// packages/ui-react/src/lib/components/Fab.tsx
import type {
  AnchorHTMLAttributes,
  ButtonHTMLAttributes,
  MouseEventHandler,
  Ref,
} from 'react';
import {
  fabStyle,
  type ComponentClassName,
  type FabInterface,
  type FabProps,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';
import { Icon } from '../icon';
import { State } from '../effects';

export type { FabSize, FabVariant } from '@udixio/core';

type ReactFabOwnProps = FabProps & {
  /** Classes or state-aware element classes applied through the shared style contract. */
  className?: ComponentClassName<FabInterface>['className'];
};

type ReactFabActionProps = ReactFabOwnProps &
  Omit<
    ButtonHTMLAttributes<HTMLButtonElement>,
    keyof ReactFabOwnProps | 'children' | 'className' | 'onClick'
  > & {
    href?: undefined;
    ref?: Ref<HTMLButtonElement>;
    onClick?: MouseEventHandler<HTMLButtonElement>;
  };

type ReactFabLinkProps = ReactFabOwnProps &
  Omit<
    AnchorHTMLAttributes<HTMLAnchorElement>,
    keyof ReactFabOwnProps | 'children' | 'className' | 'onClick' | 'href'
  > & {
    href: string;
    ref?: Ref<HTMLAnchorElement>;
    onClick?: MouseEventHandler<HTMLAnchorElement>;
  };

export type ReactFabProps = ReactFabActionProps | ReactFabLinkProps;

export const useFabStyle = createUseStyle(fabStyle);

/**
 * Floating action buttons expose the primary action on a screen.
 *
 * @status stable
 * @category Action
 * @devx
 * - Requires `label` and `icon`; arbitrary children are not accepted.
 * - `type` defaults to `'button'` to prevent accidental form submissions.
 * @a11y
 * - Uses native button/link semantics, a stable accessible name, a 48px target, and visible focus.
 * @limitations
 * - No built-in positioning; placement is handled by layout.
 * - Disabled links are inert and removed from the tab order.
 * - Compose an explicit Tooltip for non-extended FABs when visual help is required.
 */
export const Fab = (props: ReactFabProps) => {
  const {
    className,
    label,
    variant = 'primary',
    size = 'medium',
    icon,
    extended = false,
    disabled = false,
  } = props;
  const styles = useFabStyle({
    variant,
    label,
    icon,
    size,
    extended,
    disabled,
    className,
  });
  const hasAccessibleLabel = label.trim() !== '';
  const content = (
    <>
      <span className={styles.touchTarget} />
      <State
        className={styles.stateLayer}
        colorName={
          variant === 'primary'
            ? 'on-primary'
            : variant === 'primaryContainer'
              ? 'on-primary-container'
              : variant === 'secondary'
                ? 'on-secondary'
                : variant === 'secondaryContainer'
                  ? 'on-secondary-container'
                  : variant === 'tertiary'
                    ? 'on-tertiary'
                    : 'on-tertiary-container'
        }
        stateClassName="state-ripple-group-[fab]"
      />
      <Icon icon={icon} className={styles.icon} />
      {extended && <span className={styles.label}>{label}</span>}
    </>
  );

  if (!hasAccessibleLabel) {
    if (
      typeof process !== 'undefined' &&
      process.env?.NODE_ENV !== 'production'
    ) {
      console.error(
        'Udixio UI: <Fab> requires a non-empty `label`. Rendering nothing.',
      );
    }
    return null;
  }

  if (props.href !== undefined) {
    const {
      className: _className,
      disabled: _disabled,
      extended: _extended,
      icon: _icon,
      label: _label,
      onClick,
      ref,
      size: _size,
      variant: _variant,
      ...nativeProps
    } = props;
    void {
      _className,
      _disabled,
      _extended,
      _icon,
      _label,
      _size,
      _variant,
    };
    return (
      <a
        {...nativeProps}
        ref={ref}
        className={styles.fab}
        href={disabled ? undefined : props.href}
        aria-label={extended ? undefined : label}
        aria-disabled={disabled || undefined}
        tabIndex={disabled ? -1 : nativeProps.tabIndex}
        role={disabled ? 'link' : nativeProps.role}
        onClick={(event) => {
          if (disabled) {
            event.preventDefault();
            event.stopPropagation();
            return;
          }
          onClick?.(event);
        }}
      >
        {content}
      </a>
    );
  }

  const {
    className: _className,
    disabled: _disabled,
    extended: _extended,
    icon: _icon,
    label: _label,
    onClick,
    ref,
    size: _size,
    variant: _variant,
    type = 'button',
    ...nativeProps
  } = props;
  void {
    _className,
    _disabled,
    _extended,
    _icon,
    _label,
    _size,
    _variant,
  };
  return (
    <button
      {...nativeProps}
      ref={ref}
      type={type}
      disabled={disabled}
      className={styles.fab}
      aria-label={extended ? undefined : label}
      onClick={onClick}
    >
      {content}
    </button>
  );
};

// packages/ui-angular/src/lib/fab/fab.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  input,
} from '@angular/core';
import {
  fabStyle,
  type ClassNameComponent,
  type FabInterface,
  type FabProps,
} from '@udixio/core';
import { createStyle } from '../utils/create-style';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';

/**
 * Floating action buttons expose the primary action on a screen.
 *
 * @status stable
 * @category Action
 * @devx
 * - Requires the `label` and `icon` inputs.
 * - `type` defaults to `'button'` to prevent accidental form submissions.
 * @a11y
 * - Uses native button/link semantics, a stable accessible name, a 48px target, and visible focus.
 * @limitations
 * - No built-in positioning; placement is handled by layout.
 * - Disabled links are inert and removed from the tab order.
 */
@Component({
  selector: 'udx-fab',
  standalone: true,
  imports: [NgTemplateOutlet, Icon, StateLayer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <ng-template #content>
      <span [class]="styles()['touchTarget']"></span>
      <udx-state-layer
        [className]="styles()['stateLayer']"
        [colorName]="stateColor()"
        stateClassName="state-ripple-group-[fab]"
      />
      <udx-icon [icon]="icon()" [className]="styles()['icon']" />
      @if (extended()) {
        <span [class]="styles()['label']">{{ label() }}</span>
      }
    </ng-template>

    @if (href() !== undefined) {
      <a
        [hidden]="!hasAccessibleLabel()"
        [class]="styles()['fab']"
        [attr.href]="disabled() ? null : href()"
        [attr.aria-label]="extended() ? null : label()"
        [attr.aria-disabled]="disabled() || !hasAccessibleLabel() || null"
        [attr.aria-hidden]="!hasAccessibleLabel() || null"
        [attr.aria-current]="ariaCurrent()"
        [attr.aria-expanded]="ariaExpanded()"
        [attr.aria-controls]="ariaControls()"
        [attr.tabindex]="disabled() || !hasAccessibleLabel() ? -1 : tabIndex()"
        [attr.target]="target()"
        [attr.rel]="rel()"
        [attr.title]="title()"
        [attr.role]="disabled() || !hasAccessibleLabel() ? 'link' : null"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </a>
    } @else {
      <button
        [hidden]="!hasAccessibleLabel()"
        [class]="styles()['fab']"
        [attr.type]="type()"
        [disabled]="disabled() || !hasAccessibleLabel()"
        [attr.aria-hidden]="!hasAccessibleLabel() || null"
        [attr.aria-label]="extended() ? null : label()"
        [attr.aria-expanded]="ariaExpanded()"
        [attr.aria-controls]="ariaControls()"
        [attr.tabindex]="tabIndex()"
        [attr.title]="title()"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </button>
    }
  `,
})
export class Fab {
  readonly label = input.required<string>();
  readonly icon = input.required<FabProps['icon']>();
  readonly variant = input<FabProps['variant']>('primary');
  readonly size = input<FabProps['size']>('medium');
  readonly extended = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Classes or state-aware element classes applied through the shared style contract. */
  readonly className = input<string | ClassNameComponent<FabInterface>>();
  /** Navigation destination; switches the inner element to a native link. */
  readonly href = input<string>();
  /** Native link browsing-context target. */
  readonly target = input<string>();
  /** Native link relationship tokens. */
  readonly rel = input<string>();
  /** Tab order override applied to the inner interactive element. */
  readonly tabIndex = input<number>();
  /** Optional native advisory title; no tooltip is generated implicitly. */
  readonly title = input<string>();
  /** Native action button type. */
  readonly type = input<'button' | 'submit' | 'reset'>('button');
  /** Current-item state for navigation links. */
  readonly ariaCurrent = input<
    boolean | 'page' | 'step' | 'location' | 'date' | 'time' | undefined
  >(undefined, { alias: 'aria-current' });
  /** Expanded state forwarded to the inner interactive element. */
  readonly ariaExpanded = input<boolean | undefined>(undefined, {
    alias: 'aria-expanded',
  });
  /** Id of the element controlled by this FAB. */
  readonly ariaControls = input<string | undefined>(undefined, {
    alias: 'aria-controls',
  });

  protected readonly hasAccessibleLabel = computed(
    () => this.label().trim() !== '',
  );

  protected readonly styles = createStyle(fabStyle, () => ({
    label: this.label(),
    icon: this.icon(),
    variant: this.variant(),
    size: this.size(),
    extended: this.extended(),
    disabled: this.disabled(),
    className: this.className(),
  }));

  protected readonly stateColor = () =>
    this.variant() === 'primary'
      ? 'on-primary'
      : this.variant() === 'primaryContainer'
        ? 'on-primary-container'
        : this.variant() === 'secondary'
          ? 'on-secondary'
          : this.variant() === 'secondaryContainer'
            ? 'on-secondary-container'
            : this.variant() === 'tertiary'
              ? 'on-tertiary'
              : 'on-tertiary-container';

  protected handleClick(event: Event): void {
    if (!this.disabled() && this.hasAccessibleLabel()) return;
    event.preventDefault();
    event.stopPropagation();
  }
}
