// packages/ui-react/src/lib/components/Tab.tsx
import React, {
  type ReactNode,
  type RefObject,
  useEffect,
  useRef,
} from 'react';

import { Icon } from '../icon';
import {
  type ReactProps,
  resolveTabSelection,
  type TabInterface,
  tabStyle,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';
import { StateLayer } from './StateLayer';

/** Payload emitted when a tab becomes the selected one. */
export type TabSelectedEvent = Pick<TabInterface['props'], 'label' | 'icon'> & {
  index: number;
  ref: RefObject<any>;
};

export type ReactTabProps = ReactProps<TabInterface> & {
  children?: ReactNode;
  /** Navigation destination; switches the inner element to a native link. */
  href?: string;
  /** Injected by the parent Tabs: this tab is the roving-tabindex stop while nothing is selected. */
  isFocusable?: boolean;
  /** Injected by the parent Tabs: whether a connected TabPanels exists (wires aria-controls). */
  hasPanels?: boolean;
  /** Injected by the parent Tabs: requests this tab becomes selected. */
  onTabSelect?: (index: number) => void;
  /** Injected by the parent Tabs: reports this tab's icon+label content element, which the sliding indicator measures for the `primary` variant. */
  contentRef?: (element: HTMLSpanElement | null) => void;
  onTabSelected?: (args: TabSelectedEvent) => void;
};

export const useTabStyle = createUseStyle(tabStyle);

/**
 * A single tab inside a `Tabs` tablist; renders as a link when `href` is
 * provided, otherwise as a button.
 * @status beta
 * @parent Tabs
 * @devx
 * - `label` can come from string children; selection is index-based and
 *   owned by the parent `Tabs` -- there is no standalone `selected` prop.
 * @a11y
 * - Exposes `id`, roving `tabIndex` (`0` on the selected or fallback tab,
 *   `-1` otherwise), and `aria-controls` pointing at the matching
 *   `TabPanel` when the tab list is connected to a `TabPanels`.
 * - `disabled` sets the native `disabled` attribute for a button tab, or
 *   `aria-disabled` and a blocked click for a link tab.
 * @limitations
 * - Horizontal layout only; there is no vertical tablist orientation.
 * - A truncated label has no built-in tooltip.
 */
export const Tab = ({
  className,
  onClick,
  label: labelProp,
  variant = 'primary',
  href,
  icon,
  disabled = false,
  selectedTab,
  isFocusable = false,
  hasPanels = false,
  tabsId,
  index,
  onTabSelect,
  contentRef,
  onTabSelected,
  children,
  ref,
  ...restProps
}: ReactTabProps) => {
  const defaultRef = useRef(null);
  const resolvedRef = ref || defaultRef;

  // children (string) can be used as an alternative to the label prop
  const label =
    labelProp ?? (typeof children === 'string' ? children : undefined);

  const isSelected = resolveTabSelection({ selectedTab, index });

  useEffect(() => {
    if (isSelected && onTabSelected) {
      onTabSelected({
        ref: resolvedRef as any,
        index: index ?? 0,
        label,
        icon,
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSelected]);

  const ElementType = href ? 'a' : 'button';

  const handleClick = (e: React.MouseEvent<any>) => {
    if (disabled) {
      if (href) e.preventDefault();
      return;
    }
    if (index != null) {
      onTabSelect?.(index);
    }
    onClick?.(e);
  };

  const styles = useTabStyle({
    label,
    icon,
    variant,
    disabled,
    index,
    selectedTab,
    tabsId,
    isSelected,
    className,
  });

  const domId =
    tabsId != null && index != null ? `tab-${tabsId}-${index}` : undefined;
  const panelId =
    hasPanels && tabsId != null && index != null
      ? `tabpanel-${tabsId}-${index}`
      : undefined;

  return (
    <ElementType
      role="tab"
      id={domId}
      aria-selected={isSelected}
      aria-controls={panelId}
      aria-disabled={href && disabled ? true : undefined}
      disabled={!href && disabled ? true : undefined}
      tabIndex={disabled ? -1 : isSelected || isFocusable ? 0 : -1}
      ref={resolvedRef as any}
      href={href}
      className={styles.tab}
      onClick={handleClick}
      {...(restProps as any)}
    >
      <StateLayer
        transitionDuration={0.3}
        className={styles.stateLayer}
        colorName={
          variant === 'primary' && isSelected ? 'primary' : 'on-surface'
        }
        stateClassName={'state-ripple-group-[tab]'}
      />
      <span ref={contentRef} className={styles.content}>
        {icon && <Icon icon={icon} className={styles.icon} />}
        <span className={styles.label}>{label}</span>
      </span>
    </ElementType>
  );
};

// packages/ui-angular/src/lib/tabs/tab.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  booleanAttribute,
  computed,
  inject,
  input,
  viewChild,
} from '@angular/core';
import {
  resolveTabSelection,
  tabStyle,
  type ClassNameComponent,
  type Icon as IconType,
  type TabInterface,
  type TabsVariant,
} from '@udixio/core';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';
import { createStyle } from '../utils/create-style';
import { TABS_CONTEXT } from './tabs-context';

/**
 * A single tab inside a `udx-tabs` tablist; renders as a link when `href` is
 * provided, otherwise as a button.
 * @status beta
 * @parent Tabs
 * @devx
 * - `label` and `icon` are the tab's content; selection is index-based and
 *   owned by the parent `udx-tabs` -- there is no standalone `selected` input.
 * @a11y
 * - Exposes `id`, roving `tabIndex` (`0` on the selected or fallback tab,
 *   `-1` otherwise), and `aria-controls` pointing at the matching
 *   `udx-tab-panel` when the tab list is connected to a `udx-tab-panels`.
 * - `disabled` sets the native `disabled` attribute for a button tab, or
 *   `aria-disabled` and a blocked click for a link tab.
 * @limitations
 * - Horizontal layout only; there is no vertical tablist orientation.
 * - A truncated label has no built-in tooltip.
 */
@Component({
  selector: 'udx-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, Icon, StateLayer],
  host: { style: 'display: contents' },
  template: `
    @if (href() !== undefined) {
      <a
        #tabEl
        role="tab"
        [id]="domId()"
        [attr.aria-selected]="isSelected()"
        [attr.aria-controls]="panelId()"
        [attr.aria-disabled]="disabled() || null"
        [attr.tabindex]="tabIndexValue()"
        [class]="styles()['tab']"
        [attr.href]="href()"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </a>
    } @else {
      <button
        #tabEl
        type="button"
        role="tab"
        [id]="domId()"
        [attr.aria-selected]="isSelected()"
        [attr.aria-controls]="panelId()"
        [disabled]="disabled()"
        [attr.tabindex]="tabIndexValue()"
        [class]="styles()['tab']"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </button>
    }

    <ng-template #content>
      <udx-state-layer
        style="transition: 0.3s"
        [className]="styles()['stateLayer']"
        [colorName]="
          variant() === 'primary' && isSelected() ? 'primary' : 'on-surface'
        "
        stateClassName="state-ripple-group-[tab]"
      />
      <span #contentEl [class]="styles()['content']">
        @if (icon()) {
          <udx-icon [icon]="icon()!" [className]="styles()['icon']" />
        }
        <span [class]="styles()['label']">{{ label() }}</span>
      </span>
    </ng-template>
  `,
})
export class Tab {
  /** Text shown for this tab. */
  readonly label = input<string>();
  /** Icon shown alongside the label. */
  readonly icon = input<IconType>();
  /** Disables pointer, keyboard, and roving-tabindex focus for this tab. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Navigation destination; switches the inner element to a native link. */
  readonly href = input<string>();
  readonly className = input<string | ClassNameComponent<TabInterface>>();

  private readonly context = inject(TABS_CONTEXT, { optional: true });

  protected readonly resolvedIndex = computed(() => this.context?.indexOf(this));
  protected readonly variant = computed<TabsVariant>(
    () => this.context?.variant() ?? 'primary',
  );
  protected readonly isSelected = computed(() =>
    resolveTabSelection({
      selectedTab: this.context?.selectedIndex() ?? null,
      index: this.resolvedIndex(),
    }),
  );
  protected readonly isFocusable = computed(
    () =>
      this.resolvedIndex() != null &&
      this.context?.focusableIndex() === this.resolvedIndex(),
  );
  protected readonly tabIndexValue = computed(() =>
    this.disabled() ? -1 : this.isSelected() || this.isFocusable() ? 0 : -1,
  );
  protected readonly domId = computed(() => {
    const tabsId = this.context?.tabsId();
    const index = this.resolvedIndex();
    return tabsId != null && index != null
      ? `tab-${tabsId}-${index}`
      : undefined;
  });
  protected readonly panelId = computed(() => {
    if (!this.context?.hasPanels()) return undefined;
    const tabsId = this.context?.tabsId();
    const index = this.resolvedIndex();
    return tabsId != null && index != null
      ? `tabpanel-${tabsId}-${index}`
      : undefined;
  });

  protected readonly styles = createStyle(tabStyle, () => ({
    label: this.label(),
    icon: this.icon(),
    variant: this.variant(),
    disabled: this.disabled(),
    index: this.resolvedIndex(),
    selectedTab: this.context?.selectedIndex() ?? null,
    tabsId: this.context?.tabsId(),
    isSelected: this.isSelected(),
    className: this.className(),
  }));

  private readonly tabElement =
    viewChild<ElementRef<HTMLElement>>('tabEl');
  private readonly contentElementRef =
    viewChild<ElementRef<HTMLSpanElement>>('contentEl');

  /** Read by the parent `udx-tabs` to focus and measure this tab. */
  get nativeElement(): HTMLElement | null {
    return this.tabElement()?.nativeElement ?? null;
  }

  /**
   * Read by the parent `udx-tabs`: the icon+label content element, which the
   * sliding indicator measures for the `primary` variant instead of the
   * full tab (`secondary` measures the tab itself).
   */
  get contentElement(): HTMLSpanElement | null {
    return this.contentElementRef()?.nativeElement ?? null;
  }

  protected handleClick(event: Event): void {
    if (this.disabled()) {
      event.preventDefault();
      return;
    }
    const index = this.resolvedIndex();
    if (index != null) {
      this.context?.select(index);
    }
  }
}
