// packages/ui-react/src/lib/components/ContextMenu.tsx
import React, {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import type { ContextMenuProps } from '@udixio/core';
import {
  createContextMenuController,
  resolveContextMenuPosition,
  resolveBoxElement,
  showContextMenuPopover,
} from '@udixio/core/dom';
import { Menu } from './Menu';

const useBrowserLayoutEffect =
  typeof window === 'undefined' ? useEffect : useLayoutEffect;

export type ReactContextMenuProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  'children' | 'className'
> &
  Omit<ContextMenuProps, 'onOpenChange'> & {
    /** Element that receives pointer and Shift+F10 context-menu activation. */
    trigger: ReactNode;
    /** MenuItem, MenuGroup, and MenuHeadline content. */
    children?: ReactNode;
    /** Notifies visibility changes caused by user interaction. */
    onOpenChange?: (open: boolean) => void;
    /** Classes applied to the display-contents root. */
    className?: string;
  };

/**
 * Opens a Menu at the pointer or keyboard context-menu position.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Project the trigger through `trigger` and Menu family elements as children.
 * @a11y Supports native context-menu events and Shift+F10, focuses the first item without scrolling the page, and restores trigger focus after Escape.
 * @limitations The popup position is internally owned and is not controllable.
 */
export const ContextMenu = ({
  trigger,
  children,
  variant = 'standard',
  accessibleLabel,
  disabled = false,
  onOpenChange,
  className,
  ...restProps
}: ReactContextMenuProps) => {
  const [position, setPosition] = useState<{ x: number; y: number } | null>(
    null,
  );
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const openRef = useRef(false);
  const getTriggerRect = () => {
    const triggerHost = triggerRef.current;
    return triggerHost
      ? resolveBoxElement(triggerHost).getBoundingClientRect()
      : undefined;
  };

  const close = useCallback(() => {
    if (!openRef.current) return;
    openRef.current = false;
    setPosition(null);
    onOpenChange?.(false);
  }, [onOpenChange]);

  const openAt = useCallback(
    (x: number, y: number) => {
      if (disabled) return;
      const wasOpen = openRef.current;
      openRef.current = true;
      setPosition({ x, y });
      if (!wasOpen) onOpenChange?.(true);
    },
    [disabled, onOpenChange],
  );

  useBrowserLayoutEffect(() => {
    if (!position) return;
    const menu = menuRef.current;
    const ownerWindow = menu?.ownerDocument.defaultView;
    if (!menu || !ownerWindow) return;
    const popup = menu.parentElement;
    if (popup) showContextMenuPopover(popup);

    const menuRect = menu.getBoundingClientRect();
    const documentElement = menu.ownerDocument.documentElement;
    const nextPosition = resolveContextMenuPosition(
      position,
      { width: menuRect.width, height: menuRect.height },
      {
        width: documentElement.clientWidth || ownerWindow.innerWidth,
        height: documentElement.clientHeight || ownerWindow.innerHeight,
      },
    );
    if (nextPosition.x !== position.x || nextPosition.y !== position.y) {
      setPosition(nextPosition);
    }
  }, [position]);

  useEffect(() => {
    if (!position) return;
    const root = rootRef.current;
    const triggerHost = triggerRef.current;
    const menu = menuRef.current;
    const triggerElement =
      triggerHost?.querySelector<HTMLElement>(
        'button, a[href], input, select, textarea, [tabindex]',
      ) ?? triggerHost;
    if (!root || !triggerElement || !menu) return;
    const controller = createContextMenuController({
      root,
      trigger: triggerElement,
      menu,
      onDismiss: close,
    });
    return () => controller.destroy();
  }, [close, position]);

  const handleContextMenu = (event: React.MouseEvent) => {
    if (disabled) return;
    event.preventDefault();
    openAt(event.clientX, event.clientY);
  };

  return (
    <div
      {...restProps}
      ref={rootRef}
      className={className}
      style={{ display: 'contents' }}
    >
      <span
        ref={triggerRef}
        style={{ display: 'contents' }}
        onContextMenu={handleContextMenu}
        onKeyDown={(event) => {
          if (event.shiftKey && event.key === 'F10') {
            event.preventDefault();
            const rect = getTriggerRect();
            openAt(rect?.left ?? 0, rect?.bottom ?? 0);
          }
        }}
      >
        {trigger}
      </span>
      {position && (
        <div
          className="fixed z-50 rounded-lg"
          popover="manual"
          style={{
            inset: 'auto',
            margin: 0,
            top: position.y,
            left: position.x,
            right: 'auto',
            bottom: 'auto',
            maxWidth: 'calc(100vw - 16px)',
            maxHeight: 'calc(100vh - 16px)',
            overflow: 'auto',
          }}
        >
          <Menu
            ref={menuRef}
            purpose="actions"
            variant={variant}
            accessibleLabel={accessibleLabel}
          >
            {children}
          </Menu>
        </div>
      )}
    </div>
  );
};

// packages/ui-svelte/src/lib/context-menu/ContextMenu.svelte
<script lang="ts">
  import {
    createContextMenuController,
    resolveContextMenuPosition,
    resolveBoxElement,
    showContextMenuPopover,
  } from '@udixio/core/dom';
  import Menu from '../menu/Menu.svelte';
  import { setMenuContext } from '../menu/menu-context.svelte';
  import type { SvelteContextMenuProps } from './context-menu.types';

  let {
    trigger,
    children,
    variant = 'standard',
    accessibleLabel,
    disabled = false,
    onOpenChange,
    class: hostClass = '',
    ...rest
  }: SvelteContextMenuProps = $props();

  let root: HTMLDivElement | undefined = $state();
  let triggerHost: HTMLSpanElement | undefined = $state();
  let menu: HTMLDivElement | undefined = $state();
  let position = $state<{ x: number; y: number } | null>(null);
  let controller: ReturnType<typeof createContextMenuController> | undefined;

  // Menu children rendered in the popup should inherit the same context as a regular Menu.
  setMenuContext({ purpose: () => 'actions', variant: () => variant, registerGroup: () => () => undefined });

  const close = () => {
    if (!position) return;
    position = null;
    onOpenChange?.(false);
  };
  const openAt = (x: number, y: number) => {
    if (disabled) return;
    const wasOpen = !!position;
    position = { x, y };
    if (!wasOpen) onOpenChange?.(true);
  };
  const handleContextMenu = (event: MouseEvent) => {
    if (disabled) return;
    event.preventDefault();
    openAt(event.clientX, event.clientY);
  };

  $effect(() => {
    if (!position || !root || !triggerHost || !menu) return;
    const triggerElement = triggerHost.querySelector<HTMLElement>('button, a[href], input, select, textarea, [tabindex]') ?? triggerHost;
    showContextMenuPopover(menu);
    const menuElement = menu.querySelector<HTMLElement>('[role="menu"]');
    if (!menuElement) return;
    const ownerWindow = root.ownerDocument.defaultView;
    if (!ownerWindow) return;
    const menuRect = menuElement.getBoundingClientRect();
    const documentElement = root.ownerDocument.documentElement;
    const nextPosition = resolveContextMenuPosition(
      position,
      { width: menuRect.width, height: menuRect.height },
      {
        width: documentElement.clientWidth || ownerWindow.innerWidth,
        height: documentElement.clientHeight || ownerWindow.innerHeight,
      },
    );
    if (nextPosition.x !== position.x || nextPosition.y !== position.y) {
      position = nextPosition;
      return;
    }
    const created = createContextMenuController({ root, trigger: triggerElement, menu: menuElement, onDismiss: close });
    controller = created;
    return () => {
      created.destroy();
      if (controller === created) controller = undefined;
    };
  });

  $effect(() => () => controller?.destroy());
</script>

<div {...rest} bind:this={root} class={hostClass} style="display: contents">
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <span
    bind:this={triggerHost}
    style="display: contents"
    oncontextmenu={handleContextMenu}
    onkeydown={(event) => {
      if (event.shiftKey && event.key === 'F10') {
        event.preventDefault();
        const rect = triggerHost
          ? resolveBoxElement(triggerHost).getBoundingClientRect()
          : undefined;
        openAt(rect?.left ?? 0, rect?.bottom ?? 0);
      }
    }}
  >
    {@render trigger?.()}
  </span>
  {#if position}
    <div bind:this={menu} class="fixed z-50 rounded-lg" role="presentation" popover="manual" style={`inset: auto; margin: 0; top: ${position.y}px; left: ${position.x}px; right: auto; bottom: auto; max-width: calc(100vw - 16px); max-height: calc(100vh - 16px); overflow: auto`}>
      <Menu purpose="actions" {variant} {accessibleLabel}>{@render children?.()}</Menu>
    </div>
  {/if}
</div>
