// packages/ui-react/src/lib/components/StateLayer.tsx
import {
  stateLayerStyle,
  type ComponentClassName,
  type StateLayerInterface,
  type StateLayerProps,
} from '@udixio/core';
import {
  createStateLayerController,
  findStateLayerTrigger,
  type StateLayerController,
} from '@udixio/core/dom';
import { useEffect, useRef, type CSSProperties, type ReactNode } from 'react';
import { createUseStyle } from '../utils/create-use-style';

export type ReactStateLayerProps = StateLayerProps &
  ComponentClassName<StateLayerInterface> & {
    style?: CSSProperties;
    children?: ReactNode;
  };

export const StateLayer = ({
  style,
  colorName,
  stateClassName = 'state-ripple-group',
  shapeTransition,
  children,
  className,
}: ReactStateLayerProps) => {
  const ref = useRef<HTMLSpanElement>(null);
  const controllerRef = useRef<StateLayerController>(null);
  const shapeTransitionRef = useRef(shapeTransition);
  shapeTransitionRef.current = shapeTransition;
  const styles = useStateLayerStyle({
    stateClassName,
    className,
    colorName,
    shapeTransition,
  });

  useEffect(() => {
    const layer = ref.current;
    if (!layer) {
      return;
    }

    const trigger = findStateLayerTrigger(layer, stateClassName);
    if (!trigger) {
      return;
    }

    const controller = createStateLayerController({
      trigger,
      layer,
      disabled: () => trigger.matches(':disabled, [aria-disabled="true"]'),
    });
    controllerRef.current = controller;
    controller.updateShape(shapeTransitionRef.current);

    return () => {
      controller.destroy();
      if (controllerRef.current === controller) {
        controllerRef.current = null;
      }
    };
  }, [stateClassName]);

  useEffect(() => {
    controllerRef.current?.updateShape(shapeTransition);
  }, [shapeTransition]);

  return (
    <span
      ref={ref}
      aria-hidden="true"
      className={styles.stateLayer}
      style={{
        ['--state-color' as any]: `var(--default-color, var(--color-${colorName}))`,
        ...style,
      }}
    >
      {children}
    </span>
  );
};

export const useStateLayerStyle = createUseStyle(stateLayerStyle);

// packages/ui-svelte/src/lib/state-layer/StateLayer.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { mergeClassNames, stateLayerStyle, type StateLayerInterface } from '@udixio/core';
  import {
    createStateLayerController,
    findStateLayerTrigger,
    type StateLayerController,
  } from '@udixio/core/dom';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteStateLayerProps } from './state-layer.types';

  let {
    colorName,
    stateClassName = 'state-ripple-group',
    shapeTransition,
    transitionDuration,
    class: hostClass = '',
    classes,
  }: SvelteStateLayerProps = $props();

  let layer: HTMLSpanElement | undefined = $state();
  let controller: StateLayerController | undefined;
  // Read through a derived so the connect effect keys off the value, not the
  // props object: a parent that spreads props would otherwise re-create the
  // controller on every unrelated update.
  const triggerClassName = $derived(stateClassName);

  const styles = createStyle(stateLayerStyle, () => ({
    colorName,
    stateClassName,
    shapeTransition,
    transitionDuration,
    className: mergeClassNames<StateLayerInterface>('stateLayer', classes, hostClass),
  }));

  $effect(() => {
    if (!layer) return;
    const trigger = findStateLayerTrigger(layer, triggerClassName);
    if (!trigger) return;

    const created = createStateLayerController({
      trigger,
      layer,
      disabled: () => trigger.matches(':disabled, [aria-disabled="true"]'),
    });
    controller = created;
    created.updateShape(untrack(() => shapeTransition));

    return () => {
      created.destroy();
      if (controller === created) {
        controller = undefined;
      }
    };
  });

  $effect(() => {
    controller?.updateShape(shapeTransition);
  });
</script>

<span
  bind:this={layer}
  aria-hidden="true"
  class={styles.current['stateLayer']}
  style:--state-color={`var(--color-${colorName}, var(--color-on-surface))`}
  style:transition={transitionDuration === undefined ? undefined : `${transitionDuration}s`}
></span>
