// apps/doc/src/examples/angular/button-toggle.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Button } from '@udixio/ui-angular';

@Component({
  selector: 'docs-button-toggle-angular',
  standalone: true,
  imports: [Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <lib-button
      [label]="pressed() ? 'Notifications enabled' : 'Notifications disabled'"
      toggleable
      [pressed]="pressed()"
      (pressedChange)="pressed.set($event)"
      variant="tonal"
    />
  `,
})
export class ButtonToggleAngular {
  protected readonly pressed = signal(false);
}

// apps/doc/src/examples/react/button-toggle.tsx
import { useState } from 'react';
import { Button } from '@udixio/ui-react';

export default function ButtonToggleReact() {
  const [pressed, setPressed] = useState(false);

  return (
    <Button
      label={pressed ? 'Notifications enabled' : 'Notifications disabled'}
      toggleable
      pressed={pressed}
      onPressedChange={setPressed}
      variant="tonal"
    />
  );
}
