// apps/doc/src/examples/svelte/checkbox-mixed-selection.svelte
<script lang="ts">
  import { Checkbox } from '@udixio/ui-svelte';

  type Channel = 'email' | 'sms';

  let channels = $state<Record<Channel, boolean>>({ email: true, sms: false });
  const values = $derived(Object.values(channels));
  const allChecked = $derived(values.every(Boolean));
  const someChecked = $derived(values.some(Boolean));

  const setAll = (checked: boolean) => {
    channels = { email: checked, sms: checked };
  };

  const setChannel = (channel: Channel, checked: boolean) => {
    channels = { ...channels, [channel]: checked };
  };
</script>

<div class="flex flex-col gap-3">
  <div class="flex items-center gap-3">
    <Checkbox
      id="checkbox-svelte-notifications"
      bind:checked={() => allChecked, setAll}
      indeterminate={someChecked && !allChecked}
    />
    <label for="checkbox-svelte-notifications">Notifications</label>
  </div>
  <div class="ml-6 flex flex-col gap-3">
    <div class="flex items-center gap-3">
      <Checkbox
        id="checkbox-svelte-email"
        bind:checked={() => channels.email, (checked) => setChannel('email', checked)}
      />
      <label for="checkbox-svelte-email">Email</label>
    </div>
    <div class="flex items-center gap-3">
      <Checkbox
        id="checkbox-svelte-sms"
        bind:checked={() => channels.sms, (checked) => setChannel('sms', checked)}
      />
      <label for="checkbox-svelte-sms">SMS</label>
    </div>
  </div>
</div>

// apps/doc/src/examples/react/checkbox-mixed-selection.tsx
import { useState } from 'react';
import { Checkbox } from '@udixio/ui-react';

type Channel = 'email' | 'sms';

export default function CheckboxMixedSelectionReact() {
  const [channels, setChannels] = useState<Record<Channel, boolean>>({
    email: true,
    sms: false,
  });
  const values = Object.values(channels);
  const allChecked = values.every(Boolean);
  const someChecked = values.some(Boolean);

  const setAll = (checked: boolean) => {
    setChannels({ email: checked, sms: checked });
  };

  const setChannel = (channel: Channel, checked: boolean) => {
    setChannels((current) => ({ ...current, [channel]: checked }));
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-3">
        <Checkbox
          id="checkbox-react-notifications"
          checked={allChecked}
          indeterminate={someChecked && !allChecked}
          onCheckedChange={setAll}
        />
        <label htmlFor="checkbox-react-notifications">Notifications</label>
      </div>
      <div className="ml-6 flex flex-col gap-3">
        <div className="flex items-center gap-3">
          <Checkbox
            id="checkbox-react-email"
            checked={channels.email}
            onCheckedChange={(checked) => setChannel('email', checked)}
          />
          <label htmlFor="checkbox-react-email">Email</label>
        </div>
        <div className="flex items-center gap-3">
          <Checkbox
            id="checkbox-react-sms"
            checked={channels.sms}
            onCheckedChange={(checked) => setChannel('sms', checked)}
          />
          <label htmlFor="checkbox-react-sms">SMS</label>
        </div>
      </div>
    </div>
  );
}
