// apps/doc/src/examples/angular/chip-input.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Chip } from '@udixio/ui-angular';

@Component({
  selector: 'docs-chip-input-angular',
  standalone: true,
  imports: [Chip],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-wrap gap-2">
      @for (tag of tags(); track tag) {
        <lib-chip [label]="tag" removable (remove)="removeTag(tag)" />
      }
    </div>
  `,
})
export class ChipInputAngular {
  protected readonly tags = signal(['React', 'TypeScript', 'Angular']);

  protected removeTag(tag: string): void {
    this.tags.update((current) => current.filter((item) => item !== tag));
  }
}

// apps/doc/src/examples/react/chip-input.tsx
import { useState } from 'react';
import { Chip } from '@udixio/ui-react';

export default function ChipInputReact() {
  const [tags, setTags] = useState(['React', 'TypeScript', 'Angular']);

  return (
    <div className="flex flex-wrap gap-2">
      {tags.map((tag) => (
        <Chip
          key={tag}
          label={tag}
          onRemove={() =>
            setTags((current) => current.filter((item) => item !== tag))
          }
        />
      ))}
    </div>
  );
}
