// apps/doc/src/examples/angular/fab-actions.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Fab } from '@udixio/ui-angular';
import { iAdd } from '@udixio/icons-rounded-400/add';
import { iShare } from '@udixio/icons-rounded-400/share';

@Component({
  selector: 'docs-fab-actions-angular',
  standalone: true,
  imports: [Fab],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="grid w-full gap-8">
      <section class="grid gap-3">
        <h3 class="text-title-medium">Color families</h3>
        <div class="flex flex-wrap items-end gap-4">
          <udx-fab label="Primary" [icon]="addIcon" variant="primary" />
          <udx-fab label="Secondary" [icon]="shareIcon" variant="secondary" />
          <udx-fab label="Tertiary" [icon]="addIcon" variant="tertiary" />
          <udx-fab
            label="Primary container"
            [icon]="addIcon"
            variant="primaryContainer"
            extended
          />
          <udx-fab
            label="Secondary container"
            [icon]="shareIcon"
            variant="secondaryContainer"
            extended
          />
          <udx-fab
            label="Tertiary container"
            [icon]="addIcon"
            variant="tertiaryContainer"
            extended
          />
        </div>
      </section>

      <section class="grid gap-3">
        <h3 class="text-title-medium">Sizes and states</h3>
        <div class="flex flex-wrap items-end gap-4">
          <udx-fab label="Small" [icon]="addIcon" size="small" />
          <udx-fab label="Medium" [icon]="addIcon" size="medium" />
          <udx-fab label="Large" [icon]="addIcon" size="large" />
          <udx-fab label="Disabled action" [icon]="addIcon" disabled extended />
        </div>
      </section>
    </div>
  `,
})
export class FabActionsAngular {
  protected readonly addIcon = iAdd;
  protected readonly shareIcon = iShare;
}

// apps/doc/src/examples/react/fab-actions.tsx
import { Fab } from '@udixio/ui-react';
import { iAdd } from '@udixio/icons-rounded-400/add';
import { iShare } from '@udixio/icons-rounded-400/share';

export default function FabActionsReact() {
  return (
    <div className="grid w-full gap-8">
      <section className="grid gap-3">
        <h3 className="text-title-medium">Color families</h3>
        <div className="flex flex-wrap items-end gap-4">
          <Fab label="Primary" icon={iAdd} variant="primary" />
          <Fab label="Secondary" icon={iShare} variant="secondary" />
          <Fab label="Tertiary" icon={iAdd} variant="tertiary" />
          <Fab
            label="Primary container"
            icon={iAdd}
            variant="primaryContainer"
            extended
          />
          <Fab
            label="Secondary container"
            icon={iShare}
            variant="secondaryContainer"
            extended
          />
          <Fab
            label="Tertiary container"
            icon={iAdd}
            variant="tertiaryContainer"
            extended
          />
        </div>
      </section>

      <section className="grid gap-3">
        <h3 className="text-title-medium">Sizes and states</h3>
        <div className="flex flex-wrap items-end gap-4">
          <Fab label="Small" icon={iAdd} size="small" />
          <Fab label="Medium" icon={iAdd} size="medium" />
          <Fab label="Large" icon={iAdd} size="large" />
          <Fab label="Disabled action" icon={iAdd} disabled extended />
        </div>
      </section>
    </div>
  );
}
