// apps/doc/src/examples/angular/progress-indicator-indeterminate.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ProgressIndicator } from '@udixio/ui-angular';

@Component({
  selector: 'docs-progress-indicator-indeterminate-angular',
  standalone: true,
  imports: [ProgressIndicator],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex items-center gap-6">
      <udx-progress-indicator
        variant="linear-indeterminate"
        aria-label="Loading"
        className="w-48"
      />
      <udx-progress-indicator
        variant="circular-indeterminate"
        aria-label="Loading"
      />
    </div>
  `,
})
export class ProgressIndicatorIndeterminateAngular {}

// apps/doc/src/examples/react/progress-indicator-indeterminate.tsx
import { ProgressIndicator } from '@udixio/ui-react';

export default function ProgressIndicatorIndeterminateReact() {
  return (
    <div className="flex items-center gap-6">
      <ProgressIndicator
        variant="linear-indeterminate"
        aria-label="Loading"
        className="w-48"
      />
      <ProgressIndicator
        variant="circular-indeterminate"
        aria-label="Loading"
      />
    </div>
  );
}
