// apps/doc/src/examples/angular/search-avatar.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Search } from '@udixio/ui-angular';

@Component({
  selector: 'docs-search-avatar-angular',
  standalone: true,
  imports: [Search],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <udx-search label="Search workspace" placeholder="Search workspace">
      <span
        search-avatar
        class="flex size-[30px] items-center justify-center rounded-full bg-primary text-label-small text-on-primary"
        aria-hidden="true"
      >
        JD
      </span>
    </udx-search>
  `,
})
export class SearchAvatarAngular {}

// apps/doc/src/examples/react/search-avatar.tsx
import { Search } from '@udixio/ui-react';

export default function SearchAvatarReact() {
  return (
    <Search
      label="Search workspace"
      placeholder="Search workspace"
      avatar={
        <span
          className="flex size-[30px] items-center justify-center rounded-full bg-primary text-label-small text-on-primary"
          aria-hidden="true"
        >
          JD
        </span>
      }
    />
  );
}
