// apps/doc/src/examples/angular/slider-basic.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Slider } from '@udixio/ui-angular';

@Component({
  selector: 'slider-basic-angular-example',
  standalone: true,
  imports: [Slider],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex w-72 flex-col gap-4">
      <udx-slider
        name="volume"
        [defaultValue]="30"
        [step]="10"
        (valueChange)="value = $event"
        aria-label="Volume"
      />
      <p class="text-body-medium">Value: {{ value }}</p>
    </div>
  `,
})
export class SliderBasicAngular {
  protected value = 30;
}

// apps/doc/src/examples/react/slider-basic.tsx
import { useState } from 'react';
import { Slider } from '@udixio/ui-react';

export default function SliderBasicReact() {
  const [value, setValue] = useState(30);

  return (
    <div className="flex w-72 flex-col gap-4">
      <Slider
        name="volume"
        defaultValue={30}
        step={10}
        onChange={setValue}
        aria-label="Volume"
      />
      <p className="text-body-medium">Value: {value}</p>
    </div>
  );
}
