// apps/doc/src/examples/angular/slider-controlled.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Slider } from '@udixio/ui-angular';

@Component({
  selector: 'slider-controlled-angular-example',
  standalone: true,
  imports: [Slider],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex w-72 flex-col gap-4">
      <udx-slider
        name="brightness"
        [(value)]="value"
        [step]="10"
        aria-label="Brightness"
      />
      <p class="text-body-medium">Value: {{ value }}</p>
    </div>
  `,
})
export class SliderControlledAngular {
  protected value = 50;
}

// apps/doc/src/examples/react/slider-controlled.tsx
import { useState } from 'react';
import { Slider } from '@udixio/ui-react';

export default function SliderControlledReact() {
  const [value, setValue] = useState(50);

  return (
    <div className="flex w-72 flex-col gap-4">
      <Slider
        name="brightness"
        value={value}
        step={10}
        onChange={setValue}
        aria-label="Brightness"
      />
      <p className="text-body-medium">Value: {value}</p>
    </div>
  );
}
