// apps/doc/src/examples/angular/snackbar-basic.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Button, Snackbar } from '@udixio/ui-angular';

@Component({
  selector: 'docs-snackbar-basic-angular',
  standalone: true,
  imports: [Button, Snackbar],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col items-start gap-4">
      <lib-button label="Send message" (click)="open = true" />
      <lib-snackbar
        message="Message sent"
        [open]="open"
        (openChange)="open = $event"
      />
    </div>
  `,
})
export class SnackbarBasicAngular {
  protected open = false;
}

// apps/doc/src/examples/react/snackbar-basic.tsx
import { useState } from 'react';
import { Button, Snackbar } from '@udixio/ui-react';

export default function SnackbarBasicReact() {
  const [open, setOpen] = useState(false);

  return (
    <div className="flex flex-col items-start gap-4">
      <Button label="Send message" onClick={() => setOpen(true)} />
      <Snackbar
        message="Message sent"
        open={open}
        onOpenChange={setOpen}
      />
    </div>
  );
}
