// apps/doc/src/examples/angular/snackbar-auto-dismiss.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Button, Snackbar } from '@udixio/ui-angular';

@Component({
  selector: 'docs-snackbar-auto-dismiss-angular',
  standalone: true,
  imports: [Button, Snackbar],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col items-start gap-4">
      <lib-button label="Save" (click)="open = true" />
      <lib-snackbar
        message="Saved"
        [duration]="3000"
        [open]="open"
        (openChange)="open = $event"
      />
    </div>
  `,
})
export class SnackbarAutoDismissAngular {
  protected open = false;
}

// apps/doc/src/examples/react/snackbar-auto-dismiss.tsx
import { useState } from 'react';
import { Button, Snackbar } from '@udixio/ui-react';

export default function SnackbarAutoDismissReact() {
  const [open, setOpen] = useState(false);

  return (
    <div className="flex flex-col items-start gap-4">
      <Button label="Save" onClick={() => setOpen(true)} />
      <Snackbar
        message="Saved"
        duration={3000}
        open={open}
        onOpenChange={setOpen}
      />
    </div>
  );
}
