// apps/doc/src/examples/angular/tooltip-controlled.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Button, Tooltip } from '@udixio/ui-angular';

@Component({
  selector: 'docs-tooltip-controlled-angular',
  standalone: true,
  imports: [Button, Tooltip],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex items-center gap-6 p-8">
      <udx-button
        [label]="open() ? 'Hide' : 'Show'"
        (click)="open.set(!open())"
        udxTooltip="Controlled tooltip"
        [udxTooltipOpen]="open()"
        (udxTooltipOpenChange)="open.set($event)"
      />
    </div>
  `,
})
export class TooltipControlledAngular {
  protected readonly open = signal(false);
}

// apps/doc/src/examples/react/tooltip-controlled.tsx
import { useState } from 'react';
import { Button, Tooltip } from '@udixio/ui-react';

export default function TooltipControlledReact() {
  const [open, setOpen] = useState(false);

  return (
    <div className="flex items-center gap-6 p-8">
      <Tooltip text="Controlled tooltip" open={open} onOpenChange={setOpen}>
        <Button label={open ? 'Hide' : 'Show'} onClick={() => setOpen(!open)} />
      </Tooltip>
    </div>
  );
}
