// packages/ui-react/src/lib/components/TextField.tsx
import React, { useEffect, useId, useMemo, useRef, useState } from 'react';
import { Icon } from '../icon';
import {
  faCalendarDays,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
} from '@fortawesome/free-solid-svg-icons';
import { motion } from 'motion/react';
import { DatePicker } from './DatePicker';
import { Button } from './Button';
import { Menu } from './Menu';
import { MenuItem } from './MenuItem';
import { Divider } from './Divider';
import { MenuHeadline } from './MenuHeadline';

import TextareaAutosize from 'react-textarea-autosize';
import { useTextFieldStyle } from '../styles/text-field.style';
import { classNames } from '../utils';
import { ReactProps } from '../utils/component';
import { AnchorPositioner } from './AnchorPositioner';
import { TextFieldInterface } from '../interfaces';

/**
 * Text fields let users enter text into a UI
 * @status beta
 * @category Input
 * @devx
 * - Supports controlled (`value`) and uncontrolled (`defaultValue`) usage.
 * - `multiline` switches to textarea mode.
 * - `type="select" ` switches to select mode with `options`
 * @a11y
 * - `aria-describedby` links supporting text/error to input.
 */
export const TextField = ({
  variant = 'filled',
  autoFocus,
  disabled = false,
  errorText,
  placeholder,
  suffix,
  name,
  label,
  className,
  supportingText,
  trailingIcon,
  leadingIcon,
  type = 'text',
  multiline = false,
  autoComplete = 'on',
  onChange,
  value: valueProp,
  defaultValue,
  showSupportingText,
  id: idProp,
  style,
  ref,
  onFocus,
  onBlur,
  options,
  children,
  ...restProps
}: ReactProps<TextFieldInterface> & { children?: React.ReactNode }) => {
  const generatedId = useId();
  const id = idProp || generatedId;
  const helperTextId = `${id}-helper`;

  const isControlled = valueProp !== undefined;
  const [internalValue, setInternalValue] = useState(defaultValue ?? '');
  const value = isControlled ? valueProp : internalValue;

  const [isFocused, setIsFocused] = useState(false);
  const [showErrorIcon, setShowErrorIcon] = useState(!!errorText?.length);

  const internalRef = useRef<HTMLInputElement | HTMLTextAreaElement>(null);
  const inputRef = (ref as any) || internalRef;

  const textFieldRef = useRef<HTMLDivElement>(null);
  const calendarTriggerRef = useRef<HTMLDivElement>(null);
  const datePickerRef = useRef<HTMLDivElement>(null);

  const hasSupportingText =
    showSupportingText ?? (!!errorText?.length || !!supportingText?.length);

  useEffect(() => {
    setShowErrorIcon(!!errorText?.length);
  }, [errorText]);

  const focusInput = () => {
    if (inputRef.current && !isFocused && !disabled) {
      if (type !== 'select') {
        inputRef.current.focus();
      }
    }
  };

  useEffect(() => {
    if (!autoFocus || disabled) return;

    if (type !== 'select') {
      const rafId = window.requestAnimationFrame(() => {
        focusInput();
      });
      return () => window.cancelAnimationFrame(rafId);
    }
  }, [autoFocus, disabled, inputRef, type]);

  useEffect(() => {
    if (isFocused) {
      setShowErrorIcon(false);
      onFocus?.();
    } else {
      if (errorText?.length) {
        setShowErrorIcon(true);
      }
      onBlur?.();
    }
  }, [isFocused]);

  const handleChange = (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const newValue = event.target.value;

    if (!isControlled) {
      setInternalValue(newValue);
    }

    setShowErrorIcon(false);

    if (onChange) {
      onChange(event);
    }
  };

  // Date Picker Logic
  const isDateInput = type === 'date';
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [tempDate, setTempDate] = useState<Date | null>(null);

  const initialDateValue = useMemo(() => {
    const val = String(value);
    if (!val) return null;
    const [y, m, d] = val.split('-').map(Number);
    if (y && m && d) return new Date(y, m - 1, d);
    return null;
  }, [value]);

  const handleDatePickerToggle = () => {
    if (disabled) return;
    if (showDatePicker) {
      setShowDatePicker(false);
    } else {
      setTempDate(initialDateValue);
      setShowDatePicker(true);
    }
  };

  useEffect(() => {
    if (showDatePicker) {
      setIsFocused(true);
    } else if (!isSelectInput || !showMenu) {
      setIsFocused(false);
    }
  }, [showDatePicker]);

  useEffect(() => {
    if (!showDatePicker) return;

    const isInside = (target: Node | null) => {
      if (!target) return false;
      return (
        textFieldRef.current?.contains(target) ||
        datePickerRef.current?.contains(target)
      );
    };

    const handlePointerDown = (e: PointerEvent) => {
      const target = e.target as Node;
      const inDatePicker = datePickerRef.current?.contains(target);
      const inCalendarTrigger = calendarTriggerRef.current?.contains(target);
      if (!inDatePicker && !inCalendarTrigger) {
        setShowDatePicker(false);
      }
    };

    const handleFocusIn = (e: FocusEvent) => {
      if (!isInside(e.target as Node)) {
        setShowDatePicker(false);
      }
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setShowDatePicker(false);
      }
    };

    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('focusin', handleFocusIn);
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('focusin', handleFocusIn);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [showDatePicker]);

  const handleDateConfirm = () => {
    const newValue = tempDate ? tempDate.toLocaleDateString('en-CA') : '';

    if (!isControlled) {
      setInternalValue(newValue);
    }

    if (onChange) {
      const event = {
        target: {
          value: newValue,
          name,
          type,
        },
      } as React.ChangeEvent<HTMLInputElement>;
      onChange(event);
    }
    setShowDatePicker(false);
  };

  // Select Logic
  const isSelectInput = type === 'select';
  const [showMenu, setShowMenu] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const displayValue = useMemo(() => {
    if (isSelectInput && options) {
      const selectedOption = options.find(
        (o) => String(o.value) === String(value),
      );
      return selectedOption ? selectedOption.label : value;
    }
    return value;
  }, [value, isSelectInput, options]);

  const handleSelectToggle = () => {
    if (disabled) return;
    setShowMenu(!showMenu);
    setIsFocused(!showMenu);
  };

  const handleSelectOption = (optionValue: string | number) => {
    if (!isControlled) {
      setInternalValue(String(optionValue));
    }

    if (onChange) {
      const event = {
        target: {
          value: String(optionValue),
          name,
          type,
        },
      } as React.ChangeEvent<HTMLInputElement>;
      onChange(event);
    }
    setShowMenu(false);
    setIsFocused(false);
  };

  // Close menu on outside click
  useEffect(() => {
    if (!showMenu) return;
    const handleClickOutside = (event: MouseEvent) => {
      if (
        textFieldRef.current &&
        !textFieldRef.current.contains(event.target as Node) &&
        menuRef.current &&
        !menuRef.current.contains(event.target as Node)
      ) {
        setShowMenu(false);
        setIsFocused(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showMenu]);

  const effectiveTrailingIcon = useMemo(() => {
    if (trailingIcon) return trailingIcon;
    if (isDateInput) return faCalendarDays;
    if (isSelectInput) return showMenu ? faChevronUp : faChevronDown;
    return undefined;
  }, [trailingIcon, isDateInput, isSelectInput, showMenu]);

  // Enhance styles for date input or select
  const inputSpecialClass =
    isDateInput || isSelectInput
      ? '[&::-webkit-calendar-picker-indicator]:hidden cursor-pointer selection:bg-transparent'
      : '';

  const styles = useTextFieldStyle({
    showSupportingText: hasSupportingText,
    isFocused,
    showErrorIcon,
    disabled,
    name,
    label,
    autoComplete,
    className,
    onChange,
    placeholder,
    supportingText,
    type,
    leadingIcon,
    trailingIcon: effectiveTrailingIcon,
    variant,
    errorText,
    value: String(displayValue),
    suffix,
    multiline,
  });

  const TextComponent = multiline ? TextareaAutosize : 'input';
  // For select, we want the input to be readOnly but still focusable?
  // Actually, for better UX, standard select inputs are often readOnly text fields.
  const textComponentProps = multiline
    ? {}
    : {
        type: isSelectInput ? 'text' : type,
        readOnly: isSelectInput,
      };

  const isFloating =
    isFocused ||
    (typeof value === 'string' && value.length > 0) ||
    type == 'date' ||
    (isSelectInput && showMenu);

  const showLegend = isFloating && variant === 'outlined';
  const showLabel = !showLegend;

  return (
    <div ref={textFieldRef} className={styles.textField} style={style}>
      <fieldset
        onClick={() => {
          if (isSelectInput) handleSelectToggle();
          else focusInput();
        }}
        className={styles.content}
        role="presentation"
      >
        <div className={styles.stateLayer}></div>
        {leadingIcon && (
          <div className={styles.leadingIcon}>
            {React.isValidElement(leadingIcon) ? (
              leadingIcon
            ) : (
              <Icon className={'w-5 h-5'} icon={leadingIcon}></Icon>
            )}
          </div>
        )}

        <motion.legend
          aria-hidden="true"
          variants={{
            hidden: { width: 0, padding: 0 },
            visible: { width: 'auto', padding: '0 8px' },
          }}
          initial={showLegend ? 'visible' : 'hidden'}
          animate={showLegend ? 'visible' : 'hidden'}
          className={
            'max-w-full ml-2 px-2 text-body-small h-0 overflow-hidden whitespace-nowrap'
          }
          transition={{ duration: 0.2 }}
        >
          <span className={'transform inline-flex -translate-y-1/2 opacity-0'}>
            {label}
          </span>
        </motion.legend>

        <div className={'flex-1 relative'}>
          {showLabel && (
            <motion.label
              htmlFor={id}
              className={classNames(
                'absolute left-4  transition-all duration-300 pointer-events-none',
                {
                  'text-body-small top-2': variant == 'filled' && isFloating,
                  'text-body-large top-1/2 transform -translate-y-1/2': !(
                    variant == 'filled' && isFloating
                  ),
                },
              )}
              transition={{ duration: 0.3 }}
              layoutId={variant === 'outlined' ? `${id}-label` : undefined}
            >
              <span className={styles.label}>{label}</span>
            </motion.label>
          )}

          {showLegend && (
            <motion.label
              htmlFor={id}
              className={classNames(
                'absolute left-2 -top-3 px-1 text-body-small z-10',
                styles.label,
              )}
              layoutId={`${id}-label`}
              transition={{ duration: 0.3 }}
            >
              {label}
            </motion.label>
          )}

          <TextComponent
            {...(restProps as any)}
            ref={inputRef as any}
            value={displayValue} // Use displayValue for select
            onChange={handleChange}
            className={classNames(styles.input, inputSpecialClass)}
            id={id}
            name={name}
            placeholder={isFocused ? (placeholder ?? undefined) : ''}
            onFocus={() => {
              if (!isSelectInput) setIsFocused(true);
            }}
            onBlur={() => {
              // For select, we manage focus manually with menu state usually
              if (!isSelectInput) setIsFocused(false);
            }}
            disabled={disabled}
            autoComplete={autoComplete}
            aria-invalid={!!errorText?.length}
            aria-describedby={hasSupportingText ? helperTextId : undefined}
            {...textComponentProps}
          />
        </div>

        <div className={styles.activeIndicator}></div>

        {!showErrorIcon && (
          <>
            {effectiveTrailingIcon && (
              <div
                ref={isDateInput ? calendarTriggerRef : undefined}
                onClick={(event) => {
                  event.stopPropagation();
                  if (isDateInput) handleDatePickerToggle();
                  if (isSelectInput) handleSelectToggle();
                }}
                className={classNames(
                  styles.trailingIcon,
                  (isDateInput || isSelectInput) && 'cursor-pointer',
                )}
              >
                <div className="flex items-center justify-center w-full h-full">
                  {React.isValidElement(effectiveTrailingIcon) ? (
                    effectiveTrailingIcon
                  ) : (
                    <Icon
                      className={'h-5'}
                      icon={effectiveTrailingIcon as any}
                    />
                  )}
                </div>
              </div>
            )}
            {!effectiveTrailingIcon && suffix && (
              <span className={styles.suffix}>{suffix}</span>
            )}
          </>
        )}

        {showErrorIcon && (
          <div
            className={classNames(styles.trailingIcon, {
              ' absolute right-0': !effectiveTrailingIcon,
            })}
          >
            <Icon
              className={'h-5 text-error'}
              icon={faCircleExclamation}
            ></Icon>
          </div>
        )}
      </fieldset>

      {hasSupportingText && (
        <p className={styles.supportingText} id={helperTextId}>
          {errorText?.length
            ? errorText
            : supportingText?.length
              ? supportingText
              : '\u00A0'}
        </p>
      )}

      {isDateInput && showDatePicker && (
        <>
          <AnchorPositioner anchorRef={textFieldRef} position="bottom">
            <div
              ref={datePickerRef}
              className="z-50 shadow-xl rounded-[28px] bg-surface-container-high overflow-hidden"
            >
              <DatePicker
                className={''}
                value={tempDate}
                onChange={setTempDate}
              />
              <div className="flex justify-end gap-2 p-4 pt-0">
                <Button
                  variant="text"
                  size="small"
                  onClick={() => setShowDatePicker(false)}
                >
                  Cancel
                </Button>
                <Button
                  variant="filled"
                  size="small"
                  onClick={handleDateConfirm}
                >
                  OK
                </Button>
              </div>
            </div>
          </AnchorPositioner>
        </>
      )}

      {isSelectInput && showMenu && (
        <AnchorPositioner
          anchorRef={textFieldRef}
          position="bottom"
          style={{ width: textFieldRef.current?.offsetWidth }}
        >
          <div ref={menuRef}>
            <Menu selected={value}>
              {children
                ? React.Children.map(children, (child) => {
                    if (
                      React.isValidElement(child) &&
                      child.type === MenuItem
                    ) {
                      return React.cloneElement(child, {
                        onClick: (e: React.MouseEvent) => {
                          if (child.props.onClick) {
                            child.props.onClick(e);
                          }
                          handleSelectOption(child.props.value ?? '');
                        },
                      } as any);
                    }
                    return child;
                  })
                : options?.map((opt, i) => {
                    if (opt.type === 'divider') {
                      return <Divider key={i} className="my-1" />;
                    }
                    if (opt.type === 'headline') {
                      return <MenuHeadline key={i} label={opt.label} />;
                    }
                    return (
                      <MenuItem
                        key={opt.value ?? i}
                        onClick={(e) => {
                          if (opt.onClick) {
                            opt.onClick(e);
                          }
                          handleSelectOption(opt.value ?? '');
                        }}
                        {...opt}
                      >
                        {opt.label}
                      </MenuItem>
                    );
                  })}
            </Menu>
          </div>
        </AnchorPositioner>
      )}
    </div>
  );
};

// packages/ui-angular/src/lib/text-field/text-field.ts
import { DOCUMENT } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  viewChild,
  type OnInit,
} from '@angular/core';
import {
  classNames,
  formatTextFieldIsoDate,
  parseTextFieldIsoDate,
  resolveTextFieldFloating,
  resolveTextFieldTrailingIcon,
  sanitizeTextFieldDateInput,
  textFieldStyle,
  type ClassNameComponent,
  type DatePickerValue,
  type Icon as IconType,
  type TextFieldInterface,
  type TextFieldOption,
} from '@udixio/core';
import {
  createTextFieldLabelController,
  createTextareaAutosizeController,
  type TextFieldLabelController,
  type TextareaAutosizeController,
} from '@udixio/core/dom';
import { iCalendarToday } from '@udixio/icons-rounded-400/calendar_today';
import { iError } from '@udixio/icons-rounded-400/error';
import { iKeyboardArrowDown } from '@udixio/icons-rounded-400/keyboard_arrow_down';
import { iKeyboardArrowUp } from '@udixio/icons-rounded-400/keyboard_arrow_up';
import { AnchorPositioner } from '../anchor-positioner/anchor-positioner';
import { Button } from '../button/button';
import { DatePicker } from '../date-picker/date-picker';
import { Divider } from '../divider/divider';
import { Icon } from '../icon/icon';
import { Menu } from '../menu/menu';
import { MenuHeadline } from '../menu/menu-headline';
import { MenuItem } from '../menu/menu-item';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';

const optionalBooleanAttribute = (value: unknown): boolean | undefined =>
  value === undefined ? undefined : booleanAttribute(value);

let nextTextFieldId = 0;

/**
 * Text fields let users enter text into a UI.
 *
 * @status beta
 * @category Input
 * @devx
 * - `value`/`valueChange` are controlled and support `[(value)]`; `defaultValue` initializes uncontrolled usage.
 * - `multiline` switches to an auto-growing textarea.
 * - `type="select"` switches to select mode with `options`; Angular has no equivalent to React's projected `MenuItem` children, so `options` is the only way to populate the menu.
 * - `type="date"` switches to date-picker mode; the field stays typable (`YYYY-MM-DD`).
 * - `mask` transforms typed/pasted input on every keystroke (a card number, a phone number, an
 *   ID); it defaults to the built-in `YYYY-MM-DD` mask for `type="date"`, and providing one
 *   overrides it.
 * - The outlined variant's legend notch uses one `@udixio/core/dom` Anime.js Layout controller, shared with the React adapter -- an accepted exception to the rest of `@udixio/core/dom`, which uses Motion; Motion has no free equivalent to `width: auto` layout diffing. The floating label itself is a plain CSS transition.
 * @a11y
 * - `aria-describedby` links supporting text/error to the input.
 * - `aria-invalid` reflects `errorText`.
 * - The date/select trailing icon is a real `<button>` so it stays keyboard reachable.
 * @limitations
 * - Does not support projecting custom `MenuItem` content the way the React adapter does; use `options`.
 */
@Component({
  selector: 'udx-text-field',
  standalone: true,
  imports: [
    AnchorPositioner,
    Button,
    DatePicker,
    Divider,
    Icon,
    Menu,
    MenuHeadline,
    MenuItem,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div #fieldRoot [class]="styles()['textField']">
      <fieldset
        role="presentation"
        [class]="styles()['content']"
        (click)="handleFieldClick()"
      >
        <div [class]="styles()['stateLayer']"></div>

        @if (leadingIcon()) {
          <div [class]="styles()['leadingIcon']">
            <udx-icon [icon]="leadingIcon()!" className="w-5 h-5" />
          </div>
        }

        <legend #legend aria-hidden="true" [class]="styles()['legend']">
          <span class="inline-flex -translate-y-1/2 opacity-0">{{
            label()
          }}</span>
        </legend>

        <div class="flex-1 relative">
          <label [for]="resolvedId()" [class]="styles()['label']">{{
            label()
          }}</label>

          @if (multiline()) {
            <textarea
              #control
              [id]="resolvedId()"
              [name]="name() ?? null"
              [value]="displayValue()"
              [class]="classNames(styles()['input'], inputSpecialClass())"
              [placeholder]="isFocused() ? (placeholder() ?? '') : ''"
              [disabled]="disabled()"
              [attr.autocomplete]="autoComplete()"
              [attr.aria-invalid]="hasError()"
              [attr.aria-describedby]="
                hasSupportingText() ? helperTextId() : null
              "
              (input)="handleInput($event)"
              (focus)="handleControlFocus()"
              (blur)="handleControlBlur()"
            ></textarea>
          } @else {
            <input
              #control
              [id]="resolvedId()"
              [name]="name() ?? null"
              [type]="isSelectInput() || isDateInput() ? 'text' : type()"
              [readOnly]="isSelectInput()"
              [value]="displayValue()"
              [class]="classNames(styles()['input'], inputSpecialClass())"
              [placeholder]="
                isFocused()
                  ? (placeholder() ?? (isDateInput() ? 'YYYY-MM-DD' : ''))
                  : ''
              "
              [disabled]="disabled()"
              [attr.autocomplete]="autoComplete()"
              [attr.inputmode]="isDateInput() ? 'numeric' : null"
              [attr.maxlength]="isDateInput() ? 10 : null"
              [attr.aria-invalid]="hasError()"
              [attr.aria-describedby]="
                hasSupportingText() ? helperTextId() : null
              "
              (input)="handleInput($event)"
              (focus)="handleControlFocus()"
              (blur)="handleControlBlur()"
            />
          }
        </div>

        <div [class]="styles()['activeIndicator']"></div>

        @if (!showErrorIcon()) {
          @if (effectiveTrailingIcon(); as trailing) {
            @if (isDateInput() || isSelectInput()) {
              <button
                #calendarTrigger
                type="button"
                [disabled]="disabled()"
                [attr.aria-label]="
                  isDateInput() ? 'Choose date' : 'Show options'
                "
                [attr.aria-expanded]="
                  isDateInput() ? showDatePicker() : showMenu()
                "
                [class]="classNames(styles()['trailingIcon'], 'cursor-pointer')"
                (click)="handleTrailingClick($event)"
              >
                <span class="flex items-center justify-center w-full h-full">
                  <udx-icon [icon]="trailing" className="h-5" />
                </span>
              </button>
            } @else {
              <div [class]="styles()['trailingIcon']">
                <div class="flex items-center justify-center w-full h-full">
                  <udx-icon [icon]="trailing" className="h-5" />
                </div>
              </div>
            }
          } @else if (suffix()) {
            <span [class]="styles()['suffix']">{{ suffix() }}</span>
          }
        } @else {
          <div
            [class]="
              classNames(styles()['trailingIcon'], {
                ' absolute right-0': !effectiveTrailingIcon(),
              })
            "
          >
            <udx-icon [icon]="errorIcon" className="h-5 text-error" />
          </div>
        }
      </fieldset>

      @if (hasSupportingText()) {
        <p [class]="styles()['supportingText']" [id]="helperTextId()">
          {{ supportingMessage() }}
        </p>
      }

      @if (isDateInput() && showDatePicker()) {
        <udx-anchor-positioner [anchor]="rootElement()!" position="bottom">
          <div
            #datePickerPopup
            class="z-50 shadow-xl rounded-[28px] bg-surface-container-high overflow-hidden"
          >
            <udx-date-picker
              [value]="tempDate()"
              (valueChange)="handleDatePickerChange($event)"
            />
            <div class="flex justify-end gap-2 p-4 pt-0">
              <udx-button
                variant="text"
                size="small"
                label="Cancel"
                (click)="showDatePicker.set(false)"
              />
              <udx-button
                variant="filled"
                size="small"
                label="OK"
                (click)="handleDateConfirm()"
              />
            </div>
          </div>
        </udx-anchor-positioner>
      }

      @if (isSelectInput() && showMenu()) {
        <udx-anchor-positioner [anchor]="rootElement()!" position="bottom">
          <div #menuPopup class="max-w-full" [style.width.px]="rootWidth()">
            <udx-menu
              purpose="selection"
              [accessibleLabel]="label() || 'Options'"
            >
              @for (opt of options(); track opt.value ?? $index) {
                @if (opt.type === 'divider') {
                  <udx-divider class="my-1" />
                } @else if (opt.type === 'headline') {
                  @if (opt.label) {
                    <udx-menu-headline [label]="opt.label" />
                  }
                } @else {
                  <udx-menu-item
                    [label]="opt.label ?? ''"
                    [leadingIcon]="opt.leadingIcon"
                    [trailingIcon]="opt.trailingIcon"
                    [disabled]="opt.disabled ?? false"
                    [selected]="opt.value === resolvedValue()"
                    (click)="handleSelectOption(opt.value)"
                  />
                }
              }
            </udx-menu>
          </div>
        </udx-anchor-positioner>
      }
    </div>
  `,
})
export class TextField implements OnInit {
  readonly label = input.required<string>();
  readonly variant = input<TextFieldInterface['props']['variant']>('filled');
  readonly type =
    input<NonNullable<TextFieldInterface['props']['type']>>('text');
  readonly multiline = input(false, { transform: booleanAttribute });
  readonly value = input<string>();
  readonly defaultValue = input<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly name = input<string>();
  readonly id = input<string>();
  readonly placeholder = input<string>();
  readonly autoComplete = input('on');
  readonly autoFocus = input(false, { transform: booleanAttribute });
  readonly leadingIcon = input<IconType>();
  readonly trailingIcon = input<IconType>();
  readonly suffix = input<string>();
  readonly supportingText = input<string>();
  readonly errorText = input<string | null>();
  readonly showSupportingText = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  });
  /** Selectable options for `type="select"`. */
  readonly options = input<TextFieldOption[]>([]);
  /**
   * Transforms typed or pasted input into the value, on every keystroke.
   * Defaults to the built-in `YYYY-MM-DD` mask for `type="date"`; unset for
   * every other type. Providing one for `type="date"` replaces the
   * built-in mask.
   *
   * Must be idempotent (`mask(mask(x)) === mask(x)`): the field is
   * controlled, so `mask` receives its own previous output back as `raw` on
   * every subsequent keystroke. A literal you inject (a `+33` country code,
   * a fixed digit group) will be mistaken for freshly typed input on the
   * next call unless you strip it back out first.
   */
  readonly mask = input<(raw: string) => string>();
  readonly className = input<string | ClassNameComponent<TextFieldInterface>>();

  /** Emits an accepted value transition and supports `[(value)]`. */
  readonly valueChange = output<string>();
  /** Fires when the underlying control gains focus. */
  readonly focus = output<void>();
  /** Fires when the underlying control loses focus. */
  readonly blur = output<void>();

  protected readonly classNames: typeof classNames = classNames;
  protected readonly errorIcon = iError;

  private readonly generatedId = `text-field-${nextTextFieldId++}`;
  protected readonly resolvedId = computed(() => this.id() || this.generatedId);

  protected readonly helperTextId = computed(
    () => `${this.resolvedId()}-helper`,
  );

  private readonly document = inject(DOCUMENT);

  private readonly valueState = createControllableState<string>({
    value: this.value,
    defaultValue: computed(() => this.defaultValue() ?? ''),
    onChange: (next) => this.valueChange.emit(next),
    componentName: 'TextField',
    stateName: 'value',
  });

  protected readonly resolvedValue = this.valueState.value;

  protected readonly isFocused = signal(false);
  protected readonly showErrorIcon = signal(false);
  protected readonly showDatePicker = signal(false);
  protected readonly tempDate = signal<Date | null>(null);
  protected readonly showMenu = signal(false);

  protected readonly hasError = computed(() => !!this.errorText()?.length);
  protected readonly hasSupportingText = computed(
    () =>
      this.showSupportingText() ??
      (this.hasError() || !!this.supportingText()?.length),
  );
  protected readonly supportingMessage = computed(() => {
    const error = this.errorText();
    if (error?.length) return error;
    const supporting = this.supportingText();
    return supporting?.length ? supporting : ' ';
  });

  protected readonly isDateInput = computed(() => this.type() === 'date');
  protected readonly isSelectInput = computed(() => this.type() === 'select');

  protected readonly displayValue = computed(() => {
    if (this.isSelectInput()) {
      const selected = this.options().find(
        (option) => String(option.value) === this.resolvedValue(),
      );
      return selected ? String(selected.label) : this.resolvedValue();
    }
    return this.resolvedValue();
  });

  protected readonly isFloating = computed(() =>
    resolveTextFieldFloating({
      isFocused: this.isFocused(),
      hasValue: this.displayValue().length > 0,
      type: this.type(),
      isMenuOpen: this.showMenu(),
    }),
  );

  protected readonly effectiveTrailingIcon = computed(() =>
    resolveTextFieldTrailingIcon<IconType>({
      type: this.type(),
      trailingIcon: this.trailingIcon(),
      isMenuOpen: this.showMenu(),
      dateIcon: iCalendarToday,
      menuOpenIcon: iKeyboardArrowUp,
      menuClosedIcon: iKeyboardArrowDown,
    }),
  );

  protected readonly effectiveMask = computed(
    () =>
      this.mask() ??
      (this.isDateInput() ? sanitizeTextFieldDateInput : undefined),
  );

  // Select's value only ever comes from picking an option, never typing.
  protected readonly inputSpecialClass = computed(() =>
    this.isSelectInput() ? 'cursor-pointer selection:bg-transparent' : '',
  );

  protected readonly styles = createStyle(textFieldStyle, () => ({
    label: this.label(),
    variant: this.variant(),
    type: this.type(),
    multiline: this.multiline(),
    value: this.value(),
    defaultValue: this.defaultValue(),
    onChange: undefined,
    disabled: this.disabled(),
    name: this.name(),
    id: this.resolvedId(),
    placeholder: this.placeholder(),
    autoComplete: this.autoComplete(),
    autoFocus: this.autoFocus(),
    onFocus: undefined,
    onBlur: undefined,
    leadingIcon: this.leadingIcon(),
    trailingIcon: this.trailingIcon(),
    suffix: this.suffix(),
    supportingText: this.supportingText(),
    errorText: this.errorText(),
    showSupportingText: this.showSupportingText(),
    options: this.options(),
    mask: this.mask(),
    showErrorIcon: this.showErrorIcon(),
    isFocused: this.isFocused(),
    isFloating: this.isFloating(),
    hasSupportingText: this.hasSupportingText(),
    className: this.className(),
  }));

  protected readonly rootElement =
    viewChild<ElementRef<HTMLElement>>('fieldRoot');
  private readonly legendElement =
    viewChild<ElementRef<HTMLLegendElement>>('legend');
  private readonly control =
    viewChild<ElementRef<HTMLInputElement | HTMLTextAreaElement>>('control');
  private readonly calendarTrigger =
    viewChild<ElementRef<HTMLButtonElement>>('calendarTrigger');
  private readonly datePickerPopup =
    viewChild<ElementRef<HTMLElement>>('datePickerPopup');
  private readonly menuPopup = viewChild<ElementRef<HTMLElement>>('menuPopup');

  protected rootWidth(): number | undefined {
    return this.rootElement()?.nativeElement.offsetWidth;
  }

  private labelController?: TextFieldLabelController;
  private isFirstLabelUpdate = true;
  private autosizeController?: TextareaAutosizeController;
  private isFirstFocusEffect = true;

  constructor() {
    effect(() => {
      const error = this.errorText();
      this.showErrorIcon.set(!!error?.length);
    });

    effect(() => {
      if (this.showDatePicker()) {
        this.isFocused.set(true);
      } else if (!this.isSelectInput() || !this.showMenu()) {
        this.isFocused.set(false);
      }
    });

    effect(() => {
      const focused = this.isFocused();
      if (this.isFirstFocusEffect) {
        this.isFirstFocusEffect = false;
        return;
      }
      if (focused) {
        this.showErrorIcon.set(false);
        this.focus.emit();
      } else {
        if (this.errorText()?.length) this.showErrorIcon.set(true);
        this.blur.emit();
      }
    });

    afterRenderEffect((onCleanup) => {
      const shouldFocus =
        this.autoFocus() && !this.disabled() && this.type() !== 'select';
      if (!shouldFocus) return;
      const rafId = this.document.defaultView?.requestAnimationFrame(() => {
        const el = this.control()?.nativeElement;
        if (el && !this.isFocused() && !this.disabled())
          el.focus({ preventScroll: true });
      });
      onCleanup(() => {
        if (rafId !== undefined)
          this.document.defaultView?.cancelAnimationFrame(rafId);
      });
    });

    afterRenderEffect((onCleanup) => {
      // Scoped to the legend alone -- see the `root` doc on
      // `createTextFieldLabelController` for why a wider root (e.g. the
      // fieldset) would fight that element's own unrelated CSS transitions.
      const root = this.legendElement()?.nativeElement;
      if (!root) return;
      this.isFirstLabelUpdate = true;
      const controller = createTextFieldLabelController({ root });
      this.labelController = controller;
      onCleanup(() => {
        controller.destroy();
        if (this.labelController === controller)
          this.labelController = undefined;
      });
    });

    afterRenderEffect(() => {
      this.isFloating();
      this.variant();
      if (this.isFirstLabelUpdate) {
        this.isFirstLabelUpdate = false;
        return;
      }
      this.labelController?.update();
    });

    afterRenderEffect((onCleanup) => {
      if (!this.multiline()) return;
      const textarea = this.control()?.nativeElement as
        | HTMLTextAreaElement
        | undefined;
      if (!textarea) return;
      const controller = createTextareaAutosizeController({ textarea });
      this.autosizeController = controller;
      onCleanup(() => {
        controller.destroy();
        if (this.autosizeController === controller)
          this.autosizeController = undefined;
      });
    });

    afterRenderEffect(() => {
      this.displayValue();
      this.autosizeController?.update();
    });

    afterRenderEffect((onCleanup) => {
      if (!this.showDatePicker()) return;

      const isInside = (target: Node | null): boolean => {
        if (!target) return false;
        return (
          !!this.rootElement()?.nativeElement.contains(target) ||
          !!this.datePickerPopup()?.nativeElement.contains(target)
        );
      };

      const handlePointerDown = (event: PointerEvent) => {
        const target = event.target as Node;
        if (this.datePickerPopup()?.nativeElement.contains(target)) return;
        if (this.calendarTrigger()?.nativeElement.contains(target)) return;
        this.showDatePicker.set(false);
      };

      const handleFocusIn = (event: FocusEvent) => {
        if (!isInside(event.target as Node)) this.showDatePicker.set(false);
      };

      const handleKeyDown = (event: KeyboardEvent) => {
        if (event.key === 'Escape') this.showDatePicker.set(false);
      };

      this.document.addEventListener('pointerdown', handlePointerDown);
      this.document.addEventListener('focusin', handleFocusIn);
      this.document.addEventListener('keydown', handleKeyDown);

      onCleanup(() => {
        this.document.removeEventListener('pointerdown', handlePointerDown);
        this.document.removeEventListener('focusin', handleFocusIn);
        this.document.removeEventListener('keydown', handleKeyDown);
      });
    });

    afterRenderEffect((onCleanup) => {
      if (!this.showMenu()) return;

      const handleClickOutside = (event: MouseEvent) => {
        const target = event.target as Node;
        if (
          this.rootElement()?.nativeElement.contains(target) ||
          this.menuPopup()?.nativeElement.contains(target)
        ) {
          return;
        }
        this.showMenu.set(false);
        this.isFocused.set(false);
      };

      this.document.addEventListener('mousedown', handleClickOutside);
      onCleanup(() =>
        this.document.removeEventListener('mousedown', handleClickOutside),
      );
    });
  }

  ngOnInit(): void {
    this.valueState.initialize();
  }

  protected handleFieldClick(): void {
    if (this.isSelectInput()) {
      this.handleSelectToggle();
      return;
    }
    const el = this.control()?.nativeElement;
    if (el && !this.isFocused() && !this.disabled())
      el.focus({ preventScroll: true });
  }

  protected handleControlFocus(): void {
    if (!this.isSelectInput()) this.isFocused.set(true);
  }

  protected handleControlBlur(): void {
    if (!this.isSelectInput()) this.isFocused.set(false);
  }

  protected handleInput(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLTextAreaElement;
    const mask = this.effectiveMask();
    const newValue = mask ? mask(target.value) : target.value;
    this.valueState.set(newValue);
    this.showErrorIcon.set(false);
    // A controlled field whose owner rejects (or rewrites) the keystroke
    // resolves back to the same displayValue() the DOM already diverged
    // from; unlike React, Angular's `[value]` binding only writes when the
    // bound expression's result changes, so an unchanged resolved value
    // would otherwise leave the native element holding the rejected
    // keystroke. Reconcile it here, synchronously, every keystroke.
    const resolved = this.displayValue();
    if (target.value !== resolved) target.value = resolved;
  }

  protected handleTrailingClick(event: MouseEvent): void {
    event.stopPropagation();
    if (this.isDateInput()) this.handleDatePickerToggle();
    if (this.isSelectInput()) this.handleSelectToggle();
  }

  protected handleDatePickerToggle(): void {
    if (this.disabled()) return;
    if (this.showDatePicker()) {
      this.showDatePicker.set(false);
      return;
    }
    this.tempDate.set(parseTextFieldIsoDate(this.resolvedValue()));
    this.showDatePicker.set(true);
  }

  protected handleDatePickerChange(value: DatePickerValue): void {
    this.tempDate.set(value instanceof Date ? value : null);
  }

  protected handleDateConfirm(): void {
    this.valueState.set(formatTextFieldIsoDate(this.tempDate()));
    this.showDatePicker.set(false);
  }

  protected handleSelectToggle(): void {
    if (this.disabled()) return;
    const next = !this.showMenu();
    this.showMenu.set(next);
    this.isFocused.set(next);
  }

  protected handleSelectOption(value: string | number): void {
    this.valueState.set(String(value));
    this.showMenu.set(false);
    this.isFocused.set(false);
  }
}
