// packages/ui-angular/src/lib/button/button.ts
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  type OnInit,
  input,
  output,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  buttonStyle,
  getButtonProgressColor,
  getButtonPressTransition,
  getButtonShapeTransition,
  getButtonStateColor,
  resolveButtonIconPosition,
  type ButtonProps,
  type ClassNameComponent,
  type ButtonInterface,
} from '@udixio/core';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';
import { ButtonLoadingIndicator } from './button-loading-indicator';

const optionalBooleanAttribute = (value: unknown): boolean | undefined =>
  value === undefined ? undefined : booleanAttribute(value);

/**
 * Button Angular consuming the same style and interaction contracts as React.
 * `pressed` is controlled, while `defaultPressed` initializes local state.
 * The `pressed`/`pressedChange` pair also supports Angular two-way binding.
 */
@Component({
  selector: 'lib-button',
  standalone: true,
  imports: [NgTemplateOutlet, Icon, StateLayer, ButtonLoadingIndicator],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <ng-template #content>
      @if (resolvedIconPosition() === 'start' && icon(); as leadingIcon) {
        <lib-icon [icon]="leadingIcon" [className]="styles()['icon']" />
      }
      @if (loading()) {
        <span
          aria-hidden="true"
          class="!absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
        >
          <lib-button-loading-indicator [color]="progressColor()" />
        </span>
      }
      <span [class]="styles()['label']">
        <ng-content>{{ label() }}</ng-content>
      </span>
      @if (resolvedIconPosition() === 'end' && icon(); as trailingIcon) {
        <lib-icon [icon]="trailingIcon" [className]="styles()['icon']" />
      }
    </ng-template>

    @if (href() !== undefined) {
      <a
        [class]="styles()['button']"
        [attr.href]="interactionBlocked() ? null : href()"
        [attr.aria-disabled]="interactionBlocked() || null"
        [attr.aria-pressed]="isToggleButton() ? isPressed() : null"
        [attr.aria-busy]="loading() || null"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-describedby]="ariaDescribedBy()"
        [attr.aria-current]="ariaCurrent()"
        [attr.tabindex]="interactionBlocked() ? -1 : tabIndex()"
        [attr.role]="interactionBlocked() ? 'link' : null"
        [attr.target]="target()"
        [attr.rel]="rel()"
        (click)="handleClick($event)"
      >
        <span [class]="styles()['touchTarget']"></span>
        <lib-state-layer
          [className]="styles()['stateLayer']"
          [colorName]="stateColor()"
          [shapeTransition]="shapeTransition()"
          stateClassName="state-ripple-group-[button]"
        />
        <ng-container [ngTemplateOutlet]="content" />
      </a>
    } @else {
      <button
        [class]="styles()['button']"
        [attr.type]="type()"
        [disabled]="interactionBlocked()"
        [attr.aria-pressed]="isToggleButton() ? isPressed() : null"
        [attr.aria-busy]="loading() || null"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-describedby]="ariaDescribedBy()"
        [attr.tabindex]="tabIndex()"
        (click)="handleClick($event)"
      >
        <span [class]="styles()['touchTarget']"></span>
        <lib-state-layer
          [className]="styles()['stateLayer']"
          [colorName]="stateColor()"
          [shapeTransition]="shapeTransition()"
          stateClassName="state-ripple-group-[button]"
        />
        <ng-container [ngTemplateOutlet]="content" />
      </button>
    }
  `,
})
export class Button implements OnInit {
  readonly type = input<NonNullable<ButtonProps['type']>>('button');
  readonly variant = input<ButtonProps['variant']>('filled');
  readonly size = input<ButtonProps['size']>('medium');
  readonly icon = input<ButtonProps['icon']>();
  readonly iconPosition = input<ButtonProps['iconPosition']>('start');
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly disableTextMargins = input(false, { transform: booleanAttribute });
  readonly loading = input(false, { transform: booleanAttribute });
  readonly shape = input<ButtonProps['shape']>('rounded');
  readonly allowShapeTransformation = input(true, {
    transform: booleanAttribute,
  });
  readonly transition = input<ButtonProps['transition']>();
  readonly toggleable = input(false, { transform: booleanAttribute });
  readonly pressed = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  });
  readonly defaultPressed = input(false, { transform: booleanAttribute });
  readonly label = input<string>('');
  readonly className = input<string | ClassNameComponent<ButtonInterface>>();
  readonly href = input<string>();
  readonly target = input<string>();
  readonly rel = input<string>();
  readonly tabIndex = input<number>();
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: 'aria-label',
  });
  readonly ariaDescribedBy = input<string | undefined>(undefined, {
    alias: 'aria-describedby',
  });
  readonly ariaCurrent = input<
    boolean | 'page' | 'step' | 'location' | 'date' | 'time' | undefined
  >(undefined, { alias: 'aria-current' });

  readonly pressedChange = output<boolean>();

  private readonly pressedState = createControllableState({
    value: this.pressed,
    defaultValue: this.defaultPressed,
    onChange: (pressed) => this.pressedChange.emit(pressed),
    componentName: 'Button',
    stateName: 'pressed',
  });

  protected readonly isPressed = this.pressedState.value;
  protected readonly resolvedIconPosition = computed(() =>
    resolveButtonIconPosition(this.iconPosition()),
  );
  protected readonly isToggleButton = computed(
    () => this.toggleable() && this.href() === undefined,
  );
  protected readonly interactionBlocked = computed(
    () => this.disabled() || this.loading(),
  );
  protected readonly stateColor = computed(() =>
    getButtonStateColor({
      variant: this.variant(),
      toggleable: this.isToggleButton(),
      isPressed: this.isToggleButton() && this.isPressed(),
    }),
  );
  protected readonly progressColor = computed(() =>
    getButtonProgressColor({
      variant: this.variant(),
      disabled: this.disabled(),
      toggleable: this.isToggleButton(),
      isPressed: this.isToggleButton() && this.isPressed(),
    }),
  );
  protected readonly shapeTransition = computed(() =>
    getButtonShapeTransition({
      size: this.size(),
      shape: this.shape(),
      allowShapeTransformation: this.allowShapeTransformation(),
      isPressed: this.isToggleButton() && this.isPressed(),
      disabled: this.disabled() || this.loading(),
      transition: this.transition(),
    }),
  );

  protected readonly styles = createStyle(buttonStyle, () => ({
    type: this.type(),
    variant: this.variant(),
    size: this.size(),
    icon: this.icon(),
    iconPosition: this.iconPosition(),
    disabled: this.disabled(),
    disableTextMargins: this.disableTextMargins(),
    loading: this.loading(),
    shape: this.shape(),
    allowShapeTransformation: this.allowShapeTransformation(),
    transition: this.transition(),
    toggleable: this.isToggleButton(),
    pressed: this.pressed(),
    defaultPressed: this.defaultPressed(),
    label: this.label(),
    isPressed: this.isToggleButton() && this.isPressed(),
    className: this.className(),
  }));

  ngOnInit(): void {
    this.pressedState.initialize();
  }

  protected handleClick(event: Event): void {
    const interaction = getButtonPressTransition({
      disabled: this.disabled(),
      loading: this.loading(),
      toggleable: this.isToggleButton(),
      isPressed: this.isToggleButton() && this.isPressed(),
    });

    if (interaction.blocked) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    if (interaction.nextPressed === undefined) {
      return;
    }

    this.pressedState.set(interaction.nextPressed);
  }
}

// packages/ui-svelte/src/lib/button/Button.svelte
<script lang="ts">
  import {
    buttonStyle,
    getButtonPressTransition,
    getButtonProgressColor,
    getButtonShapeTransition,
    getButtonStateColor,
    mergeClassNames,
    resolveButtonIconPosition,
    type ButtonInterface,
  } from '@udixio/core';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import Icon from '../icon/Icon.svelte';
  import ProgressIndicator from '../progress-indicator/ProgressIndicator.svelte';
  import StateLayer from '../state-layer/StateLayer.svelte';
  import type { SvelteButtonProps } from './button.types';

  let {
    variant = 'filled',
    disabled = false,
    type = 'button',
    icon,
    href,
    target,
    rel,
    label,
    edgeAligned = false,
    class: hostClass = '',
    classes,
    iconPosition = 'start',
    loading = false,
    shape = 'rounded',
    toggleable = false,
    pressed = $bindable(),
    defaultPressed = false,
    onPressedChange,
    size = 'medium',
    shapeFeedback = 'morph',
    stateColor,
    transition,
    children,
    onclick,
    ...rest
  }: SvelteButtonProps = $props();

  const hasVisibleLabel = $derived(children !== undefined || (label !== undefined && label !== ''));
  const resolvedIconPosition = $derived(resolveButtonIconPosition(iconPosition));
  const isToggleButton = $derived(toggleable && href === undefined);

  const pressedState = createControllableState({
    value: () => pressed,
    defaultValue: () => defaultPressed,
    onChange: (next) => onPressedChange?.(next),
    assign: (next) => (pressed = next),
    componentName: 'Button',
    stateName: 'pressed',
  });
  const isPressed = $derived(isToggleButton && pressedState.current);
  const interactionBlocked = $derived(disabled || loading);

  const shapeTransition = $derived(
    getButtonShapeTransition({
      size,
      shape,
      shapeFeedback,
      isPressed,
      disabled: interactionBlocked,
      transition,
    }),
  );
  const resolvedStateColor = $derived(
    stateColor ?? getButtonStateColor({ variant, toggleable: isToggleButton, isPressed }),
  );
  const progressColor = $derived(
    getButtonProgressColor({ variant, disabled, toggleable: isToggleButton, isPressed }),
  );

  const styles = createStyle(buttonStyle, () => ({
    type,
    icon,
    iconPosition,
    shapeFeedback,
    stateColor,
    transition,
    size,
    edgeAligned,
    shape,
    disabled,
    loading,
    variant,
    className: mergeClassNames<ButtonInterface>('button', classes, hostClass),
    isPressed,
    toggleable: isToggleButton,
    pressed,
    defaultPressed,
    label,
  }));

  $effect(() => {
    if (hasVisibleLabel) return;
    console.error(
      'Udixio UI: <Button> requires one non-empty `label` or `children` content source. Rendering nothing.',
    );
  });

  const handleClick = (
    event: MouseEvent & { currentTarget: EventTarget & (HTMLButtonElement | HTMLAnchorElement) },
  ) => {
    const interaction = getButtonPressTransition({
      disabled,
      loading,
      toggleable: isToggleButton,
      isPressed,
    });

    if (interaction.blocked) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    if (interaction.nextPressed !== undefined) {
      pressedState.set(interaction.nextPressed);
    }
    onclick?.(event);
  };
</script>

{#snippet content()}
  <span class={styles.current['touchTarget']}></span>
  <StateLayer
    {shapeTransition}
    class={styles.current['stateLayer']}
    colorName={resolvedStateColor}
    stateClassName="state-ripple-group-[button]"
  />
  {#if resolvedIconPosition === 'start' && icon}
    <Icon {icon} class={styles.current['icon']} />
  {/if}
  {#if loading}
    <span aria-hidden="true" class="!absolute left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2">
      <!--
        `activeIndicator` always carries its own `stroke-primary` class, which wins
        over an inherited `stroke`; forcing the colour through a CSS variable with
        `!important` is what lets it apply, as in the React and Angular adapters.
      -->
      <ProgressIndicator
        classes={{
          progressIndicator: 'h-6 w-6',
          activeIndicator: '!stroke-[var(--button-progress-color)]',
        }}
        aria-hidden="true"
        style={`--button-progress-color: ${progressColor}`}
        variant="circular-indeterminate"
      />
    </span>
  {/if}
  <span class={styles.current['label']}>
    {#if children}{@render children()}{:else}{label}{/if}
  </span>
  {#if resolvedIconPosition === 'end' && icon}
    <Icon {icon} class={styles.current['icon']} />
  {/if}
{/snippet}

{#if !hasVisibleLabel}
  <!-- No content source: render nothing, as React does. -->
{:else if href !== undefined}
  <a
    {...rest}
    class={styles.current['button']}
    href={interactionBlocked ? undefined : href}
    {target}
    {rel}
    aria-disabled={interactionBlocked || undefined}
    aria-pressed={isToggleButton ? isPressed : undefined}
    aria-busy={loading || undefined}
    tabindex={interactionBlocked ? -1 : rest.tabindex}
    role={interactionBlocked ? 'link' : rest.role}
    onclick={handleClick}
  >
    {@render content()}
  </a>
{:else}
  <button
    {...rest}
    class={styles.current['button']}
    {type}
    disabled={interactionBlocked}
    aria-pressed={isToggleButton ? isPressed : undefined}
    aria-busy={loading || undefined}
    onclick={handleClick}
  >
    {@render content()}
  </button>
{/if}
