// apps/doc/src/examples/react/button-actions.tsx
import { useState } from 'react';
import { Button } from '@udixio/ui-react';

export default function ButtonActionsReact() {
  const [message, setMessage] = useState('No action yet');

  return (
    <div className="flex flex-col items-center gap-3">
      <div className="flex flex-wrap justify-center gap-3">
        <Button label="Run action" onClick={() => setMessage('Action run')} />
        <Button
          label="Button documentation"
          href="/docs/components/button"
          aria-current="page"
          variant="outlined"
        />
      </div>
      <p aria-live="polite" className="text-body-medium">
        {message}
      </p>
    </div>
  );
}

// apps/doc/src/examples/angular/button-actions.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Button } from '@udixio/ui-angular';

@Component({
  selector: 'docs-button-actions-angular',
  standalone: true,
  imports: [Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col items-center gap-3">
      <div class="flex flex-wrap justify-center gap-3">
        <lib-button label="Run action" (click)="message.set('Action run')" />
        <lib-button
          label="Button documentation"
          href="/docs/components/button"
          aria-current="page"
          variant="outlined"
        />
      </div>
      <p aria-live="polite" class="text-body-medium">{{ message() }}</p>
    </div>
  `,
})
export class ButtonActionsAngular {
  protected readonly message = signal('No action yet');
}
