// apps/doc/src/examples/react/card-actions.tsx
import { useState } from 'react';
import { Card } from '@udixio/ui-react';

export default function CardActionsReact() {
  const [message, setMessage] = useState('No action yet');

  return (
    <div className="flex w-full flex-col items-center gap-3">
      <div className="flex w-full flex-wrap gap-4">
        <Card
          href="/components/card/overview"
          variant="elevated"
          className="flex h-40 min-w-48 flex-1 items-center justify-center"
        >
          <p>Navigate to the Card page</p>
        </Card>
        <Card
          interactive
          onClick={() => setMessage('Card activated')}
          variant="filled"
          className="flex h-40 min-w-48 flex-1 items-center justify-center"
        >
          <p>Run an action</p>
        </Card>
      </div>
      <p aria-live="polite" className="text-body-medium">
        {message}
      </p>
    </div>
  );
}

// apps/doc/src/examples/angular/card-actions.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Card } from '@udixio/ui-angular';

@Component({
  selector: 'docs-card-actions-angular',
  standalone: true,
  imports: [Card],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex w-full flex-col items-center gap-3">
      <div class="flex w-full flex-wrap gap-4">
        <lib-card
          href="/components/card/overview"
          variant="elevated"
          className="flex h-40 min-w-48 flex-1 items-center justify-center"
        >
          <p>Navigate to the Card page</p>
        </lib-card>
        <lib-card
          interactive
          variant="filled"
          className="flex h-40 min-w-48 flex-1 items-center justify-center"
          (click)="message.set('Card activated')"
        >
          <p>Run an action</p>
        </lib-card>
      </div>
      <p aria-live="polite" class="text-body-medium">{{ message() }}</p>
    </div>
  `,
})
export class CardActionsAngular {
  protected readonly message = signal('No action yet');
}
