// apps/doc/src/examples/react/chips-list.tsx
import { useState } from 'react';
import { Chips } from '@udixio/ui-react';

export default function ChipsListReact() {
  const [items, setItems] = useState([{ id: 'photos', label: 'Photos', selected: true }, { id: 'videos', label: 'Videos', removable: true }]);
  return <Chips label="Media filters" items={items} onItemsChange={setItems} />;
}

// apps/doc/src/examples/angular/chips-list.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Chips } from '@udixio/ui-angular';

@Component({ selector: 'docs-chips-list-angular', standalone: true, imports: [Chips], changeDetection: ChangeDetectionStrategy.OnPush, template: `<lib-chips label="Media filters" [items]="items()" (itemsChange)="items.set($event)" />` })
export class ChipsListAngular { protected readonly items = signal([{ id: 'photos', label: 'Photos', selected: true }, { id: 'videos', label: 'Videos', removable: true }]); }
