// apps/doc/src/examples/react/text-field-variants.tsx
import { TextField } from '@udixio/ui-react';

export default function TextFieldVariantsReact() {
  return (
    <div className="flex flex-wrap items-end gap-6">
      <TextField label="Name" name="name" variant="filled" />
      <TextField label="Name" name="name2" variant="outlined" />
    </div>
  );
}

// apps/doc/src/examples/angular/text-field-variants.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { TextField } from '@udixio/ui-angular';

@Component({
  selector: 'text-field-variants-angular-example',
  standalone: true,
  imports: [TextField],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-wrap items-end gap-6">
      <lib-text-field label="Name" name="name" variant="filled" />
      <lib-text-field label="Name" name="name2" variant="outlined" />
    </div>
  `,
})
export class TextFieldVariantsAngular {}
