// apps/doc/src/examples/react/tooltip-rich.tsx
import { Button, Tooltip } from '@udixio/ui-react';

export default function TooltipRichReact() {
  return (
    <div className="flex flex-wrap items-center gap-6 p-8">
      <Tooltip
        variant="rich"
        title="Saved"
        text="Item added to favorites"
        buttons={[{ label: 'Undo' }]}
      >
        <Button label="Rich tooltip" />
      </Tooltip>
      <Tooltip
        variant="rich"
        content={
          <div>
            <strong className="text-title-small">Shortcuts</strong>
            <p className="text-body-medium">Press Cmd+K to open the command palette.</p>
          </div>
        }
      >
        <Button label="Custom content" />
      </Tooltip>
    </div>
  );
}

// apps/doc/src/examples/angular/tooltip-rich.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Button, Tooltip } from '@udixio/ui-angular';

@Component({
  selector: 'docs-tooltip-rich-angular',
  standalone: true,
  imports: [Button, Tooltip],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-wrap items-center gap-6 p-8">
      <udx-button
        label="Rich tooltip"
        udxTooltipVariant="rich"
        udxTooltipTitle="Saved"
        udxTooltip="Item added to favorites"
        [udxTooltipButtons]="{ label: 'Undo' }"
      />

      <ng-template #shortcuts>
        <strong class="text-title-small">Shortcuts</strong>
        <p class="text-body-medium">Press Cmd+K to open the command palette.</p>
      </ng-template>
      <udx-button
        label="Custom content"
        udxTooltipVariant="rich"
        [udxTooltipContent]="shortcuts"
      />
    </div>
  `,
})
export class TooltipRichAngular {}
