// apps/doc/src/examples/react/tooltip-basic.tsx
import { Button, Tooltip } from '@udixio/ui-react';

export default function TooltipBasicReact() {
  return (
    <div className="flex flex-wrap items-center gap-6 p-8">
      <Tooltip text="Copy to clipboard">
        <Button label="Hover me" />
      </Tooltip>
      <Tooltip text="Opens on click" trigger="click">
        <Button label="Click me" />
      </Tooltip>
      <Tooltip text="Top placement" position="top">
        <Button label="Top" />
      </Tooltip>
    </div>
  );
}

// apps/doc/src/examples/angular/tooltip-basic.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Button, Tooltip } from '@udixio/ui-angular';

@Component({
  selector: 'docs-tooltip-basic-angular',
  standalone: true,
  imports: [Button, Tooltip],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-wrap items-center gap-6 p-8">
      <udx-button label="Hover me" udxTooltip="Copy to clipboard" />

      <udx-button
        label="Click me"
        udxTooltip="Opens on click"
        udxTooltipTrigger="click"
      />

      <udx-button
        label="Top"
        udxTooltip="Top placement"
        udxTooltipPosition="top"
      />
    </div>
  `,
})
export class TooltipBasicAngular {}
