// packages/ui-react/src/lib/components/MenuItem.tsx
import React, { forwardRef, type ReactNode } from 'react';
import {
  classNames,
  getMenuItemRole,
  getMenuItemSelectionTransition,
  menuItemStyle,
  type MenuItemInterface,
  type MenuItemProps,
  type ReactProps,
} from '@udixio/core';
import { iCheck } from '@udixio/icons-rounded-400/check';
import { StateLayer } from './StateLayer';
import { Icon } from '../icon';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';
import { useMenuContext } from './menu-context';

export type { MenuItemSelectionType, MenuItemVariant } from '@udixio/core';

export type ReactMenuItemProps = Omit<
  ReactProps<MenuItemInterface>,
  | 'aria-checked'
  | 'aria-disabled'
  | 'aria-selected'
  | 'disabled'
  | 'leadingIcon'
  | 'role'
  | 'trailingIcon'
> & {
  /** Custom visible label content; falls back to `label`. */
  children?: ReactNode;
  /** Optional navigation target; disabled links omit the native href. */
  href?: string;
  /** Optional icon displayed before the label. Commands share this leading column when any command uses an icon; selection items keep their own indicator. */
  leadingIcon?: MenuItemProps['leadingIcon'];
  /** Optional decorative icon displayed after the label; use MenuSubmenu for a chevron that opens another menu. */
  trailingIcon?: MenuItemProps['trailingIcon'];
  /** Prevents activation, selection changes, and keyboard focus. */
  disabled?: MenuItemProps['disabled'];
};

export const useMenuItemStyle = createUseStyle(menuItemStyle);

/**
 * An action or selectable choice within a Menu.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx
 * - Use `selectionType`, `selected`, and `onSelectedChange` for controlled selection.
 * - Use `defaultSelected` when the item owns its initial selection state.
 * @a11y
 * - Resolves to `menuitem`, `menuitemradio`, `menuitemcheckbox`, or `option` from the parent Menu purpose.
 * - Disabled links are removed from navigation and expose `aria-disabled`.
 * - Use `MenuSubmenu` when the row should open another action menu.
 */
export const MenuItem = forwardRef<
  HTMLButtonElement | HTMLAnchorElement,
  ReactMenuItemProps
>(
  (
    {
      label,
      children,
      value,
      leadingIcon,
      trailingIcon,
      disabled = false,
      variant,
      href,
      selectionType: selectionTypeProp,
      selected,
      defaultSelected = false,
      onSelectedChange,
      className,
      onClick,
      ...restProps
    },
    forwardedRef,
  ) => {
    const context = useMenuContext();
    const selectionType =
      selectionTypeProp ??
      (context.purpose === 'selection' ? 'single' : 'none');
    const resolvedVariant = variant ?? context.variant;
    const [isSelected, setSelected] = useControllableState({
      value: selected,
      defaultValue: defaultSelected,
      onChange: onSelectedChange,
      componentName: 'MenuItem',
      stateName: 'selected',
    });
    const role = getMenuItemRole({
      purpose: context.purpose,
      selectionType,
    });
    const usesActionIconSlot =
      context.purpose === 'actions' && selectionType === 'none';
    const resolvedLeadingIcon =
      isSelected && selectionType !== 'none' ? iCheck : leadingIcon;
    const styles = useMenuItemStyle({
      label,
      value,
      leadingIcon,
      trailingIcon,
      disabled,
      variant: resolvedVariant,
      selectionType,
      selected,
      defaultSelected,
      onSelectedChange,
      isSelected,
      purpose: context.purpose,
      className,
    });

    const activate = (
      event: React.MouseEvent<HTMLButtonElement | HTMLAnchorElement>,
    ) => {
      if (disabled) {
        event.preventDefault();
        return;
      }
      const transition = getMenuItemSelectionTransition({
        disabled,
        selectionType,
        selected: isSelected,
      });
      if (transition.nextSelected !== undefined) {
        setSelected(transition.nextSelected);
      }
      (
        onClick as
          | React.MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>
          | undefined
      )?.(event);
    };

    const sharedProps = {
      ...restProps,
      ref: forwardedRef,
      className: styles.menuItem,
      role,
      'aria-disabled': disabled || undefined,
      'aria-selected':
        role === 'option' ? (isSelected ? 'true' : 'false') : undefined,
      'aria-checked':
        role === 'menuitemcheckbox' || role === 'menuitemradio'
          ? isSelected
          : undefined,
      'data-menu-disabled': disabled ? 'true' : undefined,
      'data-menu-leading-icon':
        usesActionIconSlot && leadingIcon ? 'true' : undefined,
      tabIndex: disabled ? -1 : 0,
      onClick: activate,
    };
    const content = (
      <>
        {!disabled && (
          <StateLayer
            className={styles.stateLayer}
            colorName={
              resolvedVariant === 'vibrant' || isSelected
                ? 'on-tertiary-container'
                : 'on-secondary-container'
            }
            stateClassName="state-ripple-group-[menu-item]"
          />
        )}
        {usesActionIconSlot ? (
          <span
            aria-hidden="true"
            data-menu-leading-icon-slot
            style={resolvedLeadingIcon ? undefined : { display: 'none' }}
            className={classNames(
              styles.itemIcon,
              styles.leadingIcon,
              'z-10 relative',
            )}
          >
            {resolvedLeadingIcon && <Icon icon={resolvedLeadingIcon} />}
          </span>
        ) : resolvedLeadingIcon ? (
          <span
            aria-hidden="true"
            className={classNames(
              styles.itemIcon,
              styles.leadingIcon,
              'z-10 relative',
            )}
          >
            <Icon icon={resolvedLeadingIcon} />
          </span>
        ) : null}
        <span className={classNames(styles.itemLabel, 'z-10 relative')}>
          {children ?? label}
        </span>
        {trailingIcon && (
          <span
            aria-hidden="true"
            className={classNames(
              styles.itemIcon,
              styles.trailingIcon,
              'z-10 relative',
            )}
          >
            <Icon icon={trailingIcon} />
          </span>
        )}
      </>
    );

    return href ? (
      <a
        {...(sharedProps as React.AnchorHTMLAttributes<HTMLAnchorElement>)}
        href={disabled ? undefined : href}
      >
        {content}
      </a>
    ) : (
      <button
        {...(sharedProps as React.ButtonHTMLAttributes<HTMLButtonElement>)}
        type="button"
        disabled={disabled}
        value={value}
      >
        {content}
      </button>
    );
  },
);

MenuItem.displayName = 'MenuItem';

// packages/ui-svelte/src/lib/menu/MenuItem.svelte
<script lang="ts">
  import {
    getMenuItemRole,
    getMenuItemSelectionTransition,
    menuItemStyle,
    mergeClassNames,
    type MenuItemInterface,
  } from '@udixio/core';
  import { iCheck } from '@udixio/icons-rounded-400/check';
  import Icon from '../icon/Icon.svelte';
  import StateLayer from '../state-layer/StateLayer.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import { getMenuContext } from './menu-context.svelte';
  import type { SvelteMenuItemProps } from './menu-item.types';

  let {
    label,
    children,
    value,
    leadingIcon,
    trailingIcon,
    disabled = false,
    variant,
    selectionType,
    selected = $bindable(),
    defaultSelected = false,
    onSelectedChange,
    href,
    class: hostClass = '',
    classes,
    onclick,
    ...rest
  }: SvelteMenuItemProps = $props();

  const context = getMenuContext();
  const purpose = $derived(context?.purpose() ?? 'actions');
  const resolvedVariant = $derived(variant ?? context?.variant() ?? 'standard');
  const resolvedSelectionType = $derived(selectionType ?? (purpose === 'selection' ? 'single' : 'none'));
  const role = $derived(getMenuItemRole({ purpose, selectionType: resolvedSelectionType }));
  const usesActionIconSlot = $derived(purpose === 'actions' && resolvedSelectionType === 'none');
  const selectedState = createControllableState({
    value: () => selected,
    defaultValue: () => defaultSelected,
    onChange: (next) => onSelectedChange?.(next),
    assign: (next) => (selected = next),
    componentName: 'MenuItem',
    stateName: 'selected',
  });
  const isSelected = $derived(selectedState.current);
  const resolvedLeadingIcon = $derived(isSelected && resolvedSelectionType !== 'none' ? iCheck : leadingIcon);
  const styles = createStyle(menuItemStyle, () => ({
    label,
    value,
    leadingIcon,
    trailingIcon,
    disabled,
    variant: resolvedVariant,
    selectionType: resolvedSelectionType,
    selected,
    defaultSelected,
    onSelectedChange,
    isSelected,
    purpose,
    className: mergeClassNames<MenuItemInterface>('menuItem', classes, hostClass),
  }));

  const activate = (event: MouseEvent & { currentTarget: EventTarget & (HTMLButtonElement | HTMLAnchorElement) }) => {
    if (disabled) {
      event.preventDefault();
      return;
    }
    const transition = getMenuItemSelectionTransition({ disabled, selectionType: resolvedSelectionType, selected: isSelected });
    if (transition.nextSelected !== undefined) selectedState.set(transition.nextSelected);
    onclick?.(event);
  };
</script>

{#if href !== undefined}
  <a
    {...rest}
    class={styles.current['menuItem']}
    role={role}
    href={disabled ? undefined : href}
    aria-disabled={disabled || undefined}
    aria-selected={role === 'option' ? isSelected : undefined}
    aria-checked={role === 'menuitemcheckbox' || role === 'menuitemradio' ? isSelected : undefined}
    data-menu-disabled={disabled ? 'true' : undefined}
    data-menu-leading-icon={usesActionIconSlot && leadingIcon ? 'true' : undefined}
    tabindex={disabled ? -1 : 0}
    onclick={activate}
  >
    {@render content()}
  </a>
{:else}
  <button
    {...rest}
    type="button"
    class={styles.current['menuItem']}
    role={role}
    disabled={disabled}
    value={value}
    aria-selected={role === 'option' ? isSelected : undefined}
    aria-checked={role === 'menuitemcheckbox' || role === 'menuitemradio' ? isSelected : undefined}
    data-menu-disabled={disabled ? 'true' : undefined}
    data-menu-leading-icon={usesActionIconSlot && leadingIcon ? 'true' : undefined}
    tabindex={disabled ? -1 : 0}
    onclick={activate}
  >
    {@render content()}
  </button>
{/if}

{#snippet content()}
  {#if !disabled}
    <StateLayer
      class={styles.current['stateLayer']}
      colorName={resolvedVariant === 'vibrant' || isSelected ? 'on-tertiary-container' : 'on-secondary-container'}
      stateClassName="state-ripple-group-[menu-item]"
    />
  {/if}
  {#if usesActionIconSlot}
    <span
      aria-hidden="true"
      data-menu-leading-icon-slot
      style:display={resolvedLeadingIcon ? undefined : 'none'}
      class={`${styles.current['itemIcon']} ${styles.current['leadingIcon']} z-10 relative`}
    >
      {#if resolvedLeadingIcon}<Icon icon={resolvedLeadingIcon} />{/if}
    </span>
  {:else if resolvedLeadingIcon}
    <span aria-hidden="true" class={`${styles.current['itemIcon']} ${styles.current['leadingIcon']} z-10 relative`}>
      <Icon icon={resolvedLeadingIcon} />
    </span>
  {/if}
  <span class={`${styles.current['itemLabel']} z-10 relative`}>{#if children}{@render children()}{:else}{label}{/if}</span>
  {#if trailingIcon}
    <span aria-hidden="true" class={`${styles.current['itemIcon']} ${styles.current['trailingIcon']} z-10 relative`}><Icon icon={trailingIcon} /></span>
  {/if}
{/snippet}
