// packages/ui-angular/src/lib/menu/menu-group.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import {
  menuGroupStyle,
  type ClassNameComponent,
  type MenuGroupInterface,
  type MenuGroupProps,
} from '@udixio/core';
import { createStyle } from '../utils/create-style';
import { MENU_CONTEXT } from './menu-context';

/**
 * Groups related MenuItem children under an optional visible label.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Projects MenuItem children and inherits the parent Menu variant.
 * @a11y A visible `label` names the semantic group; an unlabeled group is presentational.
 * @limitations Group labels are plain text.
 */
@Component({
  selector: 'lib-menu-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'data-menu-group': '',
    '[class]': "styles()['menuGroup']",
    '[attr.role]': "label() ? 'group' : 'presentation'",
    '[attr.aria-labelledby]': 'label() ? labelId : null',
  },
  template: `
    @if (label()) {
      <div [id]="labelId" [class]="styles()['groupLabel']">
        {{ label() }}
      </div>
    }
    <ng-content />
  `,
})
export class MenuGroup {
  readonly variant = input<MenuGroupProps['variant']>();
  readonly label = input<string>();
  readonly className = input<string | ClassNameComponent<MenuGroupInterface>>();

  private static nextId = 0;
  protected readonly labelId = `menu-group-${MenuGroup.nextId++}`;
  private readonly context = inject(MENU_CONTEXT, { optional: true });
  private readonly resolvedVariant = computed(
    () => this.variant() ?? this.context?.variant() ?? 'standard',
  );
  protected readonly styles = createStyle(menuGroupStyle, () => ({
    variant: this.resolvedVariant(),
    label: this.label(),
    className: this.className(),
  }));
}

// packages/ui-svelte/src/lib/menu/MenuGroup.svelte
<script module lang="ts">
  let nextMenuGroupId = 0;
</script>

<script lang="ts">
  import { menuGroupStyle, mergeClassNames, type MenuGroupInterface } from '@udixio/core';
  import { createStyle } from '../utils/create-style.svelte';
  import { getMenuContext } from './menu-context.svelte';
  import type { SvelteMenuGroupProps } from './menu-group.types';

  let { children, variant, label, class: hostClass = '', classes, ...rest }: SvelteMenuGroupProps = $props();
  const context = getMenuContext();
  const resolvedVariant = $derived(variant ?? context?.variant() ?? 'standard');
  const labelId = `menu-group-${nextMenuGroupId++}`;
  const styles = createStyle(menuGroupStyle, () => ({
    variant: resolvedVariant,
    label,
    className: mergeClassNames<MenuGroupInterface>('menuGroup', classes, hostClass),
  }));
  $effect(() => context?.registerGroup());
</script>

<div
  {...rest}
  data-menu-group
  class={styles.current['menuGroup']}
  role={label ? 'group' : 'presentation'}
  aria-labelledby={label ? labelId : undefined}
>
  {#if label}<div id={labelId} class={styles.current['groupLabel']}>{label}</div>{/if}
  {@render children?.()}
</div>
