// packages/ui-react/src/lib/components/MenuHeadline.tsx
import { type ReactNode } from 'react';
import {
  type MenuHeadlineInterface,
  menuHeadlineStyle,
  type ReactProps,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';

export type ReactMenuHeadlineProps = ReactProps<MenuHeadlineInterface> & {
  children?: ReactNode;
};

export const useMenuHeadlineStyle = createUseStyle(menuHeadlineStyle);

export const MenuHeadline = ({
  label,
  children,
  variant,
  className,
  ...restProps
}: ReactMenuHeadlineProps) => {
  const styles = useMenuHeadlineStyle({ label, variant, className });
  return (
    <div
      className={styles.headline}
      role="group"
      aria-label={label}
      {...restProps}
    >
      {children ?? label}
    </div>
  );
};

// packages/ui-svelte/src/lib/menu/MenuHeadline.svelte
<script lang="ts">
  import { menuHeadlineStyle, mergeClassNames, type MenuHeadlineInterface } from '@udixio/core';
  import { createStyle } from '../utils/create-style.svelte';
  import { getMenuContext } from './menu-context.svelte';
  import type { SvelteMenuHeadlineProps } from './menu-headline.types';

  let { label, variant, class: hostClass = '', classes, ...rest }: SvelteMenuHeadlineProps = $props();
  const context = getMenuContext();
  const resolvedVariant = $derived(variant ?? context?.variant() ?? 'standard');
  const styles = createStyle(menuHeadlineStyle, () => ({
    label,
    variant: resolvedVariant,
    className: mergeClassNames<MenuHeadlineInterface>('headline', classes, hostClass),
  }));
</script>

<div {...rest} class={styles.current['headline']} role="presentation">{label}</div>
