// apps/doc/src/examples/react/checkbox-validation.tsx
import { useState, type FormEvent } from 'react';
import { Button, Checkbox } from '@udixio/ui-react';

export default function CheckboxValidationReact() {
  const [accepted, setAccepted] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const invalid = submitted && !accepted;

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmitted(true);
  };

  return (
    <form
      className="flex flex-col items-start gap-3"
      noValidate
      onSubmit={submit}
    >
      <div className="flex items-center gap-3">
        <Checkbox
          id="checkbox-react-terms"
          name="terms"
          value="accepted"
          checked={accepted}
          required
          invalid={invalid}
          aria-describedby="checkbox-react-terms-description"
          onCheckedChange={setAccepted}
        />
        <label htmlFor="checkbox-react-terms">Accept the terms</label>
      </div>
      <p
        id="checkbox-react-terms-description"
        className={invalid ? 'text-error' : 'text-on-surface-variant'}
        aria-live="polite"
      >
        {invalid ? 'You must accept the terms.' : 'Required to continue.'}
      </p>
      <Button type="submit" label="Continue" />
    </form>
  );
}

// apps/doc/src/examples/svelte/checkbox-validation.svelte
<script lang="ts">
  import { Button, Checkbox } from '@udixio/ui-svelte';

  let accepted = $state(false);
  let submitted = $state(false);
  const invalid = $derived(submitted && !accepted);

  const submit = (event: SubmitEvent) => {
    event.preventDefault();
    submitted = true;
  };
</script>

<form class="flex flex-col items-start gap-3" novalidate onsubmit={submit}>
  <div class="flex items-center gap-3">
    <Checkbox
      id="checkbox-svelte-terms"
      name="terms"
      value="accepted"
      bind:checked={accepted}
      required
      {invalid}
      aria-describedby="checkbox-svelte-terms-description"
    />
    <label for="checkbox-svelte-terms">Accept the terms</label>
  </div>
  <p
    id="checkbox-svelte-terms-description"
    class={invalid ? 'text-error' : 'text-on-surface-variant'}
    aria-live="polite"
  >
    {invalid ? 'You must accept the terms.' : 'Required to continue.'}
  </p>
  <Button type="submit" label="Continue" />
</form>
