// src/components/Switch.tsx
import React, { useRef, useState } from 'react';

import { Icon } from '../icon';
import { motion } from 'motion/react';
import { SwitchInterface } from '../interfaces/switch.interface';
import { switchStyle } from '../styles/switch.style';
import { MotionProps } from '../utils/component';

export const Switch = ({
  selected = false,
  className,
  activeIcon,
  disabled = false,
  inactiveIcon,
  onChange,
  onClick,
  onKeyDown,
  ref,
  ...restProps
}: MotionProps<SwitchInterface>) => {
  const [isSelected, setIsSelected] = useState(selected);

  const handleClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (disabled) return;
    toggleSwitchState();
    if (onClick) {
      onClick(event);
    }
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (disabled) return;
    if (event.key === ' ' || event.key === 'Enter') {
      event.preventDefault();
      toggleSwitchState();
    }
    if (onKeyDown) {
      onKeyDown(event);
    }
  };

  const toggleSwitchState = () => {
    setIsSelected(!isSelected);
    onChange?.(!isSelected);
  };
  const styles = switchStyle({
    className,
    isSelected,
    activeIcon,
    inactiveIcon,
    disabled,
    selected: isSelected,
    onChange,
  });

  const defaultRef = useRef<HTMLDivElement>(null);
  const resolvedRef: React.RefObject<any> | React.ForwardedRef<any> =
    ref || defaultRef;

  return (
    <motion.div
      role="switch"
      aria-checked={isSelected}
      tabIndex={disabled ? -1 : 0}
      onKeyDown={handleKeyDown}
      onClick={handleClick}
      ref={resolvedRef}
      className={styles.switch}
      {...restProps}
    >
      <input type="hidden" value={isSelected ? '1' : '0'} />
      <motion.div
        layout
        style={{ translate: isSelected ? '50%' : '-50%' }}
        transition={{
          type: 'spring',
          stiffness: 700,
          damping: 30,
        }}
        className={styles.handleContainer}
      >
        <div className={styles.handle}>
          {(isSelected ? activeIcon : inactiveIcon) && (
            <Icon
              className={styles.icon}
              icon={isSelected ? activeIcon! : inactiveIcon!}
            ></Icon>
          )}
        </div>
        <div className={styles.handleStateLayer} />
      </motion.div>
    </motion.div>
  );
};

// packages/ui-svelte/src/lib/switch/Switch.svelte
<script lang="ts">
  import {
    getSwitchChangeTransition,
    getSwitchHandleOffset,
    mergeClassNames,
    switchStyle,
    type SwitchInterface,
  } from '@udixio/core';
  import {
    createSwitchThumbController,
    type SwitchThumbController,
  } from '@udixio/core/dom';
  import Icon from '../icon/Icon.svelte';
  import StateLayer from '../state-layer/StateLayer.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteSwitchProps } from './switch.types';

  let {
    checked = $bindable(),
    defaultChecked = false,
    activeIcon,
    inactiveIcon,
    disabled = false,
    class: hostClass = '',
    classes,
    onCheckedChange,
    onclick,
    onkeydown,
    ...rest
  }: SvelteSwitchProps = $props();

  const checkedState = createControllableState({
    value: () => checked,
    defaultValue: () => defaultChecked,
    onChange: (next) => onCheckedChange?.(next),
    assign: (next) => (checked = next),
    componentName: 'Switch',
    stateName: 'checked',
  });
  const isChecked = $derived(checkedState.current);
  const resolvedIcon = $derived(isChecked ? activeIcon : inactiveIcon);
  const handleOffset = $derived(getSwitchHandleOffset(isChecked));

  const styles = createStyle(switchStyle, () => ({
    checked,
    defaultChecked,
    activeIcon,
    inactiveIcon,
    disabled,
    isChecked,
    className: mergeClassNames<SwitchInterface>('switch', classes, hostClass),
  }));

  let handleContainer: HTMLDivElement | undefined = $state();
  let controller: SwitchThumbController | undefined;
  let isFirstUpdate = true;

  $effect(() => {
    if (!handleContainer) return;
    const root = handleContainer;
    const created = createSwitchThumbController({ root });
    controller = created;
    isFirstUpdate = true;

    return () => {
      created.destroy();
      if (controller === created) controller = undefined;
    };
  });

  $effect(() => {
    const checkedValue = isChecked;
    if (!controller) return;
    // The initial translate is rendered directly; only later state changes
    // should ask the shared controller to animate.
    if (isFirstUpdate) {
      isFirstUpdate = false;
      return;
    }
    controller.update(
      getSwitchHandleOffset(!checkedValue),
      getSwitchHandleOffset(checkedValue),
    );
  });

  const handleToggle = () => {
    const transition = getSwitchChangeTransition({
      disabled,
      isChecked,
    });
    if (!transition.blocked) checkedState.set(transition.nextChecked);
  };

  const handleClick = (
    event: MouseEvent & { currentTarget: EventTarget & HTMLDivElement },
  ) => {
    handleToggle();
    onclick?.(event);
  };

  const handleKeyDown = (
    event: KeyboardEvent & { currentTarget: EventTarget & HTMLDivElement },
  ) => {
    if (event.key === ' ' || event.key === 'Enter') {
      event.preventDefault();
      handleToggle();
    }
    onkeydown?.(event);
  };
</script>

<div
  {...rest}
  role="switch"
  aria-checked={isChecked}
  aria-disabled={disabled || undefined}
  tabindex={disabled ? -1 : 0}
  class={styles.current['switch']}
  onclick={handleClick}
  onkeydown={handleKeyDown}
>
  <div
    bind:this={handleContainer}
    class={styles.current['handleContainer']}
    style:translate={`${handleOffset}px`}
  >
    <StateLayer
      class={styles.current['stateLayer']}
      colorName={isChecked ? 'primary' : 'on-surface'}
      stateClassName="state-ripple-group-[switch]"
    />
    <div class={styles.current['handle']}>
      {#if resolvedIcon}
        <Icon icon={resolvedIcon} class={styles.current['icon']} />
      {/if}
    </div>
  </div>
</div>
