// packages/ui-angular/src/lib/carousel/carousel.ts
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  contentChildren,
  input,
  output,
  signal,
  viewChild,
  type OnInit,
} from '@angular/core';
import {
  carouselStyle,
  customScrollStyle,
  type CarouselInterface,
  type CarouselMetrics,
  type CarouselProps,
  type ClassNameComponent,
} from '@udixio/core';
import {
  createCarouselController,
  createCustomScrollController,
  type CarouselController,
  type CustomScrollController,
} from '@udixio/core/dom';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { CarouselItem } from './carousel-item';

const clamp01 = (value: number) => Math.min(1, Math.max(0, value));

/**
 * Carousels show a collection of items that can be scrolled on and off the screen.
 *
 * @status beta
 * @category Layout
 * @devx Project `lib-carousel-item` children; use `index`/`indexChange` for controlled positioning, or `defaultIndex` to seed the initial position of an uncontrolled carousel.
 * @a11y The root is a `region` with `aria-roledescription="carousel"` (set `accessibleLabel` for a name); each slide is a `group` with `aria-roledescription="slide"` and an `"n / total"` label. Roving `tabindex` keeps a single slide in the tab order; Arrow/Home/End move the selection.
 * @limitations Responsive behavior on mobile is not supported. Only the `hero` variant is implemented; `center-aligned`, `multi-browse`, `un-contained`, and `full-screen` are reserved in the type for future Material 3 layout support and currently render as `hero`.
 */
@Component({
  selector: 'lib-carousel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      #root
      [class]="styles()['carousel']"
      role="region"
      [attr.aria-label]="accessibleLabel() || null"
      aria-roledescription="carousel"
      (keydown)="handleKeyDown($event)"
    >
      <div #scrollContainer [class]="scrollStyles()['customScroll']">
        <div
          #scrollContent
          [class]="scrollStyles()['track']"
          [style.width.px]="viewportWidth() || null"
        >
          <div
            #track
            [class]="styles()['track']"
            [style.gap.px]="gap()"
            style="will-change: transform"
          >
            <ng-content />
          </div>
        </div>

        @if (spacerWidth() > 0) {
          <div class="flex-none" [style.width.px]="spacerWidth()"></div>
        }
      </div>
    </div>
  `,
})
export class Carousel implements OnInit {
  readonly variant = input<CarouselProps['variant']>('hero');
  readonly gap = input(8);
  readonly scrollSensitivity = input(1.25);
  readonly outputRange = input<[number, number]>([42, 300]);
  readonly index = input<number>();
  readonly defaultIndex = input(0);
  /** Accessible name for the carousel region. */
  readonly accessibleLabel = input<string>();
  readonly className = input<string | ClassNameComponent<CarouselInterface>>();

  /** Emits an accepted centered-index transition. */
  readonly indexChange = output<number>();
  /** Receives live metrics to better control the carousel externally. */
  readonly metricsChange = output<CarouselMetrics>();

  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly scrollContainer =
    viewChild<ElementRef<HTMLElement>>('scrollContainer');
  private readonly scrollContent =
    viewChild<ElementRef<HTMLElement>>('scrollContent');
  private readonly track = viewChild<ElementRef<HTMLElement>>('track');
  private readonly items = contentChildren(CarouselItem, {
    read: ElementRef<HTMLElement>,
  });

  private readonly indexState = createControllableState({
    value: this.index,
    defaultValue: this.defaultIndex,
    onChange: (value) => this.indexChange.emit(value),
    componentName: 'Carousel',
    stateName: 'index',
  });
  protected readonly selectedIndex = this.indexState.value;

  /** Last index the user explicitly targeted; the keyboard-nav baseline. */
  private readonly focusedIndex = signal(0);
  protected readonly viewportWidth = signal(0);
  private readonly isDragging = signal(false);

  private carouselController?: CarouselController;
  private customScrollController?: CustomScrollController;
  private scrollVisible = 0;
  private lastMetrics: CarouselMetrics | null = null;
  private didMount = false;

  protected readonly styles = createStyle(carouselStyle, () => ({
    variant: this.variant(),
    gap: this.gap(),
    scrollSensitivity: this.scrollSensitivity(),
    outputRange: this.outputRange(),
    index: this.index(),
    defaultIndex: this.defaultIndex(),
    onIndexChange: () => undefined,
    onMetricsChange: () => undefined,
    selectedIndex: this.selectedIndex(),
    className: this.className(),
  }));

  protected readonly scrollStyles = createStyle(customScrollStyle, () => ({
    orientation: 'horizontal' as const,
    draggable: true,
    isDragging: this.isDragging(),
    scrollSize: this.computeScrollSize(),
    onScroll: () => undefined,
    scroll: undefined,
    setScroll: () => undefined,
    throttleDuration: 75,
    className: undefined,
  }));

  protected readonly spacerWidth = computed(() =>
    Math.max(0, this.computeScrollSize() - this.viewportWidth()),
  );

  constructor() {
    // Create both shared controllers once the DOM exists, and seed the
    // spring at the resolved initial index instead of an implicit progress
    // of 0 (a nonzero controlled/default index must render correctly from
    // the very first frame, not be corrected a tick later).
    afterRenderEffect((onCleanup) => {
      const root = this.root()?.nativeElement;
      const container = this.scrollContainer()?.nativeElement;
      const content = this.scrollContent()?.nativeElement;
      const track = this.track()?.nativeElement;
      if (!root || !container || !content || !track) return;

      let carouselController: CarouselController | undefined;

      const customScrollController = createCustomScrollController({
        container,
        content,
        orientation: () => 'horizontal',
        scrollSize: () => this.computeScrollSize(),
        draggable: () => true,
        onScroll: (metrics) => {
          this.scrollVisible = metrics.scrollVisible;
          if (metrics.scrollTotal > 0) {
            carouselController?.setProgress(metrics.scrollProgress ?? 0);
          }
        },
        onDraggingChange: (dragging) => this.isDragging.set(dragging),
        onDimensionsChange: (dimensions) =>
          this.viewportWidth.set(dimensions.width),
      });

      carouselController = createCarouselController({
        track,
        items: () => this.items().map((ref) => ref.nativeElement),
        viewport: () => this.scrollVisible || root.clientWidth || 0,
        gap: () => this.gap(),
        minItemWidth: () => this.outputRange()[0],
        maxItemWidth: () => this.outputRange()[1],
        onSelectedIndexChange: (i) => this.indexState.set(i),
      });

      this.customScrollController = customScrollController;
      this.carouselController = carouselController;

      // Read the desired initial position BEFORE notifyInitial(), which can
      // synchronously round-trip through onScroll -> setProgress(0) and
      // would otherwise clobber a nonzero resolved index. Re-assert it last
      // so this call always wins regardless of that side effect.
      const count = this.items().length;
      const initialProgress =
        count > 1
          ? clamp01(this.selectedIndex() / Math.max(1, count - 1))
          : 0;
      customScrollController.notifyInitial();
      carouselController.setProgress(initialProgress, { animate: false });

      onCleanup(() => {
        customScrollController.destroy();
        carouselController?.destroy();
        this.customScrollController = undefined;
        this.carouselController = undefined;
      });
    });

    // Re-apply the layout when item count, gap, or size range change.
    afterRenderEffect(() => {
      this.items();
      this.gap();
      this.outputRange();
      this.carouselController?.update();
    });

    // Stamp slide semantics (role/roledescription/label) and wire focus once
    // per item-list change; only the count is a dependency here, so this
    // never re-runs mid-scroll.
    afterRenderEffect((onCleanup) => {
      const elements = this.items().map((ref) => ref.nativeElement);
      const total = elements.length;
      const unlisten = elements.map((element, i) => {
        element.setAttribute('role', 'group');
        element.setAttribute('aria-roledescription', 'slide');
        element.setAttribute('aria-label', `${i + 1} / ${total}`);
        const onFocus = () => this.focusedIndex.set(i);
        element.addEventListener('focus', onFocus);
        return () => element.removeEventListener('focus', onFocus);
      });
      onCleanup(() => unlisten.forEach((off) => off()));
    });

    // Roving tabindex: only the selected slide is in the tab order.
    afterRenderEffect(() => {
      const elements = this.items().map((ref) => ref.nativeElement);
      const selected = this.selectedIndex();
      elements.forEach((element, i) => {
        element.tabIndex = i === selected ? 0 : -1;
      });
    });

    // Re-center only when the controlled `index` input changes after mount
    // (the initial position is already seeded above). Reading the resolved
    // `selectedIndex` here instead of the raw input would fight free
    // scrolling, since scroll updates it continuously.
    afterRenderEffect(() => {
      const idx = this.index();
      const count = this.items().length;
      if (count === 0) return;
      if (!this.didMount) {
        this.didMount = true;
        return;
      }
      if (typeof idx === 'number') {
        this.centerOnIndex(idx);
      }
    });

    afterRenderEffect(() => {
      const total = this.items().length;
      const root = this.root()?.nativeElement;
      if (total <= 0 || !root) return;

      const viewportWidth = root.clientWidth || 0;
      const gap = this.gap();
      const itemMaxWidth = this.outputRange()[1];
      const scrollProgress = this.carouselController?.getProgress() ?? 0;
      const visibleApprox = (viewportWidth + gap) / (itemMaxWidth + gap);
      const visibleFull = Math.max(1, Math.floor(visibleApprox));
      const stepHalf = Math.max(1, Math.round(visibleFull * (2 / 3)));
      const selectedIndexSafe = Math.min(
        Math.max(0, this.selectedIndex()),
        Math.max(0, total - 1),
      );

      const metrics: CarouselMetrics = {
        total,
        selectedIndex: selectedIndexSafe,
        visibleApprox,
        visibleFull,
        stepHalf,
        canPrev: selectedIndexSafe > 0,
        canNext: selectedIndexSafe < total - 1,
        scrollProgress,
        viewportWidth,
        itemMaxWidth,
        gap,
      };

      const last = this.lastMetrics;
      const changed =
        !last ||
        (Object.keys(metrics) as (keyof CarouselMetrics)[]).some(
          (key) => metrics[key] !== last[key],
        );
      if (changed) {
        this.lastMetrics = metrics;
        this.metricsChange.emit(metrics);
      }
    });
  }

  ngOnInit(): void {
    this.indexState.initialize();
  }

  private computeScrollSize(): number {
    let maxWidth = this.outputRange()[1];
    const visible = this.viewportWidth();
    if (visible > 0 && maxWidth > visible) {
      maxWidth = visible;
    }
    const result =
      ((maxWidth + this.gap()) * this.items().length) /
      this.scrollSensitivity();
    return result || 400;
  }

  private centerOnIndex(idx: number): void {
    const count = this.items().length;
    if (count === 0) return;
    this.focusedIndex.set(idx);
    this.customScrollController?.scrollTo({
      progress: clamp01(idx / Math.max(1, count - 1)),
      orientation: 'horizontal',
    });
  }

  protected handleKeyDown(event: KeyboardEvent): void {
    const count = this.items().length;
    if (count === 0) return;
    const idx = this.focusedIndex();
    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault();
        this.centerOnIndex(Math.max(0, idx - 1));
        break;
      case 'ArrowRight':
        event.preventDefault();
        this.centerOnIndex(Math.min(count - 1, idx + 1));
        break;
      case 'Home':
        event.preventDefault();
        this.centerOnIndex(0);
        break;
      case 'End':
        event.preventDefault();
        this.centerOnIndex(count - 1);
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        this.centerOnIndex(idx);
        break;
    }
  }
}

// packages/ui-react/src/lib/components/Carousel.tsx
import React, {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import {
  carouselStyle,
  type CarouselInterface,
  type CarouselItemInterface,
  type ReactProps,
} from '@udixio/core';
import {
  createCarouselController,
  type CarouselController,
} from '@udixio/core/dom';

import { CustomScroll } from '../effects';
import { createUseStyle } from '../utils/create-use-style';
import { CarouselItem, normalize } from './CarouselItem';

export type ReactCarouselProps = ReactProps<CarouselInterface> & {
  children?: ReactNode;
};

export const useCarouselStyle = createUseStyle(carouselStyle);

/**
 * Carousels show a collection of items that can be scrolled on and off the screen
 *
 * @status beta
 * @category Layout
 * @devx
 * - Only `CarouselItem` children are rendered; other children are ignored.
 * - Use `index` for controlled positioning; otherwise relies on internal scroll state.
 * @a11y
 * - The root is a `region` with `aria-roledescription="carousel"`; provide an
 *   accessible name via `aria-label` on the component.
 * - Each item is a `group` with `aria-roledescription="slide"` and an
 *   `aria-label` of the form `"n / total"`.
 * - Roving `tabIndex` keeps a single item in the tab order; Arrow/Home/End move
 *   the selection and center the focused slide.
 * @limitations
 * - Responsive behavior on mobile is not supported.
 * - Only the `hero` variant is implemented. `center-aligned`, `multi-browse`,
 *   `un-contained`, and `full-screen` are reserved in the type for future
 *   Material 3 layout support and currently render as `hero`.
 */
export const Carousel = ({
  variant = 'hero',
  className,
  children,
  ref: optionalRef,
  outputRange = [42, 300],
  gap = 8,
  onChange,
  onMetricsChange,
  index,
  scrollSensitivity = 1.25,
  ...restProps
}: ReactCarouselProps) => {
  const defaultRef = useRef<HTMLDivElement>(null);
  const ref = optionalRef || defaultRef;

  const items = React.Children.toArray(children).filter(
    (child) => React.isValidElement(child) && child.type === CarouselItem,
  );

  const trackRef = useRef<HTMLDivElement>(null);

  // Latest scroll metrics reported by CustomScroll. Kept in a ref so 60fps
  // scrolling never triggers a React re-render.
  const getScrollState = useRef({
    scrollProgress: 0,
    scrollTotal: 0,
    scrollVisible: 0,
    scroll: 0,
  });

  const itemRefs = useRef<React.RefObject<HTMLDivElement | null>[]>([]).current;
  const [selectedItem, setSelectedItem] = useState(0);

  // The controller reads these through accessors, so it always sees the current
  // prop values without being recreated when they change.
  const gapRef = useRef(gap);
  gapRef.current = gap;
  const outputRangeRef = useRef(outputRange);
  outputRangeRef.current = outputRange;

  const controllerRef = useRef<CarouselController | null>(null);

  const styles = useCarouselStyle({
    variant,
    gap,
    scrollSensitivity,
    outputRange,
    index,
    onChange,
    onMetricsChange,
    selectedIndex: selectedItem,
    className,
  });

  if (itemRefs.length !== items.length) {
    itemRefs.length = 0; // reset
    items.forEach((_, i) => {
      itemRefs[i] = React.createRef<HTMLDivElement>();
    });
  }

  // The spring and the DOM writes live in @udixio/core/dom so every framework
  // shares one implementation; React only owns the lifecycle wiring.
  useEffect(() => {
    const root = ref.current;
    const track = trackRef.current;
    if (!root || !track) return;

    const controller = createCarouselController({
      track,
      items: () => itemRefs.map((itemRef) => itemRef.current),
      viewport: () =>
        getScrollState.current.scrollVisible || root.clientWidth || 0,
      gap: () => gapRef.current,
      minItemWidth: () => outputRangeRef.current[0],
      maxItemWidth: () => outputRangeRef.current[1],
      onSelectedIndexChange: setSelectedItem,
    });

    controllerRef.current = controller;
    controller.update();

    return () => {
      controller.destroy();
      controllerRef.current = null;
    };
  }, [ref]);

  useLayoutEffect(() => {
    controllerRef.current?.update();
  }, [items.length, gap, outputRange]);


  useEffect(() => {
    if (onChange) onChange(selectedItem);
  }, [selectedItem, onChange]);

  // accessibility and interaction states
  const [focusedIndex, setFocusedIndex] = useState(0);

  useEffect(() => {
    setFocusedIndex(selectedItem);
  }, [selectedItem]);


  const centerOnIndex = (idx: number, opts: { animate?: boolean } = {}) => {
    if (!items.length) return 0;
    const itemRef = itemRefs[idx];
    if (!itemRef || !itemRef.current || !trackRef.current) return 0;

    const itemScrollXCenter = normalize(
      idx / Math.max(1, items.length - 1),
      [0, 1],
      [0, 1],
    );

    setFocusedIndex(idx);

    const track = trackRef.current as HTMLElement;
    track.dispatchEvent(
      new CustomEvent('udx:customScroll:set', {
        bubbles: true,
        detail: {
          progress: itemScrollXCenter,
          orientation: 'horizontal',
          animate: opts.animate !== false,
        },
      }),
    );

    return itemScrollXCenter;
  };

  useEffect(() => {
    if (typeof index === 'number' && items.length > 0 && index !== selectedItem) {
      centerOnIndex(index);
    }
  }, [index, items.length]);

  const handleScroll = (args: {
    scrollProgress: number;
    scrollTotal: number;
    scrollVisible: number;
    scroll: number;
  }) => {
    getScrollState.current = args;

    if (args.scrollTotal > 0) {
      controllerRef.current?.setProgress(args.scrollProgress ?? 0);
    }
  };

  // Keep latest onMetricsChange in a ref to avoid effect dependency loops
  const onMetricsChangeRef = useRef(onMetricsChange);
  useEffect(() => {
    onMetricsChangeRef.current = onMetricsChange;
  }, [onMetricsChange]);

  const lastMetricsRef = useRef<any>(null);

  useEffect(() => {
    const cb = onMetricsChangeRef.current;
    if (!cb || !ref?.current || items.length <= 0) return;
    const total = items.length;
    const viewportWidth = (ref.current as any).clientWidth || 0;
    const itemMaxWidth = outputRange[1];
    const sProgress = controllerRef.current?.getProgress() ?? 0;
    const visibleApprox = (viewportWidth + gap) / (itemMaxWidth + gap);
    const visibleFull = Math.max(1, Math.floor(visibleApprox));
    const stepHalf = Math.max(1, Math.round(visibleFull * (2 / 3)));
    const selectedIndexSafe = Math.min(Math.max(0, selectedItem), Math.max(0, total - 1));

    const metrics = {
      total,
      selectedIndex: selectedIndexSafe,
      visibleApprox,
      visibleFull,
      stepHalf,
      canPrev: selectedIndexSafe > 0,
      canNext: selectedIndexSafe < total - 1,
      scrollProgress: sProgress,
      viewportWidth,
      itemMaxWidth,
      gap,
    };

    const last = lastMetricsRef.current;
    let changed = !last;
    if (!changed) {
      for (const k in metrics) {
        if ((metrics as any)[k] !== last[k]) {
          changed = true;
          break;
        }
      }
    }

    if (changed) {
      lastMetricsRef.current = metrics;
      cb(metrics);
    }
  }, [ref, items.length, selectedItem, gap, outputRange]);

  const [scrollSize, setScrollSize] = useState(0);
  useLayoutEffect(() => {
    let maxWidth = outputRange[1];
    const scrollState = getScrollState.current;
    if (scrollState && maxWidth > scrollState.scrollVisible && scrollState.scrollVisible > 0) {
      maxWidth = scrollState.scrollVisible;
    }
    const result = ((maxWidth + gap) * items.length) / scrollSensitivity;
    setScrollSize(result || 400); // Fail-safe
  }, [ref, items.length, gap, outputRange, scrollSensitivity]);


  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (!items.length) return;
    const idx = focusedIndex ?? selectedItem;
    switch (e.key) {
      case 'ArrowLeft':
        e.preventDefault();
        centerOnIndex(Math.max(0, idx - 1));
        break;
      case 'ArrowRight':
        e.preventDefault();
        centerOnIndex(Math.min(items.length - 1, idx + 1));
        break;
      case 'Home':
        e.preventDefault();
        centerOnIndex(0);
        break;
      case 'End':
        e.preventDefault();
        centerOnIndex(items.length - 1);
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        centerOnIndex(idx);
        break;
    }
  };

  useEffect(() => {
    const root = ref.current as any;
    if (!root) return;
    const handler = (ev: Event) => {
      const detail = (ev as CustomEvent).detail;
      if (detail && typeof detail.index === 'number') {
        centerOnIndex(detail.index);
      }
    };
    root.addEventListener('udx:carousel:centerIndex', handler);
    return () => {
      root.removeEventListener('udx:carousel:centerIndex', handler);
    };
  }, [ref, items.length]);

  const renderItems = items.map((child, idx) =>
    React.cloneElement(
      child as React.ReactElement<ReactProps<CarouselItemInterface>>,
      {
        outputRange,
        ref: itemRefs[idx],
        key: idx,
        role: 'group',
        'aria-roledescription': 'slide',
        'aria-label': `${idx + 1} / ${items.length}`,
        tabIndex: selectedItem === idx ? 0 : -1,
        onFocus: () => setFocusedIndex(idx),
      } as ReactProps<CarouselItemInterface> & Record<string, unknown>,
    ),
  );

  return (
    <div
      className={styles.carousel}
      ref={ref}
      role="region"
      aria-roledescription="carousel"
      onKeyDown={handleKeyDown}
      {...restProps}
    >
      <CustomScroll
        draggable
        orientation={'horizontal'}
        onScroll={handleScroll}
        scrollSize={scrollSize}
      >
        <div
          className={styles.track}
          ref={trackRef}
          style={{
            gap: `${gap}px`,
            willChange: 'transform',
          }}
        >
          {renderItems}
        </div>
      </CustomScroll>
    </div>
  );
};
