// packages/ui-svelte/src/lib/chips/Chips.svelte
<script lang="ts">
  import { chipsStyle, mergeClassNames, type ChipItem, type ChipsInterface } from '@udixio/core';
  import Divider from '../divider/Divider.svelte';
  import Chip from '../chip/Chip.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteChipsProps } from './chips.types';

  let {
    variant = 'input',
    label = 'Chips',
    items = $bindable<ChipItem[]>([]),
    onItemsChange,
    scrollable = true,
    draggable = false,
    class: hostClass = '',
    classes,
    ...rest
  }: SvelteChipsProps = $props();

  let root: HTMLDivElement | undefined = $state();
  let focused = $state(false);
  let editingId = $state<string | undefined>();
  let creating = $state(false);
  let nextId = 0;
  const ids = new WeakMap<object, string>();

  const list = $derived(items ?? []);
  const styles = createStyle(chipsStyle, () => ({
    variant,
    label,
    items: list,
    onItemsChange,
    scrollable,
    draggable,
    className: mergeClassNames<ChipsInterface>('chips', classes, hostClass),
  }));

  const itemId = (item: ChipItem) => {
    if (item.id) return item.id;
    let id = ids.get(item);
    if (!id) {
      id = `chip-${nextId++}`;
      ids.set(item, id);
    }
    return id;
  };

  const updateItems = (next: ChipItem[]) => {
    items = next;
    onItemsChange?.(next);
  };

  const removeAt = (index: number) => updateItems(list.filter((_, itemIndex) => itemIndex !== index));

  const chipElements = () =>
    Array.from(root?.querySelectorAll<HTMLElement>('[data-chip-item]') ?? []);

  const focusIndex = (index: number) => {
    const elements = chipElements();
    if (!elements.length) return;
    const normalized = (index + elements.length) % elements.length;
    elements[normalized]?.focus();
    elements[normalized]?.scrollIntoView?.({ block: 'nearest', inline: 'center' });
  };

  const handleKeydown = (event: KeyboardEvent) => {
    if (variant !== 'input' || !focused) return;
    const elements = chipElements();
    const active = document.activeElement as HTMLElement | null;
    const currentIndex = elements.indexOf(active as HTMLElement);
    if (event.key === 'ArrowLeft' && elements.length) {
      event.preventDefault();
      focusIndex(currentIndex > 0 ? currentIndex - 1 : elements.length - 1);
    } else if (event.key === 'ArrowRight' && elements.length) {
      event.preventDefault();
      focusIndex(currentIndex >= 0 ? (currentIndex + 1) % elements.length : 0);
    } else if (event.key === 'Home' && elements.length) {
      event.preventDefault();
      focusIndex(0);
    } else if (event.key === 'End' && elements.length) {
      event.preventDefault();
      focusIndex(elements.length - 1);
    } else if (event.key === 'Backspace' && currentIndex < 0 && elements.length) {
      event.preventDefault();
      focusIndex(elements.length - 1);
    }
  };

  const createItem = (value: string) => {
    const normalized = value.replace(/(&nbsp;)+/g, ' ').trim();
    if (!normalized || creating) return;
    creating = true;
    const newItem: ChipItem = { label: normalized };
    updateItems([...list, newItem]);
    requestAnimationFrame(() => {
      creating = false;
      editingId = itemId(newItem);
      requestAnimationFrame(() => focusIndex(list.length - 1));
    });
  };
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  {...rest}
  bind:this={root}
  role="list"
  aria-label={label}
  class={styles.current['chips']}
  tabindex={variant === 'input' ? 0 : undefined}
  onfocus={(event) => { if (event.target === event.currentTarget) focused = true; }}
  onblur={(event) => { if (!(event.relatedTarget instanceof Node && root?.contains(event.relatedTarget))) { focused = false; editingId = undefined; } }}
  onkeydown={handleKeydown}
>
  {#each list as item, index (itemId(item))}
    {@const id = itemId(item)}
    <span data-chip-item role="listitem" class="contents">
      <Chip
        label={item.label}
        icon={item.icon}
        variant={item.variant}
        disabled={item.disabled}
        href={item.href}
        selected={item.selected}
        defaultSelected={item.selected}
        onSelectedChange={item.selected === undefined ? undefined : (selected) => updateItems(list.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, selected } : candidate))}
        onRemove={variant === 'input' || item.removable ? () => removeAt(index) : undefined}
        editable={variant === 'input'}
        editing={editingId === id}
        draggable={draggable}
        onfocus={() => { focused = true; editingId = id; }}
        onblur={() => { if (editingId === id) editingId = undefined; }}
        onEditCommit={(nextLabel) => updateItems(list.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, label: nextLabel } : candidate))}
        onChange={() => { if (index === list.length - 1) root?.scrollTo({ left: root.scrollWidth, behavior: 'smooth' }); }}
      />
    </span>
  {/each}

  {#if focused && variant === 'input'}
    <Divider orientation="vertical" class="border-outline animate-[var(--animate-blink)]" style="--animate-blink: blink 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" />
    <style>
      @keyframes blink { 0%, 50% { opacity: 1; } 50.01%, 100% { opacity: 0; } }
    </style>
  {/if}

  {#if variant === 'input' && (focused || list.length === 0)}
    <Chip
      label=""
      class="opacity-0"
      editable
      editing
      draggable={draggable}
      onfocus={() => { focused = true; }}
      onblur={() => { focused = false; }}
      onChange={createItem}
      onEditCommit={() => undefined}
    />
  {/if}
</div>

// packages/ui-react/src/lib/components/Chips.tsx
import React, { useEffect, useRef, useState } from 'react';
import { ReactProps } from '../utils';
import { ChipItem, ChipsInterface } from '../interfaces';
import { useChipsStyle } from '../styles';
import { Chip } from './Chip';
import { Divider } from './Divider';
import { v4 } from 'uuid';

export const Chips = ({
  variant = 'input',
  className,
  scrollable = true,
  draggable = false,
  items,
  onItemsChange,
}: ReactProps<ChipsInterface>) => {
  const list = items ?? [];

  const ref = React.useRef<HTMLDivElement>(null);

  const [isFocused, setIsFocused] = React.useState<boolean>(false);

  // Internal stable ids per item object (since ChipItem no longer exposes id)
  const idMapRef = React.useRef<WeakMap<ChipItem, string>>(new WeakMap());
  const getInternalId = React.useCallback((it: ChipItem) => {
    const map = idMapRef.current;
    let id = map.get(it);
    if (!id) {
      id = v4();
      map.set(it, id);
    }
    return id;
  }, []);

  React.useEffect(() => {
    if (isFocused) {
      if (variant == 'input') {
        ghostChipRef.current?.focus();
      } else {
        ref.current?.focus();
      }
    }
  }, [isFocused]);

  const chipRefs = React.useRef<(HTMLElement | null)[]>([]);

  const updateItems = React.useCallback(
    (updater: (prev: ChipItem[]) => ChipItem[]) => {
      onItemsChange?.(updater(list));
    },
    [onItemsChange, list],
  );

  const removeAt = React.useCallback(
    (index: number) => {
      updateItems((prev) => prev.filter((_, i) => i !== index));
    },
    [updateItems],
  );

  const styles = useChipsStyle({
    scrollable,
    className,
    variant,
  });

  const createAndStartEdit = React.useCallback(
    (seedLabel = '') => {
      if (variant !== 'input') return;

      const newItem: ChipItem = {
        label: seedLabel,
      } as ChipItem;

      // Generate internal ID for the new item
      const newId = getInternalId(newItem);

      // Ask parent to add as well
      const next = [...list, newItem];
      onItemsChange?.(next);

      requestAnimationFrame(() => {
        setSelectedChip(newId);
      });
    },
    [variant, onItemsChange, list, getInternalId],
  );

  const [selectedChip, setSelectedChip] = useState<string | null>(null);

  useEffect(() => {
    if (selectedChip) {
      const index = list.findIndex(
        (item) => getInternalId(item) === selectedChip,
      );
      if (index !== -1) {
        const el = chipRefs.current[index] as any;
        el?.focus?.();

        const chipsEl = ref.current!;
        const scrollLeft =
          el.offsetLeft + el.offsetWidth / 2 - chipsEl.offsetWidth / 2;
        chipsEl.scrollTo({ left: scrollLeft, behavior: 'smooth' });
      }
    }
  }, [selectedChip, list, getInternalId]);

  // MODE ITEMS (source de vérité locale ou contrôlée)

  const ghostChipRef = useRef<HTMLDivElement>(null);

  return (
    <div
      ref={ref}
      role="list"
      aria-label="Chips"
      className={styles.chips}
      tabIndex={variant === 'input' ? 0 : undefined}
      onFocus={(e) => {
        if (e.target === e.currentTarget) {
          setIsFocused(true);
        }
      }}
      onBlur={() => {
        setIsFocused(false);
      }}
      onKeyDown={(e) => {
        if (variant !== 'input') return;

        const key = e.key;
        const target = e.target as HTMLElement;
        const isContainerFocused = target === e.currentTarget;

        // If currently editing a chip, let the chip handle keys
        if (!isFocused) return;

        // Determine focused chip index if any
        const activeEl = document.activeElement as HTMLElement | null;
        const focusedIndex = chipRefs.current.findIndex(
          (el) => el === activeEl,
        );

        if (key === 'ArrowLeft') {
          e.preventDefault();
          const nextIdx = focusedIndex > 0 ? focusedIndex - 1 : list.length - 1;
          const elId = getInternalId(list[nextIdx]);
          setSelectedChip(elId);
          return;
        }
        if (key === 'ArrowRight') {
          e.preventDefault();
          const nextIdx =
            focusedIndex >= 0
              ? (focusedIndex + 1) % Math.max(1, list.length)
              : 0;
          const elId = getInternalId(list[nextIdx]);
          setSelectedChip(elId);
          return;
        }
        if (key === 'Home') {
          e.preventDefault();
          const elId = getInternalId(list[0]);
          setSelectedChip(elId);
          return;
        }
        if (key === 'End') {
          e.preventDefault();
          const elId = getInternalId(list[list.length - 1]);
          setSelectedChip(elId);
          return;
        }
        if (isContainerFocused) {
          if (key === 'Backspace') {
            e.preventDefault();
            // Focus last chip if any
            if (list.length > 0) {
              const el = chipRefs.current[list.length - 1] as any;
              el?.focus?.();
            }
            return;
          }
        }
      }}
    >
      {list.map((item, index) => {
        const internalId = getInternalId(item);
        const isInputVariant = variant === 'input';
        const editProps = isInputVariant
          ? {
              editable: true,
              editing: selectedChip === internalId,
              onEditCommit: (next: string | undefined) => {
                setIsFocused(true);
                updateItems((prev) =>
                  prev.map((it, i) =>
                    i === index ? { ...it, label: next as any } : it,
                  ),
                );
              },
              onEditCancel: () => {
                setIsFocused(true);
              },
              onChange: (next: ChipItem[]) => {
                if (chipRefs.current.length == index + 1) {
                  const el = ref.current!;
                  requestAnimationFrame(() => {
                    el.scrollTo({ left: el.scrollWidth, behavior: 'smooth' });
                  });
                }
              },
            }
          : {};

        return (
          <Chip
            key={internalId}
            ref={(el: any) => (chipRefs.current[index] = el)}
            label={item.label ?? ''}
            icon={item.icon}
            activated={item.activated}
            disabled={item.disabled}
            variant={item.variant}
            href={item.href}
            draggable={draggable}
            {...editProps}
            onToggle={
              item.activated === undefined
                ? undefined
                : (next) =>
                    updateItems((prev) =>
                      prev.map((it, i) =>
                        i === index ? { ...it, activated: next } : it,
                      ),
                    )
            }
            onBlur={() => {
              if (selectedChip === internalId) {
                setSelectedChip(null);
              }
            }}
            onRemove={
              isInputVariant
                ? () => {
                    setIsFocused(true);
                    removeAt(index);
                  }
                : undefined
            }
          />
        );
      })}
      {isFocused && (
        <>
          <Divider
            orientation="vertical"
            className="animate-[var(--animate-blink)] border-outline"
            style={
              {
                '--animate-blink':
                  'blink 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
              } as React.CSSProperties
            }
          />

          <style>
            {`
        @keyframes blink {
          0%, 50% { opacity: 1; }
          50.01%, 100% { opacity: 0; }
        }
      `}
          </style>
        </>
      )}
      {isFocused && variant === 'input' && (
        <Chip
          ref={ghostChipRef}
          className="opacity-0"
          draggable={draggable}
          editable={true}
          onChange={(f) => {
            createAndStartEdit(f);
          }}
          onBlur={() => {
            setIsFocused(false);
          }}
          onFocus={(e) => {
            setIsFocused(true);
            e.stopPropagation();
          }}
          editing={true}
        >
          &nbsp;
        </Chip>
      )}
    </div>
  );
};
