// packages/ui-svelte/src/lib/chip/Chip.svelte
<script lang="ts">
  import {
    chipStyle,
    classNames,
    getChipSelectionTransition,
    mergeClassNames,
    type ChipInterface,
  } from '@udixio/core';
  import { iCheck } from '@udixio/icons-rounded-400/check';
  import { iClose } from '@udixio/icons-rounded-400/close';
  import Icon from '../icon/Icon.svelte';
  import StateLayer from '../state-layer/StateLayer.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteChipProps } from './chip.types';

  let {
    label,
    children,
    variant = 'outlined',
    disabled = false,
    icon,
    href,
    selected = $bindable(),
    defaultSelected,
    onSelectedChange,
    onRemove,
    draggable = false,
    editable = false,
    editing,
    onEditStart,
    onEditCommit,
    onEditCancel,
    onChange,
    transition,
    class: hostClass = '',
    style: hostStyle,
    classes,
    onclick,
    onfocus,
    onblur,
    onkeydown,
    ondblclick,
    ondragstart,
    ondragend,
    ...rest
  }: SvelteChipProps = $props();

  let rootElement: HTMLButtonElement | HTMLAnchorElement | undefined = $state();
  let labelElement: HTMLSpanElement | undefined = $state();
  let isFocused = $state(false);
  let isDragging = $state(false);
  let internalEditing = $state(false);
  let editValue = $state('');
  let editTimer: ReturnType<typeof setTimeout> | undefined;

  const isSelectable = $derived(
    selected !== undefined || defaultSelected !== undefined || onSelectedChange !== undefined,
  );
  const isInteractive = $derived(
    isSelectable || !!onRemove || !!onclick || !!href || editable,
  );
  const isEditing = $derived(!!editable && (editing ?? internalEditing));
  const hasTrailingIcon = $derived(!!onRemove && !isEditing);
  const resolvedDuration = $derived(transition?.duration ?? 0.3);

  const selectedState = createControllableState({
    value: () => selected,
    defaultValue: () => defaultSelected ?? false,
    onChange: (next) => onSelectedChange?.(next),
    assign: (next) => (selected = next),
    componentName: 'Chip',
    stateName: 'selected',
  });
  const isSelected = $derived(selectedState.current);
  const resolvedIcon = $derived(isSelected ? iCheck : icon);

  const styles = createStyle(chipStyle, () => ({
    transition,
    label,
    variant,
    disabled,
    icon: resolvedIcon,
    selected,
    defaultSelected,
    onSelectedChange,
    onRemove,
    href,
    draggable,
    editable,
    editing,
    onEditStart,
    onEditCommit,
    onEditCancel,
    onChange,
    isSelected,
    isFocused,
    isInteractive,
    isDragging,
    isEditing,
    trailingIcon: hasTrailingIcon,
    className: mergeClassNames<ChipInterface>('chip', classes, hostClass),
  }));

  const clearEditTimer = () => {
    if (editTimer) clearTimeout(editTimer);
    editTimer = undefined;
  };

  const enterEditing = (event?: Event, delayed = false) => {
    if (disabled || !editable || isEditing) return;
    event?.preventDefault();
    editValue = label ?? '';
    const activate = () => {
      if (disabled || (draggable && isDragging)) return;
      if (editing === undefined) internalEditing = true;
      onEditStart?.();
      requestAnimationFrame(() => {
        labelElement?.focus();
        const selection = window.getSelection();
        if (!selection || !labelElement) return;
        const range = document.createRange();
        range.selectNodeContents(labelElement);
        range.collapse(false);
        selection.removeAllRanges();
        selection.addRange(range);
      });
    };
    if (delayed) {
      clearEditTimer();
      editTimer = setTimeout(activate, 1000);
    } else activate();
  };

  const commitEditing = () => {
    const next = editValue.trim();
    if (editing === undefined) internalEditing = false;
    if (!next) {
      onRemove?.();
      return;
    }
    onEditCommit?.(next);
  };

  const handleClick = (event: MouseEvent & { currentTarget: EventTarget & (HTMLButtonElement | HTMLAnchorElement) }) => {
    if (disabled) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    if (isSelectable) {
      const transitionResult = getChipSelectionTransition({ disabled, selected: isSelected });
      if (transitionResult.nextSelected !== undefined) selectedState.set(transitionResult.nextSelected);
    }
    if (!isEditing) onclick?.(event);
  };

  const handleFocus = (event: FocusEvent) => {
    if (isInteractive) {
      isFocused = true;
      if (editable && !isEditing) enterEditing(undefined, true);
    }
    onfocus?.(event);
  };

  const handleBlur = (event: FocusEvent) => {
    const related = event.relatedTarget;
    if (related instanceof Node && rootElement?.contains(related)) return;
    clearEditTimer();
    isFocused = false;
    if (isEditing) commitEditing();
    onblur?.(event);
  };

  const handleKeydown = (event: KeyboardEvent) => {
    if (disabled) {
      onkeydown?.(event);
      return;
    }
    if (isEditing) {
      if (event.key === 'Enter') {
        event.preventDefault();
        commitEditing();
      } else if (event.key === 'Escape') {
        event.preventDefault();
        if (editing === undefined) internalEditing = false;
        onEditCancel?.();
      } else if (onRemove && !editValue.trim() && ['Backspace', 'Delete', 'Del'].includes(event.key)) {
        event.preventDefault();
        event.stopPropagation();
        onRemove();
      }
      onkeydown?.(event);
      return;
    }
    if (isFocused && editable && !isSelectable && ['F2', 'Enter'].includes(event.key)) {
      enterEditing(event);
      onkeydown?.(event);
      return;
    }
    if (isFocused && isSelectable && ['Enter', ' ', 'Spacebar'].includes(event.key)) {
      event.preventDefault();
      const transitionResult = getChipSelectionTransition({ disabled, selected: isSelected });
      if (transitionResult.nextSelected !== undefined) selectedState.set(transitionResult.nextSelected);
    }
    if (isFocused && onRemove && ['Backspace', 'Delete', 'Del'].includes(event.key)) {
      event.preventDefault();
      event.stopPropagation();
      onRemove();
    }
    onkeydown?.(event);
  };

  const handleInput = () => {
    if (!isEditing || !labelElement) return;
    editValue = labelElement.innerText;
    onChange?.(editValue);
  };

  const handleDoubleClick = (event: MouseEvent) => {
    if (!disabled && editable && !isEditing) enterEditing(event);
    ondblclick?.(event);
  };

  const handleDragStart = (event: DragEvent) => {
    if (!disabled && draggable) isDragging = true;
    ondragstart?.(event);
  };

  const handleDragEnd = (event: DragEvent) => {
    if (draggable) isDragging = false;
    ondragend?.(event);
  };

  $effect(() => () => clearEditTimer());
</script>

{#if href !== undefined}
  <a
    {...rest}
    bind:this={rootElement}
    class={styles.current['chip']}
    style={`${hostStyle ?? ''}${hostStyle && !hostStyle.endsWith(';') ? ';' : ''}transition: ${resolvedDuration}s`}
    href={disabled ? undefined : href}
    aria-disabled={disabled || undefined}
    aria-pressed={isSelectable ? isSelected : undefined}
    role={isSelectable ? 'button' : undefined}
    draggable={!disabled && draggable}
    tabindex={disabled ? -1 : undefined}
    onfocus={handleFocus}
    onblur={handleBlur}
    onclick={handleClick}
    ondblclick={handleDoubleClick}
    onkeydown={handleKeydown}
    ondragstart={handleDragStart}
    ondragend={handleDragEnd}
  >
    {@render content()}
  </a>
{:else}
  <button
    {...rest}
    bind:this={rootElement}
    type="button"
    class={styles.current['chip']}
    style={`${hostStyle ?? ''}${hostStyle && !hostStyle.endsWith(';') ? ';' : ''}transition: ${resolvedDuration}s`}
    disabled={disabled}
    aria-pressed={isSelectable ? isSelected : undefined}
    draggable={!disabled && draggable}
    onfocus={handleFocus}
    onblur={handleBlur}
    onclick={handleClick}
    ondblclick={handleDoubleClick}
    onkeydown={handleKeydown}
    ondragstart={handleDragStart}
    ondragend={handleDragEnd}
  >
    {@render content()}
  </button>
{/if}

{#snippet content()}
  {#if isInteractive && !disabled && !isEditing}
    <StateLayer
      transitionDuration={resolvedDuration}
      class={styles.current['stateLayer']}
      colorName={classNames({
        'on-surface-variant': !isSelected,
        'on-secondary-container': isSelected,
      })}
      stateClassName="state-ripple-group-[chip]"
    />
  {/if}
  {#if resolvedIcon}
    <Icon icon={resolvedIcon} class={styles.current['leadingIcon']} />
  {/if}
  <span
    bind:this={labelElement}
    class={styles.current['label']}
    contenteditable={editable && isEditing}
    role={editable ? 'textbox' : undefined}
    spellcheck={editable && isEditing ? false : undefined}
    oninput={handleInput}
    onblur={(event) => editable && isEditing && handleBlur(event)}
  >
    {#if isEditing}{editValue}{:else if children}{@render children()}{:else}{label}{/if}
  </span>
  {#if hasTrailingIcon}
    <span
      aria-hidden="true"
      class={styles.current['trailingIcon']}
      onmousedown={(event) => { event.preventDefault(); event.stopPropagation(); }}
      onclick={(event) => { event.stopPropagation(); if (!disabled) onRemove?.(); }}
    >
      <Icon icon={iClose} class="size-full" />
    </span>
  {/if}
{/snippet}

// packages/ui-react/src/lib/components/Chip.tsx
import {
  type ChipInterface,
  chipStyle,
  classNames,
  getChipSelectionTransition,
  type ReactProps,
} from '@udixio/core';
import type { Transition } from 'motion';
import { Icon } from '../icon';
import { StateLayer } from './StateLayer';
import React, { useEffect, useRef, useState } from 'react';
import { iCheck } from '@udixio/icons-rounded-400/check';
import { iClose } from '@udixio/icons-rounded-400/close';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';

export type ReactChipProps = Omit<ReactProps<ChipInterface>, 'ref'> & {
  // `children` sert de repli de `label` → typé string (comme l'ancien contrat)
  children?: string;
  transition?: Transition;
  ref?: React.Ref<HTMLButtonElement | HTMLAnchorElement>;
};

export const useChipStyle = createUseStyle(chipStyle);

/**
 * Chips prompt most actions in a UI
 * @status beta
 * @category Action
 * @devx
 * - `editable` relies on contentEditable; label should be a string.
 * - Use `selected` with `onSelectedChange` for controlled selection, or
 *   `defaultSelected` for uncontrolled selection.
 * @a11y
 * - Uses `aria-pressed` only in selection mode.
 * - Disabled links lose their navigation target and tab stop.
 * @limitations
 * - Edit mode starts after a 1s focus delay (no prop to customize).
 */
export const Chip = ({
  variant = 'outlined',
  disabled = false,
  icon,
  href,
  label,
  className,
  onClick,
  onSelectedChange,
  selected,
  defaultSelected,
  ref,
  onRemove,
  draggable = false,
  editable,
  onEditStart,
  onEditCommit,
  onEditCancel,
  onChange,
  transition,
  children,
  editing,
  // Handlers utilisateur composés avec les handlers internes
  onFocus: userOnFocus,
  onBlur: userOnBlur,
  onKeyDown: userOnKeyDown,
  onDragStart: userOnDragStart,
  onDragEnd: userOnDragEnd,
  onDoubleClick: userOnDoubleClick,
  ...restProps
}: ReactChipProps) => {
  if (children) label = children;
  // Allow empty string when editable (newly created chips start empty)
  if (label === undefined && !editable) {
    throw new Error(
      'Chip component requires either a label prop or children content',
    );
  }

  const ElementType = href ? 'a' : 'button';

  const defaultRef = useRef<HTMLButtonElement | HTMLAnchorElement>(null);
  const resolvedRef = ref || defaultRef;

  const [isSelected, setSelected] = useControllableState({
    value: selected,
    defaultValue: defaultSelected ?? false,
    onChange: onSelectedChange,
    componentName: 'Chip',
    stateName: 'selected',
  });
  const [isFocused, setIsFocused] = React.useState(false);
  const [internalEditing, setInternalEditing] = useState(false);
  const isEditing = !!editable && (editing ?? internalEditing);
  const [isDragging, setIsDragging] = React.useState(false);
  const [editValue, setEditValue] = React.useState<string>(
    typeof label === 'string' ? label : '',
  );
  const editSpanRef = React.useRef<HTMLSpanElement>(null);
  useEffect(() => {
    if (editable && isFocused && !isEditing) {
      // Délai de 1 seconde avant d'activer l'édition
      const timerId = setTimeout(() => {
        // Ignore l'édition si draggable et en cours de dragging
        if (draggable && isDragging) {
          return;
        }
        if (editing === undefined) {
          setInternalEditing(true);
        }
        onEditStart?.();
      }, 1000);

      // Cleanup: annule le timer si le focus est perdu avant 1 seconde
      return () => clearTimeout(timerId);
    } else if (!isFocused) {
      // Désactive l'édition immédiatement si le focus est perdu
      if (editing === undefined) {
        setInternalEditing(false);
      }
    }
    return;
  }, [
    isFocused,
    editable,
    isDragging,
    draggable,
    isEditing,
    editing,
    onEditStart,
  ]);

  // Sync edit value and focus caret when entering editing mode
  useEffect(() => {
    if (isEditing) {
      setEditValue(typeof label === 'string' ? label : '');
      // focus contenteditable span and move caret to end
      const el =
        (labelRef.current as unknown as HTMLSpanElement) || editSpanRef.current;
      if (el) {
        el.focus();
        const range = document.createRange();
        range.selectNodeContents(el);
        range.collapse(false);
        const sel = window.getSelection();
        sel?.removeAllRanges();
        sel?.addRange(range);
      }
    }
  }, [isEditing]);

  transition = { duration: 0.3, ...transition };

  const handleClick = (e: React.MouseEvent<any, MouseEvent>) => {
    if (disabled) {
      e.preventDefault();
      return;
    }
    if (isSelectable) {
      const transition = getChipSelectionTransition({
        disabled,
        selected: isSelected,
      });
      if (transition.nextSelected !== undefined) {
        setSelected(transition.nextSelected);
      }
    }
    onClick?.(e);
  };

  const isSelectable =
    selected !== undefined ||
    defaultSelected !== undefined ||
    onSelectedChange !== undefined;
  const isInteractive =
    isSelectable || !!onRemove || !!onClick || !!href || !!editable;

  if (isSelected) {
    icon = iCheck;
  }

  const hasTrailingIcon = !!onRemove && !isEditing;

  const trailingIconHandlers = {
    onMouseDown: (e: React.MouseEvent) => {
      e.preventDefault(); // ⬅️ clé
      e.stopPropagation();
    },
    onClick: (e: React.MouseEvent) => {
      e.stopPropagation();
      if (!disabled) {
        onRemove?.();
      }
    },
  };

  const styles = useChipStyle({
    transition,
    // props
    label,
    variant,
    disabled,
    icon,
    selected,
    defaultSelected,
    onSelectedChange,
    onRemove,
    href,
    draggable,
    editable,
    editing,
    onEditStart,
    onEditCommit,
    onEditCancel,
    onChange,
    // states
    isSelected,
    isFocused,
    isInteractive,
    isDragging,
    isEditing,
    trailingIcon: hasTrailingIcon,
    className,
  });

  const labelRef = useRef(null);

  const handleCommit = () => {
    const trimmed = (editValue ?? '').trim();
    if (editing === undefined) {
      setInternalEditing(false);
    }
    if (!trimmed) {
      if (onRemove) {
        onRemove();
      }
      return;
    }
    onEditCommit?.(trimmed);
  };

  return (
    <ElementType
      contentEditable={false}
      ref={resolvedRef}
      className={styles.chip}
      {...(restProps as any)}
      onClick={(e: React.MouseEvent<any>) => {
        if (!isEditing) handleClick(e);
      }}
      draggable={!disabled && draggable}
      onDragStart={(e: React.DragEvent<any>) => {
        if (!disabled && draggable) {
          setIsDragging(true);
        }
        userOnDragStart?.(e);
      }}
      onDragEnd={(e: React.DragEvent<any>) => {
        if (draggable) {
          setIsDragging(false);
        }
        userOnDragEnd?.(e);
      }}
      onDoubleClick={(e: React.MouseEvent<any>) => {
        if (!disabled && editable && !isEditing) {
          if (editing === undefined) {
            setInternalEditing(true);
          }
          onEditStart?.();
          e.preventDefault();
          e.stopPropagation();
        }
        userOnDoubleClick?.(e);
      }}
      onFocus={(e: React.FocusEvent<any>) => {
        if (isInteractive) {
          setIsFocused(true);
        }
        userOnFocus?.(e);
      }}
      onBlur={(e: React.FocusEvent<any>) => {
        if (e.currentTarget.contains(e.relatedTarget as Node | null)) {
          return;
        }
        setIsFocused(false);
        userOnBlur?.(e);
      }}
      onKeyDown={(e: React.KeyboardEvent<any>) => {
        const key = e.key;

        // While editing: handle commit/cancel locally
        if (!disabled && isEditing) {
          if (key === 'Enter') {
            e.preventDefault();
            handleCommit();
          } else if (key === 'Escape') {
            e.preventDefault();
            if (editing === undefined) {
              setInternalEditing(false);
            }
            onEditCancel?.();
          } else if (
            onRemove &&
            editValue?.trim() === '' &&
            (key === 'Backspace' || key === 'Delete' || key === 'Del')
          ) {
            e.preventDefault();
            e.stopPropagation();
            onRemove();
          }
          return;
        }

        // Only handle keys when focused/selected and not disabled
        if (!disabled && isFocused) {
          // Start editing with F2 or Enter when editable and no toggle behavior
          if (editable && !isSelectable && (key === 'F2' || key === 'Enter')) {
            e.preventDefault();
            if (editing === undefined) {
              setInternalEditing(true);
            }
            onEditStart?.();
            return;
          }

          // Toggle active state on Enter or Space when togglable
          if (
            isSelectable &&
            (key === 'Enter' || key === ' ' || key === 'Spacebar')
          ) {
            e.preventDefault();
            const transition = getChipSelectionTransition({
              disabled,
              selected: isSelected,
            });
            if (transition.nextSelected !== undefined) {
              setSelected(transition.nextSelected);
            }
          }

          // Trigger remove on Backspace or Delete when removable
          if (
            onRemove &&
            (key === 'Backspace' || key === 'Delete' || key === 'Del')
          ) {
            e.preventDefault();
            e.stopPropagation();
            onRemove();
          }
        }

        // Delegate to user handler last
        userOnKeyDown?.(e);
      }}
      {...(href
        ? {
            href: disabled ? undefined : href,
            'aria-disabled': disabled || undefined,
            tabIndex: disabled ? -1 : undefined,
          }
        : { disabled, type: 'button' })}
      aria-pressed={isSelectable ? isSelected : undefined}
      style={{ transition: transition.duration + 's' }}
    >
      {isInteractive && !disabled && !isEditing && (
        <StateLayer
          transitionDuration={transition.duration}
          className={styles.stateLayer}
          colorName={classNames({
            'on-surface-variant': !isSelected,
            'on-secondary-container': isSelected,
          })}
          stateClassName={'state-ripple-group-[chip]'}
        />
      )}

      {icon && <Icon icon={icon} className={styles.leadingIcon} />}
      <span
        ref={labelRef}
        contentEditable={!!editable && !!isEditing}
        suppressContentEditableWarning
        className={styles.label}
        role={editable ? 'textbox' : undefined}
        spellCheck={false}
        onInput={(e) => {
          const text = (e.currentTarget as HTMLSpanElement).innerText;
          setEditValue(text);
          onChange?.(text);
        }}
        onBlur={() => {
          if (editable && isEditing) {
            handleCommit();
          }
        }}
        onKeyDown={(e) => {
          // prevent line breaks inside contenteditable
          if (editable && isEditing && e.key === 'Enter') {
            e.preventDefault();
            e.stopPropagation();
            handleCommit();
            return;
          }
          if (editable && isEditing && e.key === 'Escape') {
            e.preventDefault();
            e.stopPropagation();
            if (editing === undefined) {
              setInternalEditing(false);
            }
            onEditCancel?.();
          }
        }}
      >
        {label}
      </span>
      {hasTrailingIcon && (
        <span className={styles.trailingIcon} {...trailingIconHandlers}>
          <Icon icon={iClose} className="size-full" />
        </span>
      )}
    </ElementType>
  );
};
