// packages/ui-angular/src/lib/context-menu/context-menu.ts
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  booleanAttribute,
  forwardRef,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import type { ContextMenuProps, MenuVariant } from '@udixio/core';
import { createContextMenuController } from '@udixio/core/dom';
import { MENU_CONTEXT } from '../menu/menu-context';
import { Menu } from '../menu/menu';

/**
 * Opens a Menu at the pointer or keyboard context-menu position.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Mark the projected trigger with `contextMenuTrigger`; project Menu family elements into the default slot.
 * @a11y Supports native context-menu events and Shift+F10, focuses the first item, and restores trigger focus after Escape.
 * @limitations The popup position is internally owned and is not controllable.
 */
@Component({
  selector: 'udx-context-menu',
  standalone: true,
  imports: [Menu],
  providers: [
    {
      provide: MENU_CONTEXT,
      useExisting: forwardRef(() => ContextMenu),
    },
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div #root [class]="classes()" style="display: contents">
      <span
        #trigger
        style="display: contents"
        (contextmenu)="handleContextMenu($event)"
        (keydown)="handleKeydown($event)"
      >
        <ng-content select="[contextMenuTrigger]" />
      </span>
      @if (position(); as point) {
        <div
          #popup
          class="fixed z-50"
          [style.top.px]="point.y"
          [style.left.px]="point.x"
          (click)="close()"
        >
          <udx-menu
            purpose="actions"
            [variant]="variant()"
            [accessibleLabel]="accessibleLabel()"
          >
            <ng-content />
          </udx-menu>
        </div>
      }
    </div>
  `,
})
export class ContextMenu {
  readonly variant = input<MenuVariant>('standard');
  readonly accessibleLabel = input<ContextMenuProps['accessibleLabel']>();
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Classes applied to the display-contents root. */
  readonly classes = input<string>();

  /** Notifies visibility changes caused by user interaction. */
  readonly openChange = output<boolean>();
  readonly purpose = () => 'actions' as const;

  protected readonly position = signal<{ x: number; y: number } | null>(null);
  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly trigger = viewChild<ElementRef<HTMLElement>>('trigger');
  private readonly popup = viewChild<ElementRef<HTMLElement>>('popup');

  constructor() {
    afterRenderEffect((onCleanup) => {
      if (!this.position()) return;
      const root = this.root()?.nativeElement;
      const triggerHost = this.trigger()?.nativeElement;
      const menu =
        this.popup()?.nativeElement.querySelector<HTMLElement>('[role="menu"]');
      const triggerElement =
        triggerHost?.querySelector<HTMLElement>(
          'button, a[href], input, select, textarea, [tabindex]',
        ) ?? triggerHost;
      if (!root || !triggerElement || !menu) return;
      const controller = createContextMenuController({
        root,
        trigger: triggerElement,
        menu,
        onDismiss: () => this.close(),
      });
      onCleanup(() => controller.destroy());
    });
  }

  protected handleContextMenu(event: MouseEvent): void {
    if (this.disabled()) return;
    event.preventDefault();
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    this.openAt(event.clientX || rect.left, event.clientY || rect.bottom);
  }

  protected handleKeydown(event: KeyboardEvent): void {
    if (!event.shiftKey || event.key !== 'F10' || this.disabled()) return;
    event.preventDefault();
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    this.openAt(rect.left, rect.bottom);
  }

  private openAt(x: number, y: number): void {
    const wasOpen = Boolean(this.position());
    this.position.set({ x, y });
    if (!wasOpen) this.openChange.emit(true);
  }

  protected close(): void {
    if (!this.position()) return;
    this.position.set(null);
    this.openChange.emit(false);
  }
}

// packages/ui-react/src/lib/components/ContextMenu.tsx
import React, {
  useCallback,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import type { ContextMenuProps } from '@udixio/core';
import { createContextMenuController } from '@udixio/core/dom';
import { Menu } from './Menu';

export type ReactContextMenuProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  'children' | 'className'
> &
  Omit<ContextMenuProps, 'onOpenChange'> & {
    /** Element that receives pointer and Shift+F10 context-menu activation. */
    trigger: ReactNode;
    /** MenuItem, MenuGroup, and MenuHeadline content. */
    children?: ReactNode;
    /** Notifies visibility changes caused by user interaction. */
    onOpenChange?: (open: boolean) => void;
    /** Classes applied to the display-contents root. */
    className?: string;
  };

/**
 * Opens a Menu at the pointer or keyboard context-menu position.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Project the trigger through `trigger` and Menu family elements as children.
 * @a11y Supports native context-menu events and Shift+F10, focuses the first item, and restores trigger focus after Escape.
 * @limitations The popup position is internally owned and is not controllable.
 */
export const ContextMenu = ({
  trigger,
  children,
  variant = 'standard',
  accessibleLabel,
  disabled = false,
  onOpenChange,
  className,
  ...restProps
}: ReactContextMenuProps) => {
  const [position, setPosition] = useState<{ x: number; y: number } | null>(
    null,
  );
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const openRef = useRef(false);

  const close = useCallback(() => {
    if (!openRef.current) return;
    openRef.current = false;
    setPosition(null);
    onOpenChange?.(false);
  }, [onOpenChange]);

  const openAt = useCallback(
    (x: number, y: number) => {
      if (disabled) return;
      const wasOpen = openRef.current;
      openRef.current = true;
      setPosition({ x, y });
      if (!wasOpen) onOpenChange?.(true);
    },
    [disabled, onOpenChange],
  );

  useEffect(() => {
    if (!position) return;
    const root = rootRef.current;
    const triggerHost = triggerRef.current;
    const menu = menuRef.current;
    const triggerElement =
      triggerHost?.querySelector<HTMLElement>(
        'button, a[href], input, select, textarea, [tabindex]',
      ) ?? triggerHost;
    if (!root || !triggerElement || !menu) return;
    const controller = createContextMenuController({
      root,
      trigger: triggerElement,
      menu,
      onDismiss: close,
    });
    return () => controller.destroy();
  }, [close, position]);

  const handleContextMenu = (event: React.MouseEvent) => {
    if (disabled) return;
    event.preventDefault();
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    openAt(event.clientX || rect.left, event.clientY || rect.bottom);
  };

  return (
    <div
      {...restProps}
      ref={rootRef}
      className={className}
      style={{ display: 'contents' }}
    >
      <span
        ref={triggerRef}
        style={{ display: 'contents' }}
        onContextMenu={handleContextMenu}
        onKeyDown={(event) => {
          if (event.shiftKey && event.key === 'F10') {
            event.preventDefault();
            const rect = event.currentTarget.getBoundingClientRect();
            openAt(rect.left, rect.bottom);
          }
        }}
      >
        {trigger}
      </span>
      {position && (
        <div
          className="fixed z-50"
          style={{ top: position.y, left: position.x }}
        >
          <Menu
            ref={menuRef}
            purpose="actions"
            variant={variant}
            accessibleLabel={accessibleLabel}
            onClick={close}
          >
            {children}
          </Menu>
        </div>
      )}
    </div>
  );
};
