// packages/ui-angular/src/lib/fab-menu/fab-menu.ts
import {
  afterRenderEffect,
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  type OnInit,
  output,
  viewChild,
} from '@angular/core';
import {
  type ButtonInterface,
  type ClassNameComponent,
  DEFAULT_FAB_MENU_CLOSE_ICON,
  type FabMenuAction,
  type FabMenuInterface,
  type FabMenuProps,
  fabMenuStyle,
} from '@udixio/core';
import {
  createFabMenuController,
  type FabMenuController,
} from '@udixio/core/dom';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { Fab } from '../fab/fab';
import { Button } from '../button/button';

const optionalBooleanAttribute = (value: unknown): boolean | undefined =>
  value === undefined ? undefined : booleanAttribute(value);

export interface FabMenuActionSelectEvent {
  action: FabMenuAction;
  index: number;
}

/**
 * FabMenu exposes related primary actions from one toggleable FAB.
 *
 * @status stable
 * @category Action
 * @devx
 * - Uses the framework-independent `actions` input.
 * - `open` is controlled; `defaultOpen` initializes uncontrolled usage.
 * - Opening contracts every trigger size to a small icon-only close control while preserving the closed footprint.
 * - Action choreography is implemented once with Motion JavaScript in `@udixio/core/dom`.
 * @a11y
 * - The trigger exposes `aria-expanded`/`aria-controls`.
 * - Opening focuses the first enabled action; Escape closes and restores trigger focus.
 * - Outside press and selection close the action group.
 * - Reduced-motion preference keeps state changes immediate and fully perceivable.
 * @limitations
 * - Consumers own action-specific side effects through the `actionSelect` output.
 */
@Component({
  selector: 'udx-fab-menu',
  standalone: true,
  imports: [Fab, Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      #root
      [class]="styles()['fabMenu']"
      [hidden]="!hasAccessibleLabel()"
      [attr.aria-hidden]="!hasAccessibleLabel() || null"
      [attr.data-open]="isOpen()"
    >
      <span
        #closedTriggerHost
        [class]="styles()['triggerSizer']"
        aria-hidden="true"
        inert
      >
        <udx-fab
          [label]="label()"
          [icon]="icon()"
          [variant]="closedTriggerVariant()"
          [size]="size()"
          [extended]="extended()"
          disabled
          [tabIndex]="-1"
        />
        <span #openTriggerHost [class]="styles()['triggerPositioner']">
          <udx-fab
            [label]="closeLabel() ?? 'Close ' + label()"
            [icon]="closeIcon() || defaultCloseIcon"
            [variant]="variant()"
            size="small"
            disabled
            [tabIndex]="-1"
          />
        </span>
      </span>

      <span #triggerHost [class]="styles()['triggerPositioner']">
        <udx-fab
          [label]="resolvedTriggerLabel()"
          [icon]="resolvedTriggerIcon()"
          [variant]="triggerVariant()"
          [size]="isOpen() ? 'small' : size()"
          [extended]="extended() && !isOpen()"
          [disabled]="disabled() || !hasAccessibleLabel()"
          [classes]="styles()['fab']"
          [aria-expanded]="isOpen()"
          [aria-controls]="panelId()"
          (click)="toggle()"
        />
      </span>

      <div
        #panel
        [id]="panelId()"
        [class]="styles()['actions']"
        role="group"
        [attr.aria-label]="resolvedActionsLabel()"
        [attr.aria-hidden]="!isOpen() || null"
        [attr.inert]="!isOpen() ? '' : null"
      >
        @for (action of actions(); track action.id; let index = $index) {
          <span [class]="styles()['actionContainer']" data-fab-menu-action>
            <udx-button
              [label]="action.label"
              [icon]="action.icon"
              [href]="action.href"
              [disabled]="disabled() || !!action.disabled"
              variant="filled"
              shape="rounded"
              [classes]="actionClassName"
              [stateColor]="actionStateColor()"
              (click)="selectAction(action, index)"
            />
          </span>
        }
      </div>
    </div>
  `,
})
export class FabMenu implements OnInit {
  readonly label = input.required<string>();
  readonly icon = input.required<FabMenuProps['icon']>();
  readonly actions = input.required<readonly FabMenuAction[]>();
  readonly closeIcon = input<FabMenuProps['closeIcon']>();
  readonly closeLabel = input<string>();
  readonly actionsLabel = input<string>();
  readonly variant = input<FabMenuProps['variant']>('primary');
  readonly size = input<FabMenuProps['size']>('small');
  readonly extended = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly open = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  });
  readonly defaultOpen = input(false, { transform: booleanAttribute });
  /** Classes or state-aware element classes applied through the shared style contract. */
  readonly classes = input<string | ClassNameComponent<FabMenuInterface>>();

  /** Emits an accepted open-state request and supports `[(open)]`. */
  readonly openChange = output<boolean>();
  /** Emits the selected action and its source index before closing. */
  readonly actionSelect = output<FabMenuActionSelectEvent>();

  private readonly openState = createControllableState({
    value: this.open,
    defaultValue: this.defaultOpen,
    onChange: (open) => this.openChange.emit(open),
    componentName: 'FabMenu',
    stateName: 'open',
  });
  protected readonly isOpen = this.openState.value;
  protected readonly hasAccessibleLabel = computed(
    () => this.label().trim() !== '',
  );
  protected readonly resolvedTriggerLabel = computed(() =>
    this.isOpen()
      ? (this.closeLabel() ?? `Close ${this.label()}`)
      : this.label(),
  );
  protected readonly resolvedTriggerIcon = computed(
    () =>
      (this.isOpen() && this.closeIcon()) ||
      (this.isOpen() ? DEFAULT_FAB_MENU_CLOSE_ICON : this.icon()),
  );
  protected readonly resolvedActionsLabel = computed(
    () => this.actionsLabel() ?? `${this.label()} actions`,
  );
  protected readonly triggerVariant = computed(
    () =>
      (this.isOpen() ? this.variant() : `${this.variant()}Container`) as
        | 'primary'
        | 'secondary'
        | 'tertiary'
        | 'primaryContainer'
        | 'secondaryContainer'
        | 'tertiaryContainer',
  );
  protected readonly closedTriggerVariant = computed(
    () =>
      `${this.variant()}Container` as
        'primaryContainer' | 'secondaryContainer' | 'tertiaryContainer',
  );
  protected readonly panelId = computed(() => `fab-menu-${this.instanceId}`);
  protected readonly defaultCloseIcon = DEFAULT_FAB_MENU_CLOSE_ICON;
  protected readonly styles = createStyle(fabMenuStyle, () => ({
    label: this.label(),
    icon: this.icon(),
    actions: this.actions(),
    closeIcon: this.closeIcon(),
    closeLabel: this.closeLabel(),
    actionsLabel: this.actionsLabel(),
    variant: this.variant(),
    size: this.size(),
    extended: this.extended(),
    disabled: this.disabled(),
    open: this.open(),
    defaultOpen: this.defaultOpen(),
    isOpen: this.isOpen(),
    className: this.classes(),
  }));

  private static nextId = 0;
  private readonly instanceId = FabMenu.nextId++;
  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly triggerHost =
    viewChild<ElementRef<HTMLElement>>('triggerHost');
  private readonly closedTriggerHost =
    viewChild<ElementRef<HTMLElement>>('closedTriggerHost');
  private readonly openTriggerHost =
    viewChild<ElementRef<HTMLElement>>('openTriggerHost');
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
  private controller?: FabMenuController;

  constructor() {
    afterRenderEffect((onCleanup) => {
      const root = this.root()?.nativeElement;
      const trigger =
        this.triggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const closedTrigger =
        this.closedTriggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const openTrigger =
        this.openTriggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const panel = this.panel()?.nativeElement;
      if (!root || !trigger || !closedTrigger || !openTrigger || !panel) return;

      const controller = createFabMenuController({
        root,
        trigger,
        closedTrigger,
        openTrigger,
        panel,
        onDismiss: () => this.openState.set(false),
      });
      this.controller = controller;
      onCleanup(() => {
        controller.destroy();
        if (this.controller === controller) {
          this.controller = undefined;
        }
      });
    });

    afterRenderEffect(() => {
      this.controller?.setOpen(this.isOpen());
    });
  }

  // The action is repainted onto a container surface, so the state layer must
  // contrast with that, not with the filled variant's own primary background.
  protected readonly actionStateColor = computed(
    () => `on-${this.variant()}-container`,
  );

  ngOnInit(): void {
    this.openState.initialize();
  }

  protected readonly actionClassName: ClassNameComponent<ButtonInterface> =
    () => ({
      button: this.styles()['action'],
    });

  protected toggle(): void {
    if (!this.disabled() && this.hasAccessibleLabel()) {
      this.openState.set(!this.isOpen());
    }
  }

  protected selectAction(action: FabMenuAction, index: number): void {
    if (this.disabled() || action.disabled) return;
    this.actionSelect.emit({ action, index });
    this.controller?.restoreFocusOnClose();
    this.openState.set(false);
  }
}

// packages/ui-react/src/lib/components/FabMenu.tsx
import { type HTMLAttributes, type Ref, useEffect, useId, useRef } from 'react';
import {
  type ComponentClassName,
  DEFAULT_FAB_MENU_CLOSE_ICON,
  type FabMenuAction,
  type FabMenuInterface,
  type FabMenuProps,
  fabMenuStyle,
} from '@udixio/core';
import {
  createFabMenuController,
  type FabMenuController,
} from '@udixio/core/dom';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';
import { Fab } from './Fab';
import { Button } from './Button';

export type { FabMenuAction, FabMenuVariant } from '@udixio/core';

type ReactFabMenuOwnProps = FabMenuProps & {
  /** Classes or state-aware element classes applied through the shared style contract. */
  className?: ComponentClassName<FabMenuInterface>['className'];
  /** Notifies an accepted open-state request. */
  onOpenChange?: (open: boolean) => void;
  /** Notifies selection before the menu closes. */
  onActionSelect?: (action: FabMenuAction, index: number) => void;
  ref?: Ref<HTMLDivElement>;
};

export type ReactFabMenuProps = ReactFabMenuOwnProps &
  Omit<
    HTMLAttributes<HTMLDivElement>,
    keyof ReactFabMenuOwnProps | 'children' | 'className'
  >;

export const useFabMenuStyle = createUseStyle(fabMenuStyle);

/**
 * FabMenu exposes related primary actions from one toggleable FAB.
 *
 * @status stable
 * @category Action
 * @devx
 * - Uses the framework-independent `actions` model instead of framework-specific children.
 * - `open` is controlled; `defaultOpen` initializes uncontrolled usage.
 * - Opening contracts every trigger size to a small icon-only close control while preserving the closed footprint.
 * - Action choreography is implemented once with Motion JavaScript in `@udixio/core/dom`.
 * @a11y
 * - The trigger exposes `aria-expanded`/`aria-controls`.
 * - Opening focuses the first enabled action; Escape closes and restores trigger focus.
 * - Outside press and selection close the group without applying false ARIA menu semantics.
 * - Reduced-motion preference keeps state changes immediate and fully perceivable.
 * @limitations
 * - Consumers own action-specific side effects through `onActionSelect`.
 */
export const FabMenu = (props: ReactFabMenuProps) => {
  const {
    label,
    icon,
    actions,
    closeIcon = DEFAULT_FAB_MENU_CLOSE_ICON,
    closeLabel = `Close ${label}`,
    actionsLabel = `${label} actions`,
    variant = 'primary',
    size = 'small',
    extended = false,
    disabled = false,
    open: openProp,
    defaultOpen = false,
    onOpenChange,
    onActionSelect,
    className,
    ref,
    ...nativeProps
  } = props;
  const [open, setOpen] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
    componentName: 'FabMenu',
    stateName: 'open',
  });
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const closedTriggerRef = useRef<HTMLButtonElement>(null);
  const openTriggerRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const controllerRef = useRef<FabMenuController>(null);
  const panelId = `fab-menu-${useId().replace(/:/g, '')}`;
  const hasAccessibleLabel = label.trim() !== '';
  const styles = useFabMenuStyle({
    label,
    icon,
    actions,
    closeIcon,
    closeLabel,
    actionsLabel,
    variant,
    size,
    extended,
    disabled,
    open: openProp,
    defaultOpen,
    isOpen: open,
    className,
  });

  useEffect(() => {
    if (
      !hasAccessibleLabel ||
      !rootRef.current ||
      !triggerRef.current ||
      !closedTriggerRef.current ||
      !openTriggerRef.current ||
      !panelRef.current
    ) {
      return;
    }

    const controller = createFabMenuController({
      root: rootRef.current,
      trigger: triggerRef.current,
      closedTrigger: closedTriggerRef.current,
      openTrigger: openTriggerRef.current,
      panel: panelRef.current,
      onDismiss: () => setOpen(false),
    });
    controllerRef.current = controller;
    return () => {
      controller.destroy();
      if (controllerRef.current === controller) {
        controllerRef.current = null;
      }
    };
  }, [hasAccessibleLabel, setOpen]);

  useEffect(() => {
    controllerRef.current?.setOpen(open);
  }, [open]);

  const selectAction = (action: FabMenuAction, index: number) => {
    if (disabled || action.disabled) return;
    onActionSelect?.(action, index);
    controllerRef.current?.restoreFocusOnClose();
    setOpen(false);
  };
  const triggerVariant = `${variant}Container` as const;

  if (!hasAccessibleLabel) {
    if (
      typeof process !== 'undefined' &&
      process.env?.NODE_ENV !== 'production'
    ) {
      console.error(
        'Udixio UI: <FabMenu> requires a non-empty `label`. Rendering nothing.',
      );
    }
    return null;
  }

  return (
    <div
      {...nativeProps}
      ref={(node) => {
        rootRef.current = node;
        if (typeof ref === 'function') ref(node);
        else if (ref) ref.current = node;
      }}
      className={styles.fabMenu}
      data-open={open}
    >
      <span className={styles.triggerSizer} aria-hidden="true" inert>
        <Fab
          ref={closedTriggerRef}
          label={label}
          icon={icon}
          variant={triggerVariant}
          size={size}
          extended={extended}
          disabled
          tabIndex={-1}
        />
        <span className={styles.triggerPositioner}>
          <Fab
            ref={openTriggerRef}
            label={closeLabel}
            icon={closeIcon}
            variant={variant}
            size="small"
            disabled
            tabIndex={-1}
          />
        </span>
      </span>

      <span className={styles.triggerPositioner}>
        <Fab
          ref={triggerRef}
          label={open ? closeLabel : label}
          icon={open ? closeIcon : icon}
          variant={open ? variant : triggerVariant}
          size={open ? 'small' : size}
          extended={extended && !open}
          disabled={disabled}
          className={styles.fab}
          aria-expanded={open}
          aria-controls={panelId}
          onClick={() => setOpen(!open)}
        />
      </span>

      <div
        ref={panelRef}
        id={panelId}
        className={styles.actions}
        role="group"
        aria-label={actionsLabel}
        aria-hidden={!open}
        inert={!open}
      >
        {actions.map((action, index) => {
          const actionClassName = () => ({
            button: styles.action,
          });
          const sharedActionProps = {
            label: action.label,
            icon: action.icon,
            disabled: disabled || action.disabled,
            variant: 'filled' as const,
            shape: 'rounded' as const,
            className: actionClassName,
            // The action is repainted onto a container surface, so the state
            // layer must contrast with that, not with the filled variant's
            // own primary background.
            stateColor: `on-${variant}-container`,
          };

          return (
            <span
              key={action.id}
              className={styles.actionContainer}
              data-fab-menu-action=""
            >
              {action.href ? (
                <Button
                  {...sharedActionProps}
                  href={action.href}
                  onClick={() => selectAction(action, index)}
                />
              ) : (
                <Button
                  {...sharedActionProps}
                  onClick={() => selectAction(action, index)}
                />
              )}
            </span>
          );
        })}
      </div>
    </div>
  );
};
