// packages/ui-angular/src/lib/menu/menu-headline.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import {
  menuHeadlineStyle,
  type ClassNameComponent,
  type MenuHeadlineInterface,
  type MenuHeadlineProps,
} from '@udixio/core';
import { createStyle } from '../utils/create-style';
import { MENU_CONTEXT } from './menu-context';

/**
 * A non-interactive visual heading inside a Menu.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Use MenuGroup when the heading must also name a semantic group.
 * @a11y Rendered as presentational text and excluded from menu keyboard navigation.
 * @limitations Does not create a heading landmark or label neighboring items.
 */
@Component({
  selector: 'udx-menu-headline',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': "styles()['headline']",
    role: 'presentation',
  },
  template: `{{ label() }}`,
})
export class MenuHeadline {
  readonly label = input.required<string>();
  readonly variant = input<MenuHeadlineProps['variant']>();
  readonly className = input<
    string | ClassNameComponent<MenuHeadlineInterface>
  >();

  private readonly context = inject(MENU_CONTEXT, { optional: true });
  private readonly resolvedVariant = computed(
    () => this.variant() ?? this.context?.variant() ?? 'standard',
  );
  protected readonly styles = createStyle(menuHeadlineStyle, () => ({
    label: this.label(),
    variant: this.resolvedVariant(),
    className: this.className(),
  }));
}

// packages/ui-react/src/lib/components/MenuHeadline.tsx
import {
  type MenuHeadlineInterface,
  menuHeadlineStyle,
  type ReactProps,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';
import { useMenuContext } from './menu-context';

export type ReactMenuHeadlineProps = ReactProps<MenuHeadlineInterface>;

export const useMenuHeadlineStyle = createUseStyle(menuHeadlineStyle);

/**
 * A non-interactive visual heading inside a Menu.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Use MenuGroup when the heading must also name a semantic group.
 * @a11y Rendered as presentational text and excluded from menu keyboard navigation.
 * @limitations Does not create a heading landmark or label neighboring items.
 */
export const MenuHeadline = ({
  label,
  variant,
  className,
  ...restProps
}: ReactMenuHeadlineProps) => {
  const context = useMenuContext();
  const resolvedVariant = variant ?? context.variant;
  const styles = useMenuHeadlineStyle({
    label,
    variant: resolvedVariant,
    className,
  });
  return (
    <div {...restProps} className={styles.headline} role="presentation">
      {label}
    </div>
  );
};
