// packages/ui-angular/src/lib/navigation-rail/navigation-rail-item.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  booleanAttribute,
  computed,
  inject,
  input,
  viewChild,
} from '@angular/core';
import {
  navigationRailItemStyle,
  resolveNavigationRailItemSelection,
  type ClassNameComponent,
  type Icon as IconType,
  type NavigationRailItemInterface,
} from '@udixio/core';
import {
  createNavigationRailItemLabelController,
  type NavigationRailItemLabelController,
} from '@udixio/core/dom';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';
import { createStyle } from '../utils/create-style';
import { NAVIGATION_RAIL_CONTEXT } from './navigation-rail-context';

/**
 * A single destination inside a `udx-navigation-rail`; renders as a link
 * when `href` is provided, otherwise as a button.
 * @status beta
 * @parent NavigationRail
 * @devx
 * - Selection is index-based and resolved from the parent rail; standalone
 *   usage falls back to `selected`.
 * - An item placed after a `udx-navigation-rail-section` only renders while
 *   the rail is extended.
 * - The label reveal (width/height + opacity, on `extended` changes) is
 *   driven by a shared `@udixio/core/dom` Motion controller, the same one
 *   the React adapter uses.
 * @a11y
 * - Exposes `aria-current="page"` when selected, since the rail is a
 *   navigation landmark rather than a tabbed panel switcher.
 * @limitations
 * - No arrow-key navigation between items; relies on the native sequential
 *   tab order.
 */
@Component({
  selector: 'udx-navigation-rail-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, Icon, StateLayer],
  host: { style: 'display: contents' },
  template: `
    @if (!hidden()) {
      @if (href() !== undefined) {
        <a
          [class]="styles()['navigationRailItem']"
          [attr.href]="href()"
          [attr.aria-current]="isSelected() ? 'page' : null"
          style="transition: 0.3s"
          (click)="handleClick()"
        >
          <ng-container [ngTemplateOutlet]="content" />
        </a>
      } @else {
        <button
          type="button"
          [class]="styles()['navigationRailItem']"
          [attr.aria-current]="isSelected() ? 'page' : null"
          style="transition: 0.3s"
          (click)="handleClick()"
        >
          <ng-container [ngTemplateOutlet]="content" />
        </button>
      }
    }

    <ng-template #content>
      <span [class]="styles()['container']" [style.transition]="containerTransition()">
        <udx-state-layer
          [className]="styles()['stateLayer']"
          [colorName]="isSelected() ? 'on-secondary-container' : 'on-surface'"
          stateClassName="state-ripple-group-[navigation-rail-item]"
        />
        @if (icon()) {
          <udx-icon
            [icon]="(isSelected() ? iconSelected() : icon())!"
            [className]="styles()['icon']"
          />
        }
        <span
          #horizontalLabel
          [class]="styles()['label']"
          [attr.aria-hidden]="resolvedVariant() !== 'horizontal'"
          [style]="initialHorizontalStyle"
          >{{ label() }}</span
        >
      </span>
      <span
        #verticalLabel
        [class]="styles()['label']"
        [attr.aria-hidden]="resolvedVariant() !== 'vertical'"
        [style]="initialVerticalStyle"
        >{{ label() }}</span
      >
    </ng-template>
  `,
})
export class NavigationRailItem {
  /** Text shown alongside (or as the accessible name for) the icon. */
  readonly label = input<string>();
  /** Icon shown while the item is not selected. */
  readonly icon = input<IconType>();
  /** Icon shown while the item is selected. */
  readonly iconSelected = input<IconType>();
  /** Controlled selected state, used when no parent drives the selection. */
  readonly selected = input(false, { transform: booleanAttribute });
  /** Navigation destination; switches the inner element to a native link. */
  readonly href = input<string>();
  readonly className = input<
    string | ClassNameComponent<NavigationRailItemInterface>
  >();

  private readonly context = inject(NAVIGATION_RAIL_CONTEXT, {
    optional: true,
  });
  private readonly elementRef = inject(ElementRef<HTMLElement>);

  protected readonly resolvedIndex = computed(() =>
    this.context?.indexOf(this),
  );
  protected readonly resolvedVariant = computed<'vertical' | 'horizontal'>(
    () => (this.context?.isExtended() ? 'horizontal' : 'vertical'),
  );
  protected readonly isSelected = computed(() =>
    resolveNavigationRailItemSelection({
      selectedItem: this.context?.selectedIndex() ?? null,
      index: this.resolvedIndex(),
      selected: this.selected(),
    }),
  );
  protected readonly hidden = computed(
    () =>
      (this.context?.hasPrecedingSection(this) ?? false) &&
      !(this.context?.isExtended() ?? true),
  );
  // Staggers the container's own `gap` transition behind the label reveal,
  // matching the React adapter's timing exactly.
  protected readonly containerTransition = computed(() =>
    this.resolvedVariant() === 'horizontal'
      ? '0.3s, gap 0.15s 0.15s'
      : '0.3s, gap 0.1s 0.2s',
  );

  protected readonly styles = createStyle(navigationRailItemStyle, () => ({
    label: this.label(),
    icon: this.icon()!,
    iconSelected: this.iconSelected()!,
    selected: this.selected(),
    variant: this.resolvedVariant(),
    index: this.resolvedIndex(),
    selectedItem: this.context?.selectedIndex() ?? null,
    isExtended: this.context?.isExtended(),
    extendedOnly: this.context?.hasPrecedingSection(this),
    isSelected: this.isSelected(),
    className: this.className(),
  }));

  /** @internal Read by the parent rail to order this item relative to sections. */
  get nativeElement(): HTMLElement {
    return this.elementRef.nativeElement;
  }

  private readonly horizontalLabel =
    viewChild<ElementRef<HTMLElement>>('horizontalLabel');
  private readonly verticalLabel =
    viewChild<ElementRef<HTMLElement>>('verticalLabel');
  private wiredHorizontalEl?: HTMLElement;
  private wiredVerticalEl?: HTMLElement;
  private horizontalController?: NavigationRailItemLabelController;
  private verticalController?: NavigationRailItemLabelController;

  // Captured once, from whichever variant this component actually mounted
  // with, and never updated afterward -- it exists only so server-rendered/
  // first-paint markup is already correct before hydration, instead of both
  // labels being visible until afterRenderEffect runs. If this were a
  // computed() re-evaluated on every resolvedVariant() change, it would
  // race the Motion controller: Angular would jump the style straight to
  // the new target before the effect's animate() call ever reads a "from"
  // value to animate from, i.e. every transition would silently become a
  // no-op snap.
  protected readonly initialHorizontalStyle: Record<string, string>;
  protected readonly initialVerticalStyle: Record<string, string>;

  constructor() {
    // The label is always mounted in both positions (horizontal, inside the
    // container; vertical, after it); the shared `@udixio/core/dom`
    // controller animates whichever one matches the current variant, so
    // this component never has to coordinate an exit-animation-before-
    // removal sequence with `@if`.
    const destroyRef = inject(DestroyRef);

    const initialVariant = this.resolvedVariant();
    this.initialHorizontalStyle =
      initialVariant === 'horizontal'
        ? { overflow: 'hidden' }
        : { width: '0px', opacity: '0', overflow: 'hidden' };
    this.initialVerticalStyle =
      initialVariant === 'vertical'
        ? { overflow: 'hidden' }
        : { height: '0px', opacity: '0', overflow: 'hidden' };

    afterRenderEffect(() => {
      const horizontalEl = this.horizontalLabel()?.nativeElement;
      const verticalEl = this.verticalLabel()?.nativeElement;
      if (!horizontalEl || !verticalEl) return;

      // The viewChild query signal can refresh its own wrapper identity on
      // every render without the underlying DOM node actually changing
      // (this item has no preceding section, no `@if` toggles at all, and
      // it still happened). Guarding on the *native element* -- not the
      // signal firing -- is what keeps this effect from tearing down and
      // recreating both controllers on every single render: that reset
      // their "first apply is instant" bookkeeping each time, so every
      // extend/collapse was replayed as a fresh mount and silently never
      // animated.
      if (
        horizontalEl === this.wiredHorizontalEl &&
        verticalEl === this.wiredVerticalEl
      ) {
        return;
      }
      this.horizontalController?.destroy();
      this.verticalController?.destroy();

      this.wiredHorizontalEl = horizontalEl;
      this.wiredVerticalEl = verticalEl;
      this.horizontalController = createNavigationRailItemLabelController({
        label: horizontalEl,
        axis: () => 'horizontal',
        visible: () => this.resolvedVariant() === 'horizontal',
      });
      this.verticalController = createNavigationRailItemLabelController({
        label: verticalEl,
        axis: () => 'vertical',
        visible: () => this.resolvedVariant() === 'vertical',
      });
    });

    destroyRef.onDestroy(() => {
      this.horizontalController?.destroy();
      this.verticalController?.destroy();
    });

    afterRenderEffect(() => {
      this.resolvedVariant();
      this.horizontalController?.update();
      this.verticalController?.update();
    });
  }

  protected handleClick(): void {
    const index = this.resolvedIndex();
    if (index != null) {
      this.context?.select(index);
    }
  }
}

// packages/ui-react/src/lib/components/NavigationRailItem.tsx
import React, {
  type Dispatch,
  type RefObject,
  type SetStateAction,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from 'react';
import type { Transition } from 'motion';

import { Icon } from '../icon';
import {
  classNames,
  type NavigationRailItemInterface,
  navigationRailItemStyle,
  type ReactProps,
  resolveNavigationRailItemSelection,
} from '@udixio/core';
import {
  createNavigationRailItemLabelController,
  type NavigationRailItemLabelController,
} from '@udixio/core/dom';
import { createUseStyle } from '../utils/create-use-style';
import { StateLayer } from './StateLayer';

/** Payload emitted when an item becomes the selected one. */
export type NavigationRailItemSelectedEvent = Pick<
  NavigationRailItemInterface['props'],
  'label' | 'icon'
> & {
  index: number;
  ref: RefObject<any>;
};

export type ReactNavigationRailItemProps =
  ReactProps<NavigationRailItemInterface> & {
    // `children` sert de repli de `label` → typé string (comme Fab / IconButton)
    children?: string;
    href?: string;
    transition?: Transition;
    setSelectedItem?: Dispatch<SetStateAction<number | null>>;
    onItemSelected?: (args: NavigationRailItemSelectedEvent) => void;
  };

export const useNavigationRailItemStyle = createUseStyle(
  navigationRailItemStyle,
);

/**
 * A single destination inside a `NavigationRail`; renders as a link when
 * `href` is provided, otherwise as a button.
 * @status beta
 * @parent NavigationRail
 * @devx
 * - Selection is index-based and provided by the parent rail.
 * - `extendedOnly` hides items when the rail is collapsed.
 * - The label reveal (width/height + opacity, on `extended` changes) is
 *   driven by a shared `@udixio/core/dom` Motion controller, the same one
 *   the Angular adapter uses.
 * @a11y
 * - Exposes `aria-current="page"` when selected, since the rail is a
 *   navigation landmark rather than a tabbed panel switcher.
 * @limitations
 * - No arrow-key navigation between items; relies on the native sequential
 *   tab order (a roving tabindex is only required for `tablist`/`listbox`
 *   widgets, which this is not).
 */
export const NavigationRailItem = ({
  className,
  onClick,
  label,
  variant = 'vertical',
  href,
  icon,
  selectedItem,
  setSelectedItem,
  index,
  onItemSelected,
  selected = false,
  ref,
  transition,
  isExtended,
  iconSelected,
  style,
  extendedOnly,
  children,
  ...restProps
}: ReactNavigationRailItemProps) => {
  if (children) label = children;

  const defaultRef = useRef<any>(null);
  const resolvedRef = ref || defaultRef;

  const isSelected = resolveNavigationRailItemSelection({
    selectedItem,
    index,
    selected,
  });

  useEffect(() => {
    if (selectedItem == index && onItemSelected) {
      onItemSelected({
        ref: resolvedRef as any,
        index: index || 0,
        label,
        icon,
      });
    }
  }, [selectedItem, index, onItemSelected, label, icon, resolvedRef]);

  // The label is always mounted in both positions (horizontal, inside the
  // container; vertical, after it); a shared `@udixio/core/dom` controller
  // animates whichever one matches the current variant, so neither adapter
  // has to coordinate an exit-animation-before-unmount sequence.
  //
  // The resting width/height/opacity below is captured once (lazy useState
  // initializer, matching the variant this component actually mounted
  // with) and never updated by React afterward -- it exists only so
  // server-rendered/first-paint markup is already correct before
  // hydration, instead of both labels being visible until the layout
  // effect runs. If this were recomputed reactively on every render, it
  // would race the Motion controller: React would jump the style straight
  // to the new target before the effect's animate() call ever reads a
  // "from" value to animate from, i.e. every transition would silently
  // become a no-op snap.
  const [initialHorizontalStyle] = useState<React.CSSProperties>(() =>
    variant === 'horizontal'
      ? { overflow: 'hidden' }
      : { width: 0, opacity: 0, overflow: 'hidden' },
  );
  const [initialVerticalStyle] = useState<React.CSSProperties>(() =>
    variant === 'vertical'
      ? { overflow: 'hidden' }
      : { height: 0, opacity: 0, overflow: 'hidden' },
  );
  const variantRef = useRef(variant);
  variantRef.current = variant;
  const horizontalLabelRef = useRef<HTMLSpanElement | null>(null);
  const verticalLabelRef = useRef<HTMLSpanElement | null>(null);
  const horizontalController = useRef<NavigationRailItemLabelController | null>(
    null,
  );
  const verticalController = useRef<NavigationRailItemLabelController | null>(
    null,
  );

  useLayoutEffect(() => {
    if (!horizontalLabelRef.current || !verticalLabelRef.current) return;

    horizontalController.current = createNavigationRailItemLabelController({
      label: horizontalLabelRef.current,
      axis: () => 'horizontal',
      visible: () => variantRef.current === 'horizontal',
      duration: transition?.duration ?? 0.3,
    });
    verticalController.current = createNavigationRailItemLabelController({
      label: verticalLabelRef.current,
      axis: () => 'vertical',
      visible: () => variantRef.current === 'vertical',
      duration: transition?.duration ?? 0.3,
    });

    return () => {
      horizontalController.current?.destroy();
      verticalController.current?.destroy();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    horizontalController.current?.update();
    verticalController.current?.update();
  }, [variant]);

  const ElementType = href ? 'a' : 'button';

  const handleClick = (e: React.MouseEvent<any>) => {
    if (setSelectedItem) {
      setSelectedItem(index ?? null);
    }
    if (onClick) {
      onClick(e);
    }
  };

  const styles = useNavigationRailItemStyle({
    label,
    icon,
    iconSelected,
    selected,
    variant,
    index,
    selectedItem,
    isExtended,
    extendedOnly,
    isSelected,
    className,
  });

  transition = { duration: 0.3, ...transition };

  if (extendedOnly && !isExtended) return null;

  return (
    <ElementType
      {...(restProps as any)}
      aria-current={isSelected ? 'page' : undefined}
      ref={resolvedRef as any}
      href={href}
      className={styles.navigationRailItem}
      onClick={handleClick}
      style={{ transition: transition.duration + 's', ...style }}
    >
      <span
        style={{
          transition:
            variant == 'horizontal'
              ? transition.duration +
                `s, gap ${transition.duration! / 2}s ${transition.duration! - transition.duration! / 2}s`
              : transition.duration +
                `s, gap ${transition.duration! / 3}s ${transition.duration! - transition.duration! / 3}s`,
        }}
        className={styles.container}
      >
        <StateLayer
          transitionDuration={transition.duration}
          className={styles.stateLayer}
          colorName={classNames({
            'on-surface': !isSelected,
            'on-secondary-container': isSelected,
          })}
          stateClassName={'state-ripple-group-[navigation-rail-item]'}
        />
        {icon && (
          <Icon
            icon={isSelected ? iconSelected : icon}
            className={styles.icon}
          />
        )}
        <span
          ref={horizontalLabelRef}
          className={styles.label}
          aria-hidden={variant !== 'horizontal'}
          style={initialHorizontalStyle}
        >
          {label}
        </span>
      </span>
      <span
        ref={verticalLabelRef}
        className={styles.label}
        aria-hidden={variant !== 'vertical'}
        style={initialVerticalStyle}
      >
        {label}
      </span>
    </ElementType>
  );
};
