// packages/ui-angular/src/lib/navigation-rail/navigation-rail.ts
import {
  ChangeDetectionStrategy,
  Component,
  afterRenderEffect,
  contentChildren,
  forwardRef,
  input,
  output,
  type OnInit,
} from '@angular/core';
import {
  getNextNavigationRailExtended,
  navigationRailStyle,
  type ClassNameComponent,
  type Icon,
  type NavigationRailInterface,
  type NavigationRailMenuState,
  type NavigationRailProps,
} from '@udixio/core';
import { iClose } from '@udixio/icons-rounded-400/close';
import { iMenu } from '@udixio/icons-rounded-400/menu';
import { IconButton } from '../icon-button/icon-button';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import {
  NAVIGATION_RAIL_CONTEXT,
  type NavigationRailContext,
} from './navigation-rail-context';
import { NavigationRailItem } from './navigation-rail-item';
import { NavigationRailSection } from './navigation-rail-section';

/** Payload emitted when an item becomes the selected one. */
export interface NavigationRailItemSelectedEvent {
  index: number;
  label?: string;
  icon?: Icon;
}

const DEFAULT_MENU: { closed: NavigationRailMenuState; opened: NavigationRailMenuState } = {
  closed: { icon: iMenu, label: 'Open menu' },
  opened: { icon: iClose, label: 'Close menu' },
};

/**
 * Navigation rails let people switch between UI views on mid-sized devices.
 * @status beta
 * @category Navigation
 * @devx
 * - Project `udx-navigation-rail-item`, `udx-navigation-rail-section`, and
 *   a `udx-fab` as children; the FAB is hoisted into the header.
 * - `footer` content is projected via `<div footer>`/an element with a
 *   `footer` attribute, pinned below the item list.
 * - Selection is index-based; use `selectedItem`/`selectedItemChange` for
 *   controlled usage, or `defaultSelectedItem` uncontrolled.
 * @a11y
 * - The menu toggle button exposes its open/closed label via `menu.opened`/
 *   `menu.closed`.
 * @limitations
 * - Keyboard navigation/roving tabindex is not implemented.
 * - Angular's `selectedItem`/`selectedItemChange` follow this repository's
 *   output-naming convention; React instead exposes a raw
 *   `setSelectedItem` dispatcher (an intentional platform difference, not a
 *   parity gap).
 */
@Component({
  selector: 'udx-navigation-rail',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconButton],
  providers: [
    {
      provide: NAVIGATION_RAIL_CONTEXT,
      useExisting: forwardRef(() => NavigationRail),
    },
  ],
  host: { style: 'display: contents' },
  template: `
    <div [class]="styles()['navigationRail']" style="transition: 0.3s">
      <div [class]="styles()['header']">
        <udx-icon-button
          [label]="isExtended() ? menu().opened.label : menu().closed.label"
          [icon]="isExtended() ? menu().opened.icon : menu().closed.icon"
          [className]="styles()['menuIcon']"
          (click)="toggleExtended()"
        />
        <div class="mx-5 [&_.fab]:!shadow-none">
          <ng-content select="udx-fab" />
        </div>
      </div>

      <div [class]="styles()['segments']">
        <ng-content
          select="udx-navigation-rail-item, udx-navigation-rail-section"
        />
      </div>

      <div [class]="styles()['footer']">
        <ng-content select="[footer]" />
      </div>
    </div>
  `,
})
export class NavigationRail implements OnInit, NavigationRailContext {
  readonly variant = input<NavigationRailProps['variant']>('standard');
  readonly alignment = input<NavigationRailProps['alignment']>('top');
  readonly menu = input<{
    closed: NavigationRailMenuState;
    opened: NavigationRailMenuState;
  }>(DEFAULT_MENU);
  /** Controlled extended state of the rail. */
  readonly extended = input<boolean>();
  /** Initial extended state when uncontrolled. */
  readonly defaultExtended = input(false);
  /** Controlled index of the selected item. */
  readonly selectedItem = input<number | null>();
  /** Initial selected index when uncontrolled. */
  readonly defaultSelectedItem = input<number | null>(null);
  readonly className = input<
    string | ClassNameComponent<NavigationRailInterface>
  >();

  /** Emits each accepted extended-state request and supports `[(extended)]`. */
  readonly extendedChange = output<boolean>();
  /** Emits each accepted selection request and supports `[(selectedItem)]`. */
  readonly selectedItemChange = output<number | null>();
  /** Emits once whenever the resolved selection settles on a given item. */
  readonly itemSelected = output<NavigationRailItemSelectedEvent>();

  private readonly extendedState = createControllableState({
    value: this.extended,
    defaultValue: this.defaultExtended,
    onChange: (value) => this.extendedChange.emit(value),
    componentName: 'NavigationRail',
    stateName: 'extended',
  });
  readonly isExtended = this.extendedState.value;

  private readonly selectedItemState = createControllableState({
    value: this.selectedItem,
    defaultValue: this.defaultSelectedItem,
    onChange: (value) => this.selectedItemChange.emit(value),
    componentName: 'NavigationRail',
    stateName: 'selectedItem',
  });
  readonly selectedIndex = this.selectedItemState.value;

  private readonly items = contentChildren(NavigationRailItem);
  private readonly sections = contentChildren(NavigationRailSection);

  protected readonly styles = createStyle(navigationRailStyle, () => ({
    variant: this.variant(),
    alignment: this.alignment(),
    menu: this.menu(),
    selectedItem: this.selectedItem(),
    extended: this.extended(),
    defaultExtended: this.defaultExtended(),
    onExtendedChange: undefined,
    isExtended: this.isExtended(),
    selectedIndex: this.selectedIndex(),
    className: this.className(),
  }));

  private lastEmittedIndex: number | null = null;

  constructor() {
    afterRenderEffect(() => {
      const idx = this.selectedIndex();
      const items = this.items();
      if (idx == null || idx === this.lastEmittedIndex) return;
      const item = items[idx];
      if (!item) return;
      this.lastEmittedIndex = idx;
      this.itemSelected.emit({
        index: idx,
        label: item.label(),
        icon: item.icon(),
      });
    });
  }

  ngOnInit(): void {
    this.extendedState.initialize();
    this.selectedItemState.initialize();
  }

  protected toggleExtended(): void {
    this.extendedState.set(getNextNavigationRailExtended(this.isExtended()));
  }

  select(index: number): void {
    this.selectedItemState.set(index);
  }

  indexOf(item: object): number | undefined {
    const idx = this.items().indexOf(item as NavigationRailItem);
    return idx === -1 ? undefined : idx;
  }

  hasPrecedingSection(item: object): boolean {
    const itemEl = (item as NavigationRailItem).nativeElement;
    return this.sections().some((section) => {
      const position = section.nativeElement.compareDocumentPosition(itemEl);
      return (position & Node.DOCUMENT_POSITION_FOLLOWING) !== 0;
    });
  }
}

// packages/ui-react/src/lib/components/NavigationRail.tsx
import {
  Children,
  cloneElement,
  type Dispatch,
  Fragment,
  isValidElement,
  type ReactElement,
  type ReactNode,
  type SetStateAction,
  useRef,
  useState,
} from 'react';
import type { Transition } from 'motion';
import {
  getNextNavigationRailExtended,
  type NavigationRailInterface,
  navigationRailStyle,
  type ReactProps,
} from '@udixio/core';
import {
  NavigationRailItem,
  type NavigationRailItemSelectedEvent,
  type ReactNavigationRailItemProps,
} from './NavigationRailItem';
import { NavigationRailSection } from './NavigationRailSection';
import { Fab, type ReactFabProps } from './Fab';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';
import { iClose } from '@udixio/icons-rounded-400/close';
import { iMenu } from '@udixio/icons-rounded-400/menu';
import { IconButton } from './IconButton';

export type ReactNavigationRailProps = ReactProps<NavigationRailInterface> & {
  children?: ReactNode;
  /** Content pinned below the item list (e.g. an account or sign-out action). */
  footer?: ReactNode;
  transition?: Transition;
  setSelectedItem?: Dispatch<SetStateAction<number | null>>;
  onItemSelected?: (args: NavigationRailItemSelectedEvent) => void;
};

export const useNavigationRailStyle = createUseStyle(navigationRailStyle);

/**
 * Navigation rails let people switch between UI views on mid-sized devices
 * @status beta
 * @category Navigation
 * @devx
 * - Treats `NavigationRailItem`, `NavigationRailSection`, and `Fab` specially.
 * - Selection is index-based; provide `selectedItem` for controlled usage.
 * - `footer` pins arbitrary content (e.g. a sign-out button) below the items,
 *   without needing to wrap the rail in a custom layout.
 * @a11y
 * - The menu toggle button exposes its open/closed label via `menu.opened`/
 *   `menu.closed`; there is no additional live region for the extended state.
 * @limitations
 * - Keyboard navigation/roving tabindex is not implemented.
 */
export const NavigationRail = ({
  variant = 'standard',
  onItemSelected,
  children,
  footer,
  className,
  selectedItem: externalSelectedItem,
  extended,
  defaultExtended,
  alignment = 'top',
  menu = {
    closed: {
      icon: iMenu,
      label: 'Open menu',
    },
    opened: {
      icon: iClose,
      label: 'Close menu',
    },
  },
  style,
  onExtendedChange,
  transition,
  setSelectedItem: externalSetSelectedItem,
}: ReactNavigationRailProps) => {
  const [internalSelectedItem, internalSetSelectedItem] = useState<
    number | null
  >(null);

  const [isExtended, setIsExtended] = useControllableState({
    value: extended,
    defaultValue: defaultExtended ?? false,
    onChange: onExtendedChange,
    componentName: 'NavigationRail',
    stateName: 'extended',
  });

  let selectedIndex: number | null;
  if (externalSelectedItem == 0 || externalSelectedItem != undefined) {
    selectedIndex = externalSelectedItem;
  } else {
    selectedIndex = internalSelectedItem;
  }

  const setSelectedItem = externalSetSelectedItem || internalSetSelectedItem;

  const ref = useRef<HTMLDivElement | null>(null);

  const handleOnItemSelected = (args: NavigationRailItemSelectedEvent) => {
    onItemSelected?.(args);
  };

  function flattenChildren(children: ReactNode): ReactNode[] {
    const flatChildren: ReactNode[] = [];
    Children.forEach(children, (child) => {
      if (
        isValidElement<{ children?: ReactNode }>(child) &&
        child.type === Fragment
      ) {
        flatChildren.push(...flattenChildren(child.props.children));
      } else {
        flatChildren.push(child);
      }
    });
    return flatChildren;
  }

  const childrenArray = flattenChildren(children);

  const fab = childrenArray.filter(
    (child) => isValidElement(child) && child.type === Fab,
  );

  const styles = useNavigationRailStyle({
    variant,
    selectedItem: externalSelectedItem,
    extended,
    defaultExtended,
    onExtendedChange,
    alignment,
    menu,
    isExtended,
    selectedIndex,
    className,
  });
  transition = { duration: 0.3, ...transition };
  const extendedOnly = useRef(false);
  extendedOnly.current = false;

  return (
    <div
      style={{ transition: transition.duration + 's', ...style }}
      ref={ref}
      className={styles.navigationRail}
    >
      <div className={styles.header}>
        <IconButton
          onClick={() => setIsExtended(getNextNavigationRailExtended(isExtended))}
          label={isExtended ? menu?.opened.label : menu?.closed.label}
          className={styles.menuIcon}
          icon={!isExtended ? menu?.closed.icon : menu.opened.icon}
        />
        {fab.length > 0 &&
          cloneElement(fab[0] as ReactElement<ReactFabProps>, {
            extended: isExtended,
            className: '!shadow-none mx-5 ' + (fab[0] as any).props.className,
          })}
      </div>

      <div className={styles.segments}>
        {(() => {
          let itemIndex = 0;
          return childrenArray.map((child, arrIndex) => {
            if (isValidElement(child) && child.type === NavigationRailItem) {
              return cloneElement(
                child as ReactElement<ReactNavigationRailItemProps>,
                {
                  // The React key must be unique among ALL children of
                  // segments (items + sections): arrIndex always is, whereas
                  // itemIndex (a counter dedicated to items only) can collide
                  // with the arrIndex of a section placed earlier, causing an
                  // incorrect reconciliation (e.g. a NavigationRailSection's
                  // text duplicated after a click).
                  key: arrIndex,
                  index: itemIndex++, // Use and increment the dedicated counter
                  variant: isExtended ? 'horizontal' : 'vertical',
                  selectedItem: selectedIndex,
                  setSelectedItem: setSelectedItem,
                  onItemSelected: handleOnItemSelected,
                  transition,
                  extendedOnly: extendedOnly.current,
                  isExtended,
                },
              );
            }
            if (isValidElement(child) && child.type === Fab) {
              return null;
            }
            if (isValidElement(child) && child.type === NavigationRailSection) {
              extendedOnly.current = true;
              if (!isExtended) return null;
              return cloneElement(child as ReactElement<{ label: string }>, {
                key: arrIndex,
              });
            }
            return child;
          });
        })()}
      </div>
      <div className={styles.footer}>{footer}</div>
    </div>
  );
};
