// packages/ui-svelte/src/lib/snackbar/Snackbar.svelte
<script lang="ts">
  import { iClose } from '@udixio/icons-rounded-400/close';
  import { mergeClassNames, snackbarStyle, type SnackbarInterface } from '@udixio/core';
  import { createSnackbarAutoDismissController, createSnackbarTransitionController, type SnackbarTransitionController } from '@udixio/core/dom';
  import { untrack } from 'svelte';
  import IconButton from '../icon-button/IconButton.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteSnackbarProps } from './snackbar.types';

  let {
    message,
    open = $bindable(),
    defaultOpen = true,
    onOpenChange,
    duration,
    closeIcon = iClose,
    transition,
    class: hostClass = '',
    style: hostStyle,
    classes,
    ...rest
  }: SvelteSnackbarProps = $props();

  let panel: HTMLDivElement | undefined = $state();
  let transitionController: SnackbarTransitionController | undefined;
  const openState = createControllableState({
    value: () => open,
    defaultValue: () => defaultOpen,
    onChange: (next) => onOpenChange?.(next),
    assign: (next) => (open = next),
    componentName: 'Snackbar',
    stateName: 'open',
  });
  const isOpen = $derived(openState.current);
  const styles = createStyle(snackbarStyle, () => ({
    message,
    open,
    defaultOpen,
    duration,
    closeIcon,
    transition,
    isOpen,
    className: mergeClassNames<SnackbarInterface>('snackbar', classes, hostClass),
  }));

  $effect(() => {
    if (!panel) return;
    const created = createSnackbarTransitionController({ panel, open: untrack(() => isOpen), transition: untrack(() => transition) });
    transitionController = created;
    return () => {
      created.destroy();
      if (transitionController === created) transitionController = undefined;
    };
  });
  $effect(() => { transitionController?.setOpen(isOpen); });
  $effect(() => {
    if (!isOpen || !duration) return;
    const controller = createSnackbarAutoDismissController({ duration, onDismiss: () => openState.set(false) });
    return () => controller.destroy();
  });
  $effect(() => () => transitionController?.destroy());
</script>

<div
  {...rest}
  bind:this={panel}
  class={styles.current['snackbar']}
  style={hostStyle}
  role="status"
  aria-live="polite"
  aria-hidden={!isOpen}
  inert={!isOpen}
>
  <div class={styles.current['container']}>
    <p class={styles.current['supportingText']}>{message}</p>
    <IconButton label="Close the snackbar" icon={closeIcon} class={styles.current['icon']} onclick={() => openState.set(false)} />
  </div>
</div>

// packages/ui-react/src/lib/components/Snackbar.tsx
import { useEffect, useRef } from 'react';
import { iClose } from '@udixio/icons-rounded-400/close';
import {
  type ReactProps,
  type SnackbarInterface,
  snackbarStyle,
} from '@udixio/core';
import {
  createSnackbarAutoDismissController,
  createSnackbarTransitionController,
  type SnackbarTransitionController,
} from '@udixio/core/dom';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';
import { IconButton } from './IconButton';

export type ReactSnackbarProps = ReactProps<SnackbarInterface> & {
  /** Notifies an accepted open-state request. */
  onOpenChange?: (open: boolean) => void;
};

export const useSnackbarStyle = createUseStyle(snackbarStyle);

/**
 * Snackbars show a brief, non-blocking status message about an app process.
 * @status beta
 * @category Communication
 * @devx
 * - `open` is controlled; `defaultOpen` initializes uncontrolled usage. Defaults to `true`.
 * - `duration` (ms) auto-dismisses the snackbar; omit it to require an explicit `onOpenChange`
 *   or a click on the built-in close button.
 * - Renders in normal document flow at the call site. Fixed/bottom positioning, stacking, and
 *   queueing multiple snackbars are the caller's responsibility.
 * - The height transition is implemented once with Motion JavaScript in `@udixio/core/dom`,
 *   shared with Angular. It applies the initial `open` state immediately; only transitions
 *   after the first render animate.
 * @a11y
 * - Renders `role="status"` and `aria-live="polite"` so assistive technology announces the
 *   message without interrupting the user. The element stays mounted and `inert` while closed
 *   instead of unmounting, so the live region is reliably present before it announces.
 * @limitations
 * - No built-in queue/stacking for multiple simultaneous snackbars.
 */
export const Snackbar = ({
  message,
  className,
  duration,
  closeIcon = iClose,
  open: openProp,
  defaultOpen = true,
  onOpenChange,
  transition,
  style,
  ...restProps
}: ReactSnackbarProps) => {
  const [isOpen, setOpen] = useControllableState({
    value: openProp,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
    componentName: 'Snackbar',
    stateName: 'open',
  });

  const styles = useSnackbarStyle({
    className,
    closeIcon,
    duration,
    open: openProp,
    defaultOpen,
    isOpen,
    message,
    transition,
  });

  const panelRef = useRef<HTMLDivElement>(null);
  const controllerRef = useRef<SnackbarTransitionController | null>(null);

  useEffect(() => {
    if (!panelRef.current) return;
    const controller = createSnackbarTransitionController({
      panel: panelRef.current,
      open: isOpen,
      transition,
    });
    controllerRef.current = controller;
    return () => {
      controller.destroy();
      controllerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    controllerRef.current?.setOpen(isOpen);
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen || !duration) return;
    const controller = createSnackbarAutoDismissController({
      duration,
      onDismiss: () => setOpen(false),
    });
    return () => controller.destroy();
  }, [isOpen, duration, setOpen]);

  return (
    <div
      {...restProps}
      ref={panelRef}
      style={{ ...style, height: isOpen ? undefined : 0 }}
      className={styles.snackbar}
      role="status"
      aria-live="polite"
      aria-hidden={!isOpen}
      inert={!isOpen}
    >
      <div className={styles.container}>
        <p className={styles.supportingText}>{message}</p>
        <IconButton
          onClick={() => setOpen(false)}
          className={styles.icon}
          icon={closeIcon}
          label="Close the snackbar"
        />
      </div>
    </div>
  );
};
