// packages/ui-angular/src/lib/tabs/tab-group.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  forwardRef,
  input,
  output,
  type OnInit,
} from '@angular/core';
import { createControllableState } from '../utils/create-controllable-state';
import { TAB_GROUP_CONTEXT, type TabGroupContext } from './tab-group-context';

/**
 * TabGroup shares selection state between a `udx-tabs` tablist and a
 * `udx-tab-panels` placed anywhere in its subtree.
 * @status beta
 * @parent Tabs
 * @category Navigation
 * @devx
 * - Project `udx-tabs` and `udx-tab-panels`; wrap them in a `udx-tab-group`
 *   to connect them. `udx-tabs` alone (no group) is enough for a
 *   navigation-only tab list with no panels.
 * - Use `selectedTab`/`selectedTabChange` for controlled selection, or
 *   `defaultSelectedTab` (defaults to `0`) when uncontrolled.
 * @a11y
 * - Renders `display: contents` and no ARIA role itself; the `tablist`/
 *   `tab`/`tabpanel` roles live on the connected `udx-tabs`/`udx-tab`/
 *   `udx-tab-panel`.
 * @limitations
 * - No URL/hash syncing or persistence built in.
 */
@Component({
  selector: 'udx-tab-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    { provide: TAB_GROUP_CONTEXT, useExisting: forwardRef(() => TabGroup) },
  ],
  host: { style: 'display: contents' },
  template: `<ng-content />`,
})
export class TabGroup implements OnInit, TabGroupContext {
  private static nextId = 0;

  /** Controlled index of the selected tab. */
  readonly selectedTab = input<number | null>();
  /** Index selected on mount when the group is uncontrolled. */
  readonly defaultSelectedTab = input<number | null>(0);
  /** Emits each accepted selection request and supports `[(selectedTab)]`. */
  readonly selectedTabChange = output<number | null>();

  private readonly tabsIdValue = `tab-group-${TabGroup.nextId++}`;
  readonly tabsId = computed(() => this.tabsIdValue);

  private readonly selectedTabState = createControllableState({
    value: this.selectedTab,
    defaultValue: this.defaultSelectedTab,
    onChange: (value) => this.selectedTabChange.emit(value),
    componentName: 'TabGroup',
    stateName: 'selectedTab',
  });
  readonly selectedIndex = this.selectedTabState.value;

  private previousSelected: number | null = null;

  readonly direction = computed(() => {
    const current = this.selectedIndex();
    const previous = this.previousSelected;
    const nextDirection =
      previous !== null && current !== null
        ? current > previous
          ? 1
          : -1
        : 0;
    this.previousSelected = current;
    return nextDirection;
  });

  ngOnInit(): void {
    this.selectedTabState.initialize();
  }

  select(index: number | null): void {
    this.selectedTabState.set(index);
  }
}

// packages/ui-react/src/lib/components/TabGroup.tsx
import { type ReactNode, useId, useMemo, useRef } from 'react';
import type { ReactProps, TabGroupInterface } from '@udixio/core';
import { useControllableState } from '../utils/use-controllable-state';
import { TabGroupContext, type TabGroupContextValue } from './TabGroupContext';

export type ReactTabGroupProps = ReactProps<TabGroupInterface> & {
  children?: ReactNode;
  onSelectedTabChange?: (index: number | null) => void;
};

/**
 * TabGroup shares selection state between a `Tabs` tablist and a `TabPanels`
 * placed anywhere in its subtree.
 * @status beta
 * @parent Tabs
 * @category Navigation
 * @devx
 * - Wrap `Tabs` and `TabPanels` in a `TabGroup` to connect them; `Tabs` alone
 *   (no `TabGroup`) is enough for a navigation-only tab list with no panels.
 * - Use `selectedTab`/`onSelectedTabChange` for controlled selection, or
 *   `defaultSelectedTab` (defaults to `0`) when uncontrolled.
 * @a11y
 * - Renders no DOM element and no ARIA role itself; the `tablist`/`tab`/
 *   `tabpanel` roles live on the connected `Tabs`/`Tab`/`TabPanel`.
 * @limitations
 * - No URL/hash syncing or persistence built in.
 */
export const TabGroup = ({
  children,
  selectedTab,
  defaultSelectedTab = 0,
  onSelectedTabChange,
}: ReactTabGroupProps) => {
  const [resolvedSelectedTab, setSelectedTab] = useControllableState({
    value: selectedTab,
    defaultValue: defaultSelectedTab,
    onChange: onSelectedTabChange,
    componentName: 'TabGroup',
    stateName: 'selectedTab',
  });

  // Tracks the previous selection (mutated during render, not in an effect)
  // so the very next render already knows the slide direction -- an effect
  // would only learn it a frame late, after TabPanels already animated.
  const previousTabRef = useRef<number | null>(null);
  const direction =
    previousTabRef.current !== null && resolvedSelectedTab !== null
      ? resolvedSelectedTab > previousTabRef.current
        ? 1
        : -1
      : 0;
  if (resolvedSelectedTab !== previousTabRef.current) {
    previousTabRef.current = resolvedSelectedTab;
  }

  const tabsId = useId();

  const contextValue: TabGroupContextValue = useMemo(
    () => ({
      selectedTab: resolvedSelectedTab,
      direction,
      tabsId,
      select: setSelectedTab,
    }),
    [resolvedSelectedTab, direction, tabsId, setSelectedTab],
  );

  return (
    <TabGroupContext.Provider value={contextValue}>
      {children}
    </TabGroupContext.Provider>
  );
};
