// packages/ui-angular/src/lib/progress-indicator/progress-indicator.ts
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  input,
  signal,
  viewChild,
} from '@angular/core';
import {
  clampProgressValue,
  isDeterminateVariant,
  progressIndicatorStyle,
  type ClassNameComponent,
  type ProgressIndicatorInterface,
  type ProgressIndicatorVariant,
} from '@udixio/core';
import {
  createCircularProgressController,
  createLinearIndeterminateController,
  createProgressVisibilityController,
} from '@udixio/core/dom';
import { createStyle } from '../utils/create-style';

/**
 * Progress indicators express an unspecified wait time or display the length
 * of a process.
 *
 * @status beta
 * @category Communication
 * @devx
 * - `value` is clamped to 0–100; indeterminate variants ignore it.
 * @a11y
 * - Renders `role="progressbar"` with `aria-valuemin`/`aria-valuemax`; determinate
 *   variants also expose `aria-valuenow`.
 * - Provide `aria-label`/`aria-labelledby`; this component does not infer an
 *   accessible name.
 * @limitations
 * - Visibility auto-hides at 100% (no controlled open prop).
 */
@Component({
  selector: 'udx-progress-indicator',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @switch (variant()) {
      @case ('linear-indeterminate') {
        <div
          [class]="styles()['progressIndicator']"
          role="progressbar"
          [attr.aria-valuemin]="0"
          [attr.aria-valuemax]="100"
          [attr.aria-label]="ariaLabel()"
          [attr.aria-labelledby]="ariaLabelledBy()"
        >
          <div
            #leadingBar
            style="flex-shrink: 0"
            [class]="styles()['activeIndicator']"
          ></div>
          <div
            #gapTrack
            style="flex-shrink: 0"
            [class]="styles()['firstTrack']"
          ></div>
          <div
            #trailingBar
            style="flex-shrink: 0; margin-left: 6px"
            [class]="styles()['activeIndicator']"
          ></div>
          <div style="margin-left: 6px" [class]="styles()['lastTrack']"></div>
        </div>
      }
      @case ('linear-determinate') {
        <div
          [class]="styles()['progressIndicator']"
          role="progressbar"
          [attr.aria-valuemin]="0"
          [attr.aria-valuemax]="100"
          [attr.aria-valuenow]="ariaValueNow()"
          [attr.aria-label]="ariaLabel()"
          [attr.aria-labelledby]="ariaLabelledBy()"
        >
          <div
            [style.width.%]="completedPercentage()"
            [style.transition]="activeIndicatorTransition()"
            [class]="styles()['activeIndicator']"
          ></div>
          <div
            [style.marginLeft]="lastTrackMarginLeft()"
            [style.transition]="lastTrackTransition()"
            [class]="styles()['lastTrack']"
          ></div>
          <div
            style="width: 4px"
            [style.transition]="stopTransition()"
            [class]="styles()['stop']"
          ></div>
        </div>
      }
      @case ('circular-indeterminate') {
        <svg
          #indeterminateSvg
          width="48"
          height="48"
          viewBox="0 0 48 48"
          [class]="styles()['progressIndicator']"
          role="progressbar"
          [attr.aria-valuemin]="0"
          [attr.aria-valuemax]="100"
          [attr.aria-label]="ariaLabel()"
          [attr.aria-labelledby]="ariaLabelledBy()"
        >
          <circle
            #indeterminateCircle
            cx="50%"
            cy="50%"
            r="calc(50% - 2px)"
            style="stroke-linecap: round"
            [class]="styles()['activeIndicator']"
          />
        </svg>
      }
      @case ('circular-determinate') {
        <svg
          width="48"
          height="48"
          viewBox="0 0 48 48"
          style="transform: rotate(-90deg)"
          [class]="styles()['progressIndicator']"
          role="progressbar"
          [attr.aria-valuemin]="0"
          [attr.aria-valuemax]="100"
          [attr.aria-valuenow]="ariaValueNow()"
          [attr.aria-label]="ariaLabel()"
          [attr.aria-labelledby]="ariaLabelledBy()"
        >
          <circle
            cx="50%"
            cy="50%"
            [attr.r]="circularRadius()"
            style="stroke-linecap: round"
            [style.stroke-dasharray]="circumference()"
            [style.stroke-dashoffset]="strokeDashoffset()"
            [style.transition]="
              'stroke-dashoffset ' + transitionDuration() + 'ms ease-in-out'
            "
            [class]="styles()['activeIndicator']"
          />
        </svg>
      }
    }
  `,
})
export class ProgressIndicator {
  readonly variant = input<ProgressIndicatorVariant>('linear-determinate');
  readonly value = input<number>(0);
  readonly transitionDuration = input<number>(1000);
  readonly minHeight = input<number>();
  readonly className = input<
    string | ClassNameComponent<ProgressIndicatorInterface>
  >();
  /** Accessible-name override; this component does not infer one. */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: 'aria-label',
  });
  /** Id reference for text that names the indicator. */
  readonly ariaLabelledBy = input<string | undefined>(undefined, {
    alias: 'aria-labelledby',
  });

  private readonly indeterminateSvg =
    viewChild<ElementRef<SVGSVGElement>>('indeterminateSvg');
  private readonly indeterminateCircle = viewChild<
    ElementRef<SVGCircleElement>
  >('indeterminateCircle');
  private readonly leadingBar =
    viewChild<ElementRef<HTMLDivElement>>('leadingBar');
  private readonly gapTrack = viewChild<ElementRef<HTMLDivElement>>('gapTrack');
  private readonly trailingBar =
    viewChild<ElementRef<HTMLDivElement>>('trailingBar');

  protected readonly completedPercentage = computed(() =>
    clampProgressValue(this.value()),
  );
  protected readonly isVisible = signal(this.completedPercentage() < 100);
  protected readonly ariaValueNow = computed(() =>
    isDeterminateVariant(this.variant()) ? this.completedPercentage() : null,
  );
  protected readonly circularRadius = computed(() =>
    this.isVisible() ? 22 : 24,
  );
  protected readonly circumference = computed(
    () => 2 * Math.PI * this.circularRadius(),
  );
  protected readonly strokeDashoffset = computed(
    () => this.circumference() * (1 - this.completedPercentage() / 100),
  );
  protected readonly activeIndicatorTransition = computed(
    () =>
      `width ${this.transitionDuration()}ms ease-in-out${
        this.completedPercentage() === 100
          ? ', max-height 200ms 0.5s ease-in-out'
          : ''
      }`,
  );
  protected readonly lastTrackMarginLeft = computed(() =>
    this.completedPercentage() !== 100 ? '6px' : '0px',
  );
  protected readonly lastTrackTransition = computed(() => {
    const duration = this.transitionDuration();
    return `width ${duration}ms ease-in-out${
      this.completedPercentage() === 100
        ? `, max-height 200ms 0.5s ease-in-out, margin-left ${duration}ms ${duration / 1.5}ms`
        : ''
    }`;
  });
  protected readonly stopTransition = computed(
    () =>
      `width ${this.transitionDuration()}ms ease-in-out, max-height 200ms 0.5s ease-in-out`,
  );

  protected readonly styles = createStyle(progressIndicatorStyle, () => ({
    className: this.className(),
    variant: this.variant(),
    value: this.value(),
    transitionDuration: this.transitionDuration(),
    minHeight: this.minHeight(),
    isVisible: this.isVisible(),
  }));

  constructor() {
    afterRenderEffect((onCleanup) => {
      onCleanup(
        createProgressVisibilityController({
          completedPercentage: this.completedPercentage(),
          transitionDuration: this.transitionDuration(),
          onVisibilityChange: (isVisible) => this.isVisible.set(isVisible),
        }),
      );
    });

    afterRenderEffect((onCleanup) => {
      if (this.variant() !== 'circular-indeterminate') return;
      const svg = this.indeterminateSvg()?.nativeElement;
      const circle = this.indeterminateCircle()?.nativeElement;
      if (!svg || !circle) return;

      onCleanup(createCircularProgressController({ svg, circle }));
    });

    afterRenderEffect((onCleanup) => {
      if (this.variant() !== 'linear-indeterminate') return;
      const leadingBar = this.leadingBar()?.nativeElement;
      const gapTrack = this.gapTrack()?.nativeElement;
      const trailingBar = this.trailingBar()?.nativeElement;
      if (!leadingBar || !gapTrack || !trailingBar) return;

      onCleanup(
        createLinearIndeterminateController({
          leadingBar,
          gapTrack,
          trailingBar,
        }),
      );
    });
  }
}

// packages/ui-svelte/src/lib/progress-indicator/ProgressIndicator.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import {
    clampProgressValue,
    isDeterminateVariant,
    mergeClassNames,
    progressIndicatorStyle,
    type ProgressIndicatorInterface,
  } from '@udixio/core';
  import {
    createCircularProgressController,
    createLinearIndeterminateController,
    createProgressVisibilityController,
  } from '@udixio/core/dom';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteProgressIndicatorProps } from './progress-indicator.types';

  let {
    variant = 'linear-determinate',
    value = 0,
    transitionDuration = 1000,
    minHeight,
    class: hostClass = '',
    classes,
    ...rest
  }: SvelteProgressIndicatorProps = $props();

  const completedPercentage = $derived(clampProgressValue(value));
  // Seeded once; the visibility controller owns every later change.
  let isVisible = $state(untrack(() => clampProgressValue(value) < 100));

  let indeterminateSvg: SVGSVGElement | undefined = $state();
  let indeterminateCircle: SVGCircleElement | undefined = $state();
  let leadingBar: HTMLDivElement | undefined = $state();
  let gapTrack: HTMLDivElement | undefined = $state();
  let trailingBar: HTMLDivElement | undefined = $state();

  const ariaValueNow = $derived(isDeterminateVariant(variant) ? completedPercentage : undefined);
  const circularRadius = $derived(isVisible ? 22 : 24);
  const circumference = $derived(2 * Math.PI * circularRadius);
  const strokeDashoffset = $derived(circumference * (1 - completedPercentage / 100));
  const activeIndicatorTransition = $derived(
    `width ${transitionDuration}ms ease-in-out${
      completedPercentage === 100 ? ', max-height 200ms 0.5s ease-in-out' : ''
    }`,
  );
  const lastTrackMarginLeft = $derived(completedPercentage !== 100 ? '6px' : '0px');
  const lastTrackTransition = $derived(
    `width ${transitionDuration}ms ease-in-out${
      completedPercentage === 100
        ? `, max-height 200ms 0.5s ease-in-out, margin-left ${transitionDuration}ms ${transitionDuration / 1.5}ms`
        : ''
    }`,
  );
  const stopTransition = $derived(
    `width ${transitionDuration}ms ease-in-out, max-height 200ms 0.5s ease-in-out`,
  );

  const styles = createStyle(progressIndicatorStyle, () => ({
    className: mergeClassNames<ProgressIndicatorInterface>('progressIndicator', classes, hostClass),
    variant,
    value,
    transitionDuration,
    minHeight,
    isVisible,
  }));

  $effect(() =>
    createProgressVisibilityController({
      completedPercentage,
      transitionDuration,
      onVisibilityChange: (visible) => (isVisible = visible),
    }),
  );

  $effect(() => {
    if (variant !== 'circular-indeterminate' || !indeterminateSvg || !indeterminateCircle) return;
    return createCircularProgressController({ svg: indeterminateSvg, circle: indeterminateCircle });
  });

  $effect(() => {
    if (variant !== 'linear-indeterminate' || !leadingBar || !gapTrack || !trailingBar) return;
    return createLinearIndeterminateController({ leadingBar, gapTrack, trailingBar });
  });
</script>

{#if variant === 'linear-indeterminate'}
  <div
    {...rest}
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
  >
    <div bind:this={leadingBar} style:flex-shrink={0} class={styles.current['activeIndicator']}></div>
    <div bind:this={gapTrack} style:flex-shrink={0} class={styles.current['firstTrack']}></div>
    <div
      bind:this={trailingBar}
      style:flex-shrink={0}
      style:margin-left="6px"
      class={styles.current['activeIndicator']}
    ></div>
    <div style:margin-left="6px" class={styles.current['lastTrack']}></div>
  </div>
{:else if variant === 'linear-determinate'}
  <div
    {...rest}
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
    aria-valuenow={ariaValueNow}
  >
    <div
      style:width={`${completedPercentage}%`}
      style:transition={activeIndicatorTransition}
      class={styles.current['activeIndicator']}
    ></div>
    <div
      style:margin-left={lastTrackMarginLeft}
      style:transition={lastTrackTransition}
      class={styles.current['lastTrack']}
    ></div>
    <div style:width="4px" style:transition={stopTransition} class={styles.current['stop']}></div>
  </div>
{:else if variant === 'circular-indeterminate'}
  <svg
    {...rest}
    bind:this={indeterminateSvg}
    width="48"
    height="48"
    viewBox="0 0 48 48"
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
  >
    <circle
      bind:this={indeterminateCircle}
      cx="50%"
      cy="50%"
      r="calc(50% - 2px)"
      style:stroke-linecap="round"
      class={styles.current['activeIndicator']}
    />
  </svg>
{:else}
  <svg
    {...rest}
    width="48"
    height="48"
    viewBox="0 0 48 48"
    style:transform="rotate(-90deg)"
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
    aria-valuenow={ariaValueNow}
  >
    <circle
      cx="50%"
      cy="50%"
      r={circularRadius}
      style:stroke-linecap="round"
      style:stroke-dasharray={circumference}
      style:stroke-dashoffset={strokeDashoffset}
      style:transition={`stroke-dashoffset ${transitionDuration}ms ease-in-out`}
      class={styles.current['activeIndicator']}
    />
  </svg>
{/if}
