// src/components/ProgressIndicator.tsx
import React, { useEffect, useState } from 'react';
import { ProgressIndicatorInterface } from '../interfaces/progress-indicator.interface';

import { motion } from 'motion/react';
import { progressIndicatorStyle } from '../styles/progress-indicator.style';
import { ReactProps } from '../utils/component';

export const ProgressIndicator = ({
  variant = 'linear-determinate',
  minHeight = 4,
  value = 0,
  transitionDuration = 1000,
  className,
  ...restProps
}: ReactProps<ProgressIndicatorInterface>): any => {
  const [completedPercentage, setCompletedPercentage] = useState(value);

  const [transitionRotate, setTransitionRotate] = useState(1.5);

  useEffect(() => {
    if (value > 100) {
      value = 100;
    }
    if (value < 0) {
      value = 0;
    }
    setCompletedPercentage(value);
  }, [value]);

  const [togglePercentage, setTogglePercentage] = useState(true);

  const getTransitionRotate = () => {
    return togglePercentage ? transitionRotate : transitionRotate * 0.5;
  };

  useEffect(() => {
    if (
      (variant === 'circular-indeterminate' ||
        variant === 'linear-indeterminate') &&
      completedPercentage !== 100
    ) {
      const interval = setInterval(() => {
        setCompletedPercentage(togglePercentage ? 10 : 90);
        setTogglePercentage(!togglePercentage);
      }, getTransitionRotate() * 1000);
      return () => clearInterval(interval);
    }
  }, [variant, togglePercentage, completedPercentage]);

  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    if (completedPercentage >= 100) {
      const timeoutId = setTimeout(() => {
        setIsVisible(false);
      }, transitionDuration);
      return () => {
        clearTimeout(timeoutId);
      };
    } else {
      setIsVisible(true);
    }
  }, [completedPercentage, transitionDuration]);

  const styles = progressIndicatorStyle({
    className,
    variant,
    value,
    transitionDuration,
    isVisible,
    minHeight,
  });

  return (
    <>
      {(variant === 'linear-determinate' ||
        variant == 'linear-indeterminate') && (
        <div
          style={{ height: `${minHeight}px` }}
          className={styles.progressIndicator}
          {...restProps}
        >
          <div
            style={{
              height: !isVisible ? '0px' : `${minHeight}px`,
              width: `${completedPercentage}%`,
              transition: `width ${1}ms ease-in-out ${completedPercentage == 100 ? ', height 200ms 0.5s ease-in-out' : ''}`,
            }}
            className={styles.track}
          ></div>
          <div
            style={{
              height: !isVisible ? '0px' : `${minHeight}px`,
              marginLeft: completedPercentage != 100 ? '6px' : '0px',
              transition: `width ${transitionDuration}ms ease-in-out ${completedPercentage == 100 ? `, height 200ms 0.5s ease-in-out, margin-left ${transitionDuration}ms ${transitionDuration / 1.5}ms` : ''}`,
            }}
            className={styles.activeIndicator}
          ></div>
          <div
            style={{
              height: !isVisible ? '0px' : `${minHeight}px`,
              width: `${minHeight}px`,
              transition: `width ${transitionDuration}ms ease-in-out, height 200ms 0.5s ease-in-out`,
            }}
            className={styles.stop}
          ></div>
        </div>
      )}
      {(variant === 'circular-determinate' ||
        variant == 'circular-indeterminate') && (
        <motion.svg
          key={togglePercentage + ''}
          width="48"
          height="48"
          viewBox="0 0 48 48"
          initial={{ rotate: -90 }}
          animate={{ rotate: 270 }}
          transition={{
            repeat: Infinity,
            duration: getTransitionRotate(),
            ease: 'linear',
          }}
          className={styles.progressIndicator}
          {...(restProps as any)}
        >
          <motion.circle
            cx="50%"
            cy="50%"
            r={isVisible ? 'calc(50% - 2px)' : '50%'}
            style={{
              strokeLinecap: 'round',
            }}
            initial="hidden"
            animate="visible"
            className={styles.activeIndicator}
            variants={{
              hidden: {
                pathLength: togglePercentage ? 10 / 100 : 90 / 100,
              },
              visible: {
                pathLength: togglePercentage ? 90 / 100 : 10 / 100,
              },
            }}
            transition={{
              pathLength: {
                type: 'tween',
                ease: 'linear',
                duration: getTransitionRotate(),
                bounce: 0,
              },
            }}
          />
        </motion.svg>
      )}
    </>
  );
};

// packages/ui-svelte/src/lib/progress-indicator/ProgressIndicator.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import {
    clampProgressValue,
    isDeterminateVariant,
    mergeClassNames,
    progressIndicatorStyle,
    type ProgressIndicatorInterface,
  } from '@udixio/core';
  import {
    createCircularProgressController,
    createLinearIndeterminateController,
    createProgressVisibilityController,
  } from '@udixio/core/dom';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteProgressIndicatorProps } from './progress-indicator.types';

  let {
    variant = 'linear-determinate',
    value = 0,
    transitionDuration = 1000,
    minHeight,
    class: hostClass = '',
    classes,
    ...rest
  }: SvelteProgressIndicatorProps = $props();

  const completedPercentage = $derived(clampProgressValue(value));
  // Seeded once; the visibility controller owns every later change.
  let isVisible = $state(untrack(() => clampProgressValue(value) < 100));

  let indeterminateSvg: SVGSVGElement | undefined = $state();
  let indeterminateCircle: SVGCircleElement | undefined = $state();
  let leadingBar: HTMLDivElement | undefined = $state();
  let gapTrack: HTMLDivElement | undefined = $state();
  let trailingBar: HTMLDivElement | undefined = $state();

  const ariaValueNow = $derived(isDeterminateVariant(variant) ? completedPercentage : undefined);
  const circularRadius = $derived(isVisible ? 22 : 24);
  const circumference = $derived(2 * Math.PI * circularRadius);
  const strokeDashoffset = $derived(circumference * (1 - completedPercentage / 100));
  const activeIndicatorTransition = $derived(
    `width ${transitionDuration}ms ease-in-out${
      completedPercentage === 100 ? ', max-height 200ms 0.5s ease-in-out' : ''
    }`,
  );
  const lastTrackMarginLeft = $derived(completedPercentage !== 100 ? '6px' : '0px');
  const lastTrackTransition = $derived(
    `width ${transitionDuration}ms ease-in-out${
      completedPercentage === 100
        ? `, max-height 200ms 0.5s ease-in-out, margin-left ${transitionDuration}ms ${transitionDuration / 1.5}ms`
        : ''
    }`,
  );
  const stopTransition = $derived(
    `width ${transitionDuration}ms ease-in-out, max-height 200ms 0.5s ease-in-out`,
  );

  const styles = createStyle(progressIndicatorStyle, () => ({
    className: mergeClassNames<ProgressIndicatorInterface>('progressIndicator', classes, hostClass),
    variant,
    value,
    transitionDuration,
    minHeight,
    isVisible,
  }));

  $effect(() =>
    createProgressVisibilityController({
      completedPercentage,
      transitionDuration,
      onVisibilityChange: (visible) => (isVisible = visible),
    }),
  );

  $effect(() => {
    if (variant !== 'circular-indeterminate' || !indeterminateSvg || !indeterminateCircle) return;
    return createCircularProgressController({ svg: indeterminateSvg, circle: indeterminateCircle });
  });

  $effect(() => {
    if (variant !== 'linear-indeterminate' || !leadingBar || !gapTrack || !trailingBar) return;
    return createLinearIndeterminateController({ leadingBar, gapTrack, trailingBar });
  });
</script>

{#if variant === 'linear-indeterminate'}
  <div
    {...rest}
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
  >
    <div bind:this={leadingBar} style:flex-shrink={0} class={styles.current['activeIndicator']}></div>
    <div bind:this={gapTrack} style:flex-shrink={0} class={styles.current['firstTrack']}></div>
    <div
      bind:this={trailingBar}
      style:flex-shrink={0}
      style:margin-left="6px"
      class={styles.current['activeIndicator']}
    ></div>
    <div style:margin-left="6px" class={styles.current['lastTrack']}></div>
  </div>
{:else if variant === 'linear-determinate'}
  <div
    {...rest}
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
    aria-valuenow={ariaValueNow}
  >
    <div
      style:width={`${completedPercentage}%`}
      style:transition={activeIndicatorTransition}
      class={styles.current['activeIndicator']}
    ></div>
    <div
      style:margin-left={lastTrackMarginLeft}
      style:transition={lastTrackTransition}
      class={styles.current['lastTrack']}
    ></div>
    <div style:width="4px" style:transition={stopTransition} class={styles.current['stop']}></div>
  </div>
{:else if variant === 'circular-indeterminate'}
  <svg
    {...rest}
    bind:this={indeterminateSvg}
    width="48"
    height="48"
    viewBox="0 0 48 48"
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
  >
    <circle
      bind:this={indeterminateCircle}
      cx="50%"
      cy="50%"
      r="calc(50% - 2px)"
      style:stroke-linecap="round"
      class={styles.current['activeIndicator']}
    />
  </svg>
{:else}
  <svg
    {...rest}
    width="48"
    height="48"
    viewBox="0 0 48 48"
    style:transform="rotate(-90deg)"
    class={styles.current['progressIndicator']}
    role="progressbar"
    aria-valuemin={0}
    aria-valuemax={100}
    aria-valuenow={ariaValueNow}
  >
    <circle
      cx="50%"
      cy="50%"
      r={circularRadius}
      style:stroke-linecap="round"
      style:stroke-dasharray={circumference}
      style:stroke-dashoffset={strokeDashoffset}
      style:transition={`stroke-dashoffset ${transitionDuration}ms ease-in-out`}
      class={styles.current['activeIndicator']}
    />
  </svg>
{/if}
