// packages/ui-react/src/lib/components/Toolbar.tsx
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import {
  splitToolbarActions,
  toolbarStyle,
  type AnchorPosition,
  type ReactProps,
  type ToolbarAction,
  type ToolbarInterface,
  type ToolbarMoreProps,
} from '@udixio/core';
import { iMoreVert } from '@udixio/icons-rounded-400/more_vert';
import { createUseStyle } from '../utils/create-use-style';
import { AnchorPositioner } from './AnchorPositioner';
import { IconButton } from './IconButton';
import { Menu } from './Menu';
import { MenuItem } from './MenuItem';

export type ReactToolbarAction = ToolbarAction & {
  /** Runs when an action without an `href` is activated. */
  onClick?: () => void;
  /** Receives accepted toggle-state changes. */
  onToggle?: (pressed: boolean) => void;
};

export interface ReactToolbarMoreRenderProps {
  actions: readonly ReactToolbarAction[];
  label: string;
  icon: NonNullable<ToolbarMoreProps['icon']>;
  variant: NonNullable<ToolbarMoreProps['variant']>;
  size: NonNullable<ToolbarMoreProps['size']>;
  open: boolean;
  ariaHasPopup: 'menu';
  ariaExpanded: boolean;
  onClick: () => void;
}

export type ReactToolbarProps = Omit<
  ReactProps<ToolbarInterface>,
  'role' | 'actions'
> & {
  actions?: readonly ReactToolbarAction[];
  children?: ReactNode;
  /** Notifies consumers when the generated overflow menu opens or closes. */
  onMoreOpenChange?: (open: boolean) => void;
  /** Replaces the default overflow trigger while retaining the overflow menu. */
  renderMore?: (props: ReactToolbarMoreRenderProps) => ReactNode;
};

export const useToolbarStyle = createUseStyle(toolbarStyle);

/**
 * Toolbars group related actions in a docked or floating container.
 *
 * @status beta
 * @category Layout
 * @devx
 * - Compose `IconButton` children or pass `actions` for a data-driven action group.
 * - `maxVisible` moves the remaining actions into an automatic overflow menu;
 *   `responsive` derives the visible count from the toolbar width.
 * - `more` customizes the default overflow trigger and `renderMore` replaces its
 *   visual rendering while keeping the menu behavior.
 * - The generated overflow menu chooses above/below or left/right from the
 *   toolbar orientation and the trigger's viewport half; `morePosition` can
 *   force a placement.
 * - Descendant `IconButton` controls keep rounded press feedback in floating
 *   toolbars.
 * - Use `variant="floating"` for a compact surface and
 *   `orientation="vertical"` for a vertical action group.
 * @a11y
 * - Renders `role="toolbar"` and applies `aria-orientation="vertical"` for
 *   vertical layouts.
 * - The overflow trigger has an accessible label and the generated menu uses
 *   the labels from each action.
 * - Provide `accessibleLabel` or an `aria-labelledby` reference to name the
 *   toolbar; label each child control according to its own component API.
 * @limitations
 * - `actions` and `children` are alternative content modes; `actions` takes precedence.
 * - The toolbar does not implement roving focus or arrow-key navigation for its
 *   direct children. The overflow menu owns menu-item keyboard navigation.
 * - Composition children remain consumer-owned; use `IconButton size="small"`
 *   for the 48dp toolbar slots shown in the Material 3 design.
 */
export const Toolbar = (props: ReactToolbarProps) => {
  const {
    variant = 'docked',
    color = 'standard',
    orientation = 'horizontal',
    accessibleLabel,
    className,
    children,
    actions,
    onMoreOpenChange,
    maxVisible,
    responsive = false,
    itemWidth = 48,
    more,
    morePosition = 'auto',
    renderMore,
    ref,
    'aria-label': ariaLabel,
    'aria-orientation': ariaOrientation,
    ...restProps
  } = props;
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const [availableWidth, setAvailableWidth] = useState(
    Number.POSITIVE_INFINITY,
  );
  const [open, setOpen] = useState(false);
  const styles = useToolbarStyle({
    variant,
    color,
    orientation,
    accessibleLabel,
    actions,
    maxVisible,
    responsive,
    itemWidth,
    more,
    morePosition,
    isOverflowOpen: open,
    className,
  });

  useEffect(() => {
    if (!responsive || actions === undefined || !rootRef.current) return;
    const root = rootRef.current;
    if (typeof ResizeObserver === 'undefined') return;

    const observer = new ResizeObserver(([entry]) => {
      if (entry) setAvailableWidth(entry.contentRect.width);
    });
    observer.observe(root);
    return () => observer.disconnect();
  }, [actions, responsive, itemWidth]);

  const split = useMemo(
    () =>
      splitToolbarActions({
        actions: actions ?? [],
        maxVisible,
        responsive,
        availableWidth,
        itemWidth,
      }),
    [actions, availableWidth, itemWidth, maxVisible, responsive],
  );
  const visibleActions = split.visible as readonly ReactToolbarAction[];
  const overflowActions = split.overflow as readonly ReactToolbarAction[];
  const moreLabel = more?.label ?? 'More actions';
  const moreIcon = more?.icon ?? iMoreVert;
  const moreVariant = more?.variant ?? 'standard';
  const moreSize = more?.size ?? 'small';

  useEffect(() => {
    if (split.overflow.length === 0 && open) {
      setOpen(false);
      onMoreOpenChange?.(false);
    }
  }, [onMoreOpenChange, open, split.overflow.length]);

  useEffect(() => {
    if (!open) return;

    const onPointerDown = (event: MouseEvent) => {
      const target = event.target;
      if (!(target instanceof Node)) return;
      if (
        triggerRef.current?.contains(target) ||
        menuRef.current?.contains(target)
      ) {
        return;
      }
      setOpen(false);
      onMoreOpenChange?.(false);
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      setOpen(false);
      onMoreOpenChange?.(false);
      triggerRef.current?.querySelector<HTMLElement>('button, a')?.focus();
    };

    document.addEventListener('mousedown', onPointerDown);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onPointerDown);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [onMoreOpenChange, open]);

  const setRootRef = (node: HTMLDivElement | null) => {
    rootRef.current = node;
    if (typeof ref === 'function') ref(node);
    else if (ref) ref.current = node;
  };

  const runAction = (action: ReactToolbarAction) => {
    if (action.href === undefined) action.onClick?.();
  };

  const selectAction = (action: ReactToolbarAction) => {
    if (action.disabled) return;
    runAction(action);
    setOpen(false);
    onMoreOpenChange?.(false);
  };

  const toggleMore = () => {
    setOpen((current) => {
      const next = !current;
      onMoreOpenChange?.(next);
      return next;
    });
  };

  const actionButtons = visibleActions.map((action) => (
    <IconButton
      key={action.id}
      label={action.label}
      icon={action.icon}
      tooltip={action.tooltip}
      pressedIcon={action.pressedIcon}
      variant={action.variant}
      size={action.size ?? 'small'}
      width={action.width}
      disabled={action.disabled}
      shape={action.shape}
      shapeFeedback={action.shapeFeedback}
      transition={action.transition}
      toggleable={action.toggleable}
      pressed={action.pressed}
      defaultPressed={action.defaultPressed}
      href={action.href}
      onClick={() => runAction(action)}
      onPressedChange={action.onToggle}
    />
  ));

  const moreRenderProps: ReactToolbarMoreRenderProps = {
    actions: split.overflow,
    label: moreLabel,
    icon: moreIcon,
    variant: moreVariant,
    size: moreSize,
    open,
    ariaHasPopup: 'menu',
    ariaExpanded: open,
    onClick: toggleMore,
  };

  const moreTrigger = renderMore ? (
    renderMore(moreRenderProps)
  ) : (
    <IconButton
      label={moreLabel}
      icon={moreIcon}
      tooltip={false}
      variant={moreVariant}
      size={moreSize}
      aria-haspopup="menu"
      aria-expanded={open}
      onClick={toggleMore}
    />
  );

  return (
    <div
      {...restProps}
      ref={setRootRef}
      className={styles.toolbar}
      role="toolbar"
      data-udx-toolbar-variant={variant}
      data-udx-toolbar-orientation={orientation}
      aria-label={accessibleLabel ?? ariaLabel}
      aria-orientation={
        ariaOrientation ?? (orientation === 'vertical' ? 'vertical' : undefined)
      }
    >
      {actions === undefined ? children : actionButtons}
      {actions !== undefined && overflowActions.length > 0 && (
        <span ref={triggerRef} className="shrink-0">
          {moreTrigger}
        </span>
      )}
      {open && overflowActions.length > 0 && (
        <AnchorPositioner
          anchorRef={triggerRef}
          position={morePosition as AnchorPosition}
          autoAxis={orientation === 'vertical' ? 'horizontal' : 'vertical'}
        >
          <div ref={menuRef}>
            <Menu
              purpose="actions"
              accessibleLabel={moreLabel}
              initialFocus="first"
            >
              {overflowActions.map((action) => (
                <MenuItem
                  key={action.id}
                  label={action.label}
                  leadingIcon={action.icon}
                  href={action.href}
                  disabled={action.disabled}
                  onClick={() => selectAction(action)}
                />
              ))}
            </Menu>
          </div>
        </AnchorPositioner>
      )}
    </div>
  );
};

// packages/ui-angular/src/lib/toolbar/toolbar.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
  TemplateRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import {
  splitToolbarActions,
  type AnchorPosition,
  type ClassNameComponent,
  type ElementClasses,
  type Icon,
  type ToolbarAction,
  type ToolbarInterface,
  type ToolbarMoreProps,
  type ToolbarProps,
  toolbarStyle,
  mergeClassNames,
} from '@udixio/core';
import { iMoreVert } from '@udixio/icons-rounded-400/more_vert';
import { AnchorPositioner } from '../anchor-positioner/anchor-positioner';
import { IconButton } from '../icon-button/icon-button';
import { Menu } from '../menu/menu';
import { MenuItem } from '../menu/menu-item';
import { createStyle } from '../utils/create-style';

export interface AngularToolbarAction extends ToolbarAction {
  /** Runs when an action without an `href` is activated. */
  onClick?: () => void;
  /** Receives accepted toggle-state changes. */
  onToggle?: (pressed: boolean) => void;
}

export interface ToolbarMoreContext {
  $implicit: readonly AngularToolbarAction[];
  actions: readonly AngularToolbarAction[];
  label: string;
  icon: Icon;
  variant: NonNullable<ToolbarMoreProps['variant']>;
  size: NonNullable<ToolbarMoreProps['size']>;
  open: boolean;
  ariaHasPopup: 'menu';
  ariaExpanded: boolean;
  toggle: () => void;
}

/**
 * Toolbars group related actions in a docked or floating container.
 *
 * @status beta
 * @category Layout
 * @devx
 * - Compose `udx-icon-button` children or pass `actions` for a data-driven action group.
 * - `maxVisible` moves the remaining actions into an automatic overflow menu;
 *   `responsive` derives the visible count from the toolbar width.
 * - `more` customizes the default overflow trigger and `moreTemplate` replaces
 *   its visual rendering while keeping the menu behavior.
 * - The generated overflow menu chooses above/below or left/right from the
 *   toolbar orientation and the trigger's viewport half; `morePosition` can
 *   force a placement.
 * - Descendant `udx-icon-button` controls keep rounded press feedback in
 *   floating toolbars.
 * - Use `variant="floating"` for a compact surface and
 *   `orientation="vertical"` for a vertical action group.
 * @a11y
 * - Renders `role="toolbar"` and applies `aria-orientation="vertical"` for
 *   vertical layouts.
 * - The overflow trigger has an accessible label and the generated menu uses
 *   the labels from each action.
 * - Provide `accessibleLabel` or an `aria-labelledby` reference to name the
 *   toolbar; label each child control according to its own component API.
 * @limitations
 * - `actions` and projected children are alternative content modes; `actions`
 *   takes precedence.
 * - The toolbar does not implement roving focus or arrow-key navigation for its
 *   direct children. The overflow menu owns menu-item keyboard navigation.
 * - Composition children remain consumer-owned; use `size="small"` on
 *   `udx-icon-button` for the 48dp toolbar slots shown in Material 3.
 * - `[class.x]` and `[ngClass]` bind to the `display: contents` host and have
 *   no visible effect; use `class`, `[class]`, or `classes`.
 */
@Component({
  selector: 'udx-toolbar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display: contents',
    '(document:click)': 'onDocumentClick($event)',
    '(document:keydown.escape)': 'closeMore()',
  },
  imports: [AnchorPositioner, IconButton, Menu, MenuItem, NgTemplateOutlet],
  template: `
    <div
      #root
      [class]="styles()['toolbar']"
      role="toolbar"
      [attr.data-udx-toolbar-variant]="variant()"
      [attr.data-udx-toolbar-orientation]="orientation()"
      [attr.aria-label]="accessibleLabel() || null"
      [attr.aria-labelledby]="ariaLabelledBy() || null"
      [attr.aria-orientation]="ariaOrientation()"
    >
      @if (actions() !== undefined) {
        @for (action of visibleActions(); track action.id) {
          <udx-icon-button
            [label]="action.label"
            [icon]="action.icon"
            [tooltip]="action.tooltip"
            [pressedIcon]="action.pressedIcon"
            [variant]="action.variant"
            [size]="action.size ?? 'small'"
            [width]="action.width"
            [disabled]="action.disabled ?? false"
            [shape]="action.shape"
            [shapeFeedback]="action.shapeFeedback"
            [transition]="action.transition"
            [toggleable]="action.toggleable ?? false"
            [pressed]="action.pressed"
            [defaultPressed]="action.defaultPressed ?? false"
            [href]="action.href"
            (click)="runAction(action)"
            (pressedChange)="action.onToggle?.($event)"
          />
        }
        @if (overflowActions().length > 0) {
          <span #moreTrigger class="shrink-0">
            @if (moreTemplate(); as template) {
              <ng-container
                [ngTemplateOutlet]="template"
                [ngTemplateOutletContext]="moreContext()"
              />
            } @else {
              <udx-icon-button
                [label]="moreLabel()"
                [icon]="moreIcon()"
                [tooltip]="false"
                [variant]="moreVariant()"
                [size]="moreSize()"
                aria-haspopup="menu"
                [aria-expanded]="open()"
                (click)="toggleMore($event)"
              />
            }
          </span>
        }
      } @else {
        <ng-content />
      }
    </div>

    @if (open() && overflowActions().length > 0 && moreTrigger(); as trigger) {
      <udx-anchor-positioner
        [anchor]="trigger"
        [position]="morePosition()"
        [autoAxis]="orientation() === 'vertical' ? 'horizontal' : 'vertical'"
      >
        <udx-menu
          purpose="actions"
          [accessibleLabel]="moreLabel()"
          initialFocus="first"
          (click)="$event.stopPropagation()"
        >
          @for (action of overflowActions(); track action.id) {
            <udx-menu-item
              [label]="action.label"
              [leadingIcon]="action.icon"
              [href]="action.href"
              [disabled]="action.disabled ?? false"
              (click)="selectAction(action)"
            />
          }
        </udx-menu>
      </udx-anchor-positioner>
    }
  `,
})
export class Toolbar {
  readonly variant = input<ToolbarProps['variant']>('docked');
  readonly color = input<ToolbarProps['color']>('standard');
  readonly orientation = input<ToolbarProps['orientation']>('horizontal');
  readonly accessibleLabel = input<ToolbarProps['accessibleLabel']>();
  /** ID of an external element that labels the toolbar. */
  readonly ariaLabelledBy = input<string | undefined>(undefined, {
    alias: 'aria-labelledby',
  });

  /** Data-driven actions rendered as icon buttons with automatic overflow. */
  readonly actions = input<readonly AngularToolbarAction[]>();
  /** Maximum number of non-pinned actions shown in the toolbar. */
  readonly maxVisible = input<number>();
  /** Measures the toolbar and reserves one action slot for overflow when needed. */
  readonly responsive = input(false, { transform: booleanAttribute });
  /** Estimated width of one action slot when `responsive` is enabled. */
  readonly itemWidth = input(48);
  /** Presentation options for the default overflow trigger. */
  readonly more = input<ToolbarMoreProps>();
  /** Position of the generated overflow menu relative to the More trigger. */
  readonly morePosition = input<AnchorPosition>('auto');
  /** Template that replaces the default overflow trigger. */
  readonly moreTemplate = input<TemplateRef<ToolbarMoreContext>>();

  /** Classes applied to the root element. Angular's native `class` attribute and `[class]` binding land here, merged with the component's own classes. */
  readonly hostClass = input<string>('', { alias: 'class' });

  /** Static or state-aware classes for the component's internal elements, keyed by element name. */
  readonly classes = input<
    ElementClasses<ToolbarInterface> | ClassNameComponent<ToolbarInterface>
  >();

  readonly moreOpenChange = output<boolean>();

  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly moreTrigger =
    viewChild<ElementRef<HTMLElement>>('moreTrigger');
  private readonly availableWidth = signal(Number.POSITIVE_INFINITY);
  protected readonly open = signal(false);

  protected readonly ariaOrientation = computed(() =>
    this.orientation() === 'vertical' ? 'vertical' : null,
  );

  protected readonly split = computed(() =>
    splitToolbarActions({
      actions: this.actions() ?? [],
      maxVisible: this.maxVisible(),
      responsive: this.responsive(),
      availableWidth: this.availableWidth(),
      itemWidth: this.itemWidth(),
    }),
  );
  protected readonly visibleActions = computed(() => this.split().visible);
  protected readonly overflowActions = computed(() => this.split().overflow);
  protected readonly moreLabel = computed(
    () => this.more()?.label ?? 'More actions',
  );
  protected readonly moreIcon = computed(() => this.more()?.icon ?? iMoreVert);
  protected readonly moreVariant = computed(
    () => this.more()?.variant ?? 'standard',
  );
  protected readonly moreSize = computed(() => this.more()?.size ?? 'small');
  protected readonly moreContext = computed<ToolbarMoreContext>(() => ({
    $implicit: this.overflowActions(),
    actions: this.overflowActions(),
    label: this.moreLabel(),
    icon: this.moreIcon(),
    variant: this.moreVariant(),
    size: this.moreSize(),
    open: this.open(),
    ariaHasPopup: 'menu',
    ariaExpanded: this.open(),
    toggle: () => this.toggleMore(),
  }));

  constructor() {
    const zone = inject(NgZone);

    afterRenderEffect((onCleanup) => {
      const root = this.root()?.nativeElement;
      if (
        !root ||
        !this.responsive() ||
        typeof ResizeObserver === 'undefined'
      ) {
        return;
      }

      const observer = new ResizeObserver(([entry]) => {
        if (entry) this.availableWidth.set(entry.contentRect.width);
      });
      zone.runOutsideAngular(() => observer.observe(root));
      onCleanup(() => observer.disconnect());
    });

    afterRenderEffect(() => {
      if (this.overflowActions().length === 0) this.closeMore();
    });
  }

  protected toggleMore(event?: Event): void {
    event?.stopPropagation();
    if (this.overflowActions().length === 0) return;
    const next = !this.open();
    this.open.set(next);
    this.moreOpenChange.emit(next);
  }

  protected closeMore(): void {
    if (!this.open()) return;
    this.open.set(false);
    this.moreOpenChange.emit(false);
  }

  protected onDocumentClick(event: MouseEvent): void {
    if (!this.open()) return;
    const trigger = this.moreTrigger()?.nativeElement;
    const target = event.target;
    if (trigger && target instanceof Node && trigger.contains(target)) return;
    this.closeMore();
  }

  protected runAction(action: AngularToolbarAction): void {
    if (action.href === undefined) action.onClick?.();
  }

  protected selectAction(action: AngularToolbarAction): void {
    if (action.disabled) return;
    this.runAction(action);
    this.closeMore();
  }

  protected readonly styles = createStyle(toolbarStyle, () => ({
    variant: this.variant(),
    color: this.color(),
    orientation: this.orientation(),
    accessibleLabel: this.accessibleLabel(),
    actions: this.actions(),
    maxVisible: this.maxVisible(),
    responsive: this.responsive(),
    itemWidth: this.itemWidth(),
    more: this.more(),
    morePosition: this.morePosition(),
    isOverflowOpen: this.open(),
    className: mergeClassNames<ToolbarInterface>(
      'toolbar',
      this.classes(),
      this.hostClass(),
    ),
  }));
}
