// packages/ui-angular/src/lib/tabs/tab.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  booleanAttribute,
  computed,
  inject,
  input,
  viewChild,
} from '@angular/core';
import {
  resolveTabSelection,
  tabStyle,
  type ClassNameComponent,
  type ElementClasses,
  mergeClassNames,
  type Icon as IconType,
  type TabInterface,
  type TabsVariant,
} from '@udixio/core';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';
import { createStyle } from '../utils/create-style';
import { TABS_CONTEXT } from './tabs-context';

/**
 * A single tab inside a `udx-tabs` tablist; renders as a link when `href` is
 * provided, otherwise as a button.
 * @status beta
 * @parent Tabs
 * @devx
 * - `label` and `icon` are the tab's content; selection is index-based and
 *   owned by the parent `udx-tabs` -- there is no standalone `selected` input.
 * @a11y
 * - Exposes `id`, roving `tabIndex` (`0` on the selected or fallback tab,
 *   `-1` otherwise), and `aria-controls` pointing at the matching
 *   `udx-tab-panel` when the tab list is connected to a `udx-tab-panels`.
 * - `disabled` sets the native `disabled` attribute for a button tab, or
 *   `aria-disabled` and a blocked click for a link tab.
 * @limitations
 * - Horizontal layout only; there is no vertical tablist orientation.
 * - A truncated label has no built-in tooltip.
 * - `[class.x]` and `[ngClass]` bind to the `display: contents` host and have no visible effect; use `class`, `[class]`, or `classes`.
 */
@Component({
  selector: 'udx-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, Icon, StateLayer],
  host: { style: 'display: contents' },
  template: `
    @if (href() !== undefined) {
      <a
        #tabEl
        role="tab"
        [id]="domId()"
        [attr.aria-selected]="isSelected()"
        [attr.aria-controls]="panelId()"
        [attr.aria-disabled]="disabled() || null"
        [attr.tabindex]="tabIndexValue()"
        [class]="styles()['tab']"
        [attr.href]="href()"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </a>
    } @else {
      <button
        #tabEl
        type="button"
        role="tab"
        [id]="domId()"
        [attr.aria-selected]="isSelected()"
        [attr.aria-controls]="panelId()"
        [disabled]="disabled()"
        [attr.tabindex]="tabIndexValue()"
        [class]="styles()['tab']"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </button>
    }

    <ng-template #content>
      <udx-state-layer
        style="transition: 0.3s"
        [class]="styles()['stateLayer']"
        [colorName]="
          variant() === 'primary' && isSelected() ? 'primary' : 'on-surface'
        "
        stateClassName="state-ripple-group-[tab]"
      />
      <span #contentEl [class]="styles()['content']">
        @if (icon()) {
          <udx-icon [icon]="icon()!" [class]="styles()['icon']" />
        }
        <span [class]="styles()['label']">{{ label() }}</span>
      </span>
    </ng-template>
  `,
})
export class Tab {
  /** Text shown for this tab. */
  readonly label = input<string>();
  /** Icon shown alongside the label. */
  readonly icon = input<IconType>();
  /** Disables pointer, keyboard, and roving-tabindex focus for this tab. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Navigation destination; switches the inner element to a native link. */
  readonly href = input<string>();
  /** Classes applied to the root element. Angular's native `class` attribute and `[class]` binding land here, merged with the component's own classes. */
  readonly hostClass = input<string>('', { alias: 'class' });

  /** Static or state-aware classes for the component's internal elements, keyed by element name. */
  readonly classes = input<
    ElementClasses<TabInterface> | ClassNameComponent<TabInterface>
  >();

  private readonly context = inject(TABS_CONTEXT, { optional: true });

  protected readonly resolvedIndex = computed(() => this.context?.indexOf(this));
  protected readonly variant = computed<TabsVariant>(
    () => this.context?.variant() ?? 'primary',
  );
  protected readonly isSelected = computed(() =>
    resolveTabSelection({
      selectedTab: this.context?.selectedIndex() ?? null,
      index: this.resolvedIndex(),
    }),
  );
  protected readonly isFocusable = computed(
    () =>
      this.resolvedIndex() != null &&
      this.context?.focusableIndex() === this.resolvedIndex(),
  );
  protected readonly tabIndexValue = computed(() =>
    this.disabled() ? -1 : this.isSelected() || this.isFocusable() ? 0 : -1,
  );
  protected readonly domId = computed(() => {
    const tabsId = this.context?.tabsId();
    const index = this.resolvedIndex();
    return tabsId != null && index != null
      ? `tab-${tabsId}-${index}`
      : undefined;
  });
  protected readonly panelId = computed(() => {
    if (!this.context?.hasPanels()) return undefined;
    const tabsId = this.context?.tabsId();
    const index = this.resolvedIndex();
    return tabsId != null && index != null
      ? `tabpanel-${tabsId}-${index}`
      : undefined;
  });

  protected readonly styles = createStyle(tabStyle, () => ({
    label: this.label(),
    icon: this.icon(),
    variant: this.variant(),
    disabled: this.disabled(),
    index: this.resolvedIndex(),
    selectedTab: this.context?.selectedIndex() ?? null,
    tabsId: this.context?.tabsId(),
    isSelected: this.isSelected(),
    className: mergeClassNames<TabInterface>(
      'tab',
      this.classes(),
      this.hostClass(),
    ),
  }));

  private readonly tabElement =
    viewChild<ElementRef<HTMLElement>>('tabEl');
  private readonly contentElementRef =
    viewChild<ElementRef<HTMLSpanElement>>('contentEl');

  /** Read by the parent `udx-tabs` to focus and measure this tab. */
  get nativeElement(): HTMLElement | null {
    return this.tabElement()?.nativeElement ?? null;
  }

  /**
   * Read by the parent `udx-tabs`: the icon+label content element, which the
   * sliding indicator measures for the `primary` variant instead of the
   * full tab (`secondary` measures the tab itself).
   */
  get contentElement(): HTMLSpanElement | null {
    return this.contentElementRef()?.nativeElement ?? null;
  }

  protected handleClick(event: Event): void {
    if (this.disabled()) {
      event.preventDefault();
      return;
    }
    const index = this.resolvedIndex();
    if (index != null) {
      this.context?.select(index);
    }
  }
}

// packages/ui-svelte/src/lib/tabs/Tab.svelte
<script lang="ts">
  import { resolveTabSelection, tabStyle, mergeClassNames, type TabInterface } from '@udixio/core';
  import Icon from '../icon/Icon.svelte';
  import StateLayer from '../state-layer/StateLayer.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import { getTabsContext, type TabRegistration } from './tabs-context.svelte';
  import type { SvelteTabProps } from './tab.types';

  let { label, icon, children, disabled = false, href, class: hostClass = '', classes, onclick, ...rest }: SvelteTabProps = $props();
  const context = getTabsContext();
  const registration = $state<TabRegistration>({ label: undefined, icon: undefined, disabled: false });
  const resolvedIndex = $derived(context?.indexOf(registration));
  const selectedIndex = $derived(context?.selectedIndex() ?? null);
  const isSelected = $derived(resolveTabSelection({ selectedTab: selectedIndex, index: resolvedIndex }));
  const isFocusable = $derived(resolvedIndex != null && context?.focusableIndex() === resolvedIndex);
  const variant = $derived(context?.variant() ?? 'primary');
  const tabsId = $derived(context?.tabsId());
  const domId = $derived(tabsId !== undefined && resolvedIndex !== undefined ? `tab-${tabsId}-${resolvedIndex}` : undefined);
  const panelId = $derived(context?.hasPanels() && tabsId !== undefined && resolvedIndex !== undefined ? `tabpanel-${tabsId}-${resolvedIndex}` : undefined);
  const resolvedLabel = $derived(label ?? (children === undefined ? undefined : label));

  const styles = createStyle(tabStyle, () => ({
    label: resolvedLabel,
    icon,
    variant,
    disabled,
    index: resolvedIndex,
    selectedTab: selectedIndex,
    tabsId,
    isSelected,
    className: mergeClassNames<TabInterface>('tab', classes, hostClass),
  }));

  let root: HTMLElement | undefined = $state();
  let content: HTMLSpanElement | undefined = $state();
  $effect(() => {
    registration.element = root;
    registration.content = content;
    registration.label = label;
    registration.icon = icon;
    registration.disabled = disabled;
    if (!context) return;
    const unregister = context.registerTab(registration);
    return unregister;
  });

  const handleClick = (event: MouseEvent & { currentTarget: EventTarget & (HTMLButtonElement | HTMLAnchorElement) }) => {
    if (disabled) {
      if (href !== undefined) event.preventDefault();
      return;
    }
    if (resolvedIndex != null) context?.select(resolvedIndex);
    onclick?.(event);
  };
</script>

{#if href !== undefined}
  <a
    {...rest}
    bind:this={root}
    role="tab"
    id={domId}
    aria-selected={isSelected}
    aria-controls={panelId}
    aria-disabled={disabled || undefined}
    tabindex={disabled ? -1 : (isSelected || isFocusable ? 0 : -1)}
    href={disabled ? undefined : href}
    class={styles.current['tab']}
    onclick={handleClick}
  >
    {@render contentMarkup()}
  </a>
{:else}
  <button
    {...rest}
    bind:this={root}
    type="button"
    role="tab"
    id={domId}
    aria-selected={isSelected}
    aria-controls={panelId}
    disabled={disabled}
    tabindex={disabled ? -1 : (isSelected || isFocusable ? 0 : -1)}
    class={styles.current['tab']}
    onclick={handleClick}
  >
    {@render contentMarkup()}
  </button>
{/if}

{#snippet contentMarkup()}
  <StateLayer
    transitionDuration={0.3}
    class={styles.current['stateLayer']}
    colorName={variant === 'primary' && isSelected ? 'primary' : 'on-surface'}
    stateClassName="state-ripple-group-[tab]"
  />
  <span bind:this={content} class={styles.current['content']}>
    {#if icon}<Icon icon={icon} class={styles.current['icon']} />{/if}
    <span class={styles.current['label']}>{#if children}{@render children()}{:else}{label}{/if}</span>
  </span>
{/snippet}
