// packages/ui-react/src/lib/components/Tooltip.tsx
import {
  cloneElement,
  isValidElement,
  type ReactNode,
  type RefObject,
  useEffect,
  useRef,
} from 'react';
import type { Transition } from 'motion';
import { AnimatePresence, motion } from 'motion/react';
import {
  type ReactProps,
  type TooltipInterface,
  tooltipStyle,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';
import { Button, type ReactButtonProps } from './Button';
import { AnchorPositioner } from './AnchorPositioner';
import { useTooltipTrigger } from '../hooks';

export type {
  TooltipPosition,
  TooltipTrigger,
  TooltipVariant,
} from '@udixio/core';

export type ReactTooltipProps<T extends HTMLElement = any> =
  ReactProps<TooltipInterface> & {
    /** Custom content slot that replaces title/text/buttons when provided */
    content?: ReactNode;
    buttons?: ReactButtonProps | ReactButtonProps[];
    transition?: Transition;
    /** Custom anchor for positioning. Defaults to the trigger element. */
    anchorRef?: RefObject<HTMLElement>;
  } & (
      | {
          children?: never;
          targetRef: RefObject<T>;
        }
      | {
          children: ReactNode;
          targetRef?: never;
        }
    );

export const useTooltipStyle = createUseStyle(tooltipStyle);

/**
 * Tooltips display brief labels or messages
 * @status beta
 * @category Communication
 * @devx
 * - `content` overrides `title`/`text`/`buttons` for fully custom content.
 * - Supports controlled `isOpen` plus `openDelay`/`closeDelay`.
 * @a11y
 * - Provides `role="tooltip"` and `aria-describedby` when open.
 */
export const Tooltip = ({
  variant = 'plain',
  buttons,
  className,
  children,
  title,
  text,
  content,
  position: positionProp,
  targetRef,
  ref,
  trigger = ['hover', 'focus'],
  transition,
  openDelay = 400,
  closeDelay = 150,
  isOpen: isOpenProp,
  defaultOpen = false,
  onOpenChange,
  id,
  anchorRef,
  ...props
}: ReactTooltipProps) => {
  const defaultPosition = variant === 'rich' ? 'bottom-right' : 'bottom';
  const effectivePosition = positionProp || defaultPosition;

  transition = { duration: 0.3, ...transition };

  if (!children && !targetRef) {
    throw new Error('Tooltip must have a child or a targetRef');
  }

  if (buttons && !Array.isArray(buttons)) {
    buttons = [buttons];
  }

  const internalRef = useRef<HTMLElement | null>(null);
  const resolvedRef = targetRef || internalRef;
  const positioningRef = anchorRef || resolvedRef;

  // Use the trigger hook for state management and accessibility
  const { triggerProps, tooltipProps, isOpen } = useTooltipTrigger({
    trigger,
    isOpen: isOpenProp,
    defaultOpen,
    onOpenChange,
    openDelay,
    closeDelay,
    id,
  });

  // Apply trigger props to the target element
  const enhancedChildren =
    !targetRef && isValidElement(children)
      ? cloneElement(children, {
          ref: internalRef,
          ...triggerProps,
          // Merge event handlers if the child already has them
          onMouseEnter: (e: React.MouseEvent) => {
            triggerProps.onMouseEnter();
            (children.props as any)?.onMouseEnter?.(e);
          },
          onMouseLeave: (e: React.MouseEvent) => {
            triggerProps.onMouseLeave();
            (children.props as any)?.onMouseLeave?.(e);
          },
          onFocus: (e: React.FocusEvent) => {
            triggerProps.onFocus();
            (children.props as any)?.onFocus?.(e);
          },
          onBlur: (e: React.FocusEvent) => {
            triggerProps.onBlur();
            (children.props as any)?.onBlur?.(e);
          },
          onClick: (e: React.MouseEvent) => {
            triggerProps.onClick();
            (children.props as any)?.onClick?.(e);
          },
          onKeyDown: (e: React.KeyboardEvent) => {
            triggerProps.onKeyDown(e);
            (children.props as any)?.onKeyDown?.(e);
          },
        } as any)
      : children;

  // Attach trigger handlers when using targetRef (no direct child to clone)
  useEffect(() => {
    if (!targetRef) return;
    const element = targetRef.current;
    if (!element) return;

    const handleMouseEnter = () => triggerProps.onMouseEnter();
    const handleMouseLeave = () => triggerProps.onMouseLeave();
    const handleFocus = () => triggerProps.onFocus();
    const handleBlur = () => triggerProps.onBlur();
    const handleClick = () => triggerProps.onClick();
    const handleKeyDown = (event: KeyboardEvent) =>
      triggerProps.onKeyDown(event as unknown as React.KeyboardEvent);

    element.addEventListener('mouseenter', handleMouseEnter);
    element.addEventListener('mouseleave', handleMouseLeave);
    element.addEventListener('focus', handleFocus, true);
    element.addEventListener('blur', handleBlur, true);
    element.addEventListener('click', handleClick);
    element.addEventListener('keydown', handleKeyDown);

    if (triggerProps['aria-describedby']) {
      element.setAttribute(
        'aria-describedby',
        triggerProps['aria-describedby'],
      );
    } else {
      element.removeAttribute('aria-describedby');
    }

    return () => {
      element.removeEventListener('mouseenter', handleMouseEnter);
      element.removeEventListener('mouseleave', handleMouseLeave);
      element.removeEventListener('focus', handleFocus, true);
      element.removeEventListener('blur', handleBlur, true);
      element.removeEventListener('click', handleClick);
      element.removeEventListener('keydown', handleKeyDown);
    };
  }, [targetRef, triggerProps]);

  const styles = useTooltipStyle({
    variant,
    title,
    text,
    position: effectivePosition,
    trigger,
    openDelay,
    closeDelay,
    isOpen: isOpenProp,
    defaultOpen,
    onOpenChange,
    id,
    isVisible: isOpen,
    className,
  });

  const variants = {
    open: {
      opacity: 1,
      height: 'auto',
    },
    close: {
      opacity: 0,
      height: 16,
    },
  };

  return (
    <>
      {enhancedChildren}
      <AnimatePresence>
        {isOpen && (
          <AnchorPositioner
            anchorRef={positioningRef}
            position={effectivePosition}
          >
            <motion.div
              initial={'close'}
              variants={variants}
              animate={'open'}
              transition={{ duration: transition.duration }}
              exit={'close'}
              className={styles.toolTip}
              {...(props as any)}
              {...tooltipProps}
            >
              <div className={styles.container}>
                {content ? (
                  <div className={styles.content}>{content}</div>
                ) : (
                  <>
                    {title && <div className={styles.subHead}>{title}</div>}
                    {text && (
                      <div className={styles.supportingText}>{text}</div>
                    )}
                    {buttons && (
                      <div className={styles.actions}>
                        {Array.isArray(buttons) &&
                          buttons.map((buttonArgs, index) => (
                            <Button
                              key={index}
                              size={'small'}
                              variant={'text'}
                              {...buttonArgs}
                            />
                          ))}
                      </div>
                    )}
                  </>
                )}
              </div>
            </motion.div>
          </AnchorPositioner>
        )}
      </AnimatePresence>
    </>
  );
};

// src/components/ToolTip.tsx
import { useEffect, useRef, useState } from 'react';
import { ReactProps } from '../utils';
import { Button } from './Button';
import { ToolTipInterface } from '../interfaces';
import { toolStyle } from '../styles';
import { v4 } from 'uuid';
import { AnimatePresence, motion } from 'motion/react';
import { SyncedFixedWrapper } from '../effects';

export const ToolTip = ({
  variant = 'plain',
  buttons,
  className,
  children,
  title,
  text,
  position,
  ref,
  trigger = ['hover', 'focus'],
}: ReactProps<ToolTipInterface>) => {
  if (!Array.isArray(trigger)) {
    trigger = [trigger];
  }

  const defaultRef = useRef<HTMLDivElement>(null);
  const resolvedRef = ref || defaultRef;

  if (buttons && !Array.isArray(buttons)) {
    buttons = [buttons];
  }

  const [currentToolTipId, setCurrentToolTipId] = useState<string | null>(null);
  const [id] = useState(v4());
  const [isVisible, setIsVisible] = useState(currentToolTipId === id);

  const timeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const handleUpdate = (event: CustomEvent) => {
      setCurrentToolTipId(event.detail);
    };

    document.addEventListener('tooltip-update', handleUpdate as EventListener);
    return () => {
      document.removeEventListener(
        'tooltip-update',
        handleUpdate as EventListener
      );
    };
  }, []);

  useEffect(() => {
    if (timeout.current) clearTimeout(timeout.current);

    if (currentToolTipId) {
      setIsVisible(currentToolTipId === id);
    } else {
      timeout.current = setTimeout(() => {
        setIsVisible(false);
      }, 1200);
    }
  }, [currentToolTipId, id]);

  const handleMouseEnter = () => {
    if (trigger.includes('hover')) {
      const event = new CustomEvent('tooltip-update', { detail: id });
      document.dispatchEvent(event);
    }
  };

  const handleMouseLeave = () => {
    if (trigger.includes('hover')) {
      const event = new CustomEvent('tooltip-update', { detail: null });
      document.dispatchEvent(event);
    }
  };

  const handleClick = () => {
    if (trigger.includes('click')) {
      const event = new CustomEvent('tooltip-update', {
        detail: isVisible ? null : id,
      });
      document.dispatchEvent(event);
    }
  };

  const handleFocus = () => {
    if (trigger.includes('focus')) {
      const event = new CustomEvent('tooltip-update', { detail: id });
      document.dispatchEvent(event);
    }
  };

  const handleBlur = () => {
    if (trigger.includes('focus')) {
      const event = new CustomEvent('tooltip-update', { detail: null });
      document.dispatchEvent(event);
    }
  };

  useEffect(() => {
    return () => {
      if (timeout.current) clearTimeout(timeout.current);
    };
  }, []);

  if (!position && typeof window != undefined) {
    if (resolvedRef?.current && !position) {
      const rect = resolvedRef.current.getBoundingClientRect();

      const viewportWidth = window.innerWidth;
      const viewportHeight = window.innerHeight;

      const documentWidth = document.documentElement.scrollWidth;
      const documentHeight = document.documentElement.scrollHeight;

      const x = rect.left / viewportWidth; // X entre 0 et 1
      const y = rect.top / viewportHeight; // Y entre 0 et 1

      if (variant == 'plain') {
        if (x < 1 / 3) {
          position = 'right';
        } else if (x > 2 / 3) {
          position = 'left';
        } else {
          if (y > 0.5) {
            position = 'top';
          } else {
            position = 'bottom';
          }
        }
      } else {
        if (x < 1 / 2 && y < 1 / 2) {
          position = 'bottom-right';
        } else if (x > 1 / 2 && y < 1 / 2) {
          position = 'bottom-left';
        } else if (x > 1 / 2 && y > 1 / 2) {
          position = 'top-left';
        } else if (x < 1 / 2 && y > 1 / 2) {
          position = 'top-right';
        }
      }
    }
  }

  const styles = toolStyle({
    variant,
    buttons,
    className,
    title,
    text,
    position,
    trigger,
  });

  return (
    <div
      ref={resolvedRef}
      className={styles.toolTip}
      tabIndex={trigger.includes('focus') ? 0 : undefined}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      onClick={handleClick}
      onFocus={handleFocus}
      onBlur={handleBlur}
    >
      {children}

      <AnimatePresence>
        {isVisible && (
          <SyncedFixedWrapper targetRef={resolvedRef}>
            <motion.div
              onMouseEnter={handleMouseEnter}
              onMouseLeave={handleMouseLeave}
              initial={{ opacity: currentToolTipId ? 1 : 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: currentToolTipId ? 0 : 0.3 }}
              exit={{ opacity: currentToolTipId ? 1 : 0 }}
              className={styles.container}
            >
              <motion.div
                className={styles.content}
                layoutId={'tool-tip'}
                transition={{
                  type: 'spring',
                  stiffness: 200,
                  damping: 20,
                }}
              >
                {title && <div className={styles.subHead}>{title}</div>}
                <div className={styles.supportingText}>{text}</div>
                {buttons && (
                  <div className={styles.actions}>
                    {Array.isArray(buttons) &&
                      buttons.map((buttonArgs, index) => (
                        <Button
                          key={index}
                          size={'small'}
                          variant={'text'}
                          {...buttonArgs}
                        />
                      ))}
                  </div>
                )}
              </motion.div>
            </motion.div>
          </SyncedFixedWrapper>
        )}
      </AnimatePresence>
    </div>
  );
};
