// packages/ui-angular/src/lib/fab-menu/fab-menu.ts
import {
  afterRenderEffect,
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  type OnInit,
  output,
  viewChild,
} from '@angular/core';
import {
  type ButtonInterface,
  type ClassNameComponent,
  DEFAULT_FAB_MENU_CLOSE_ICON,
  type FabMenuAction,
  type FabMenuInterface,
  type FabMenuProps,
  fabMenuStyle,
} from '@udixio/core';
import {
  createFabMenuController,
  type FabMenuController,
} from '@udixio/core/dom';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { Fab } from '../fab/fab';
import { Button } from '../button/button';

const optionalBooleanAttribute = (value: unknown): boolean | undefined =>
  value === undefined ? undefined : booleanAttribute(value);

export interface FabMenuActionSelectEvent {
  action: FabMenuAction;
  index: number;
}

/**
 * FabMenu exposes related primary actions from one toggleable FAB.
 *
 * @status stable
 * @category Action
 * @devx
 * - Uses the framework-independent `actions` input.
 * - `open` is controlled; `defaultOpen` initializes uncontrolled usage.
 * - Opening contracts every trigger size to a small icon-only close control while preserving the closed footprint.
 * - Action choreography is implemented once with Motion JavaScript in `@udixio/core/dom`.
 * @a11y
 * - The trigger exposes `aria-expanded`/`aria-controls`.
 * - Opening focuses the first enabled action; Escape closes and restores trigger focus.
 * - Outside press and selection close the action group.
 * - Reduced-motion preference keeps state changes immediate and fully perceivable.
 * @limitations
 * - Consumers own action-specific side effects through the `actionSelect` output.
 */
@Component({
  selector: 'udx-fab-menu',
  standalone: true,
  imports: [Fab, Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      #root
      [class]="styles()['fabMenu']"
      [hidden]="!hasAccessibleLabel()"
      [attr.aria-hidden]="!hasAccessibleLabel() || null"
      [attr.data-open]="isOpen()"
    >
      <span
        #closedTriggerHost
        [class]="styles()['triggerSizer']"
        aria-hidden="true"
        inert
      >
        <udx-fab
          [label]="label()"
          [icon]="icon()"
          [variant]="closedTriggerVariant()"
          [size]="size()"
          [extended]="extended()"
          disabled
          [tabIndex]="-1"
        />
        <span #openTriggerHost [class]="styles()['triggerPositioner']">
          <udx-fab
            [label]="closeLabel() ?? 'Close ' + label()"
            [icon]="closeIcon() || defaultCloseIcon"
            [variant]="variant()"
            size="small"
            disabled
            [tabIndex]="-1"
          />
        </span>
      </span>

      <span #triggerHost [class]="styles()['triggerPositioner']">
        <udx-fab
          [label]="resolvedTriggerLabel()"
          [icon]="resolvedTriggerIcon()"
          [variant]="triggerVariant()"
          [size]="isOpen() ? 'small' : size()"
          [extended]="extended() && !isOpen()"
          [disabled]="disabled() || !hasAccessibleLabel()"
          [classes]="styles()['fab']"
          [aria-expanded]="isOpen()"
          [aria-controls]="panelId()"
          (click)="toggle()"
        />
      </span>

      <div
        #panel
        [id]="panelId()"
        [class]="styles()['actions']"
        role="group"
        [attr.aria-label]="resolvedActionsLabel()"
        [attr.aria-hidden]="!isOpen() || null"
        [attr.inert]="!isOpen() ? '' : null"
      >
        @for (action of actions(); track action.id; let index = $index) {
          <span [class]="styles()['actionContainer']" data-fab-menu-action>
            <udx-button
              [label]="action.label"
              [icon]="action.icon"
              [href]="action.href"
              [disabled]="disabled() || !!action.disabled"
              variant="filled"
              shape="rounded"
              [classes]="actionClassName"
              [stateColor]="actionStateColor()"
              (click)="selectAction(action, index)"
            />
          </span>
        }
      </div>
    </div>
  `,
})
export class FabMenu implements OnInit {
  readonly label = input.required<string>();
  readonly icon = input.required<FabMenuProps['icon']>();
  readonly actions = input.required<readonly FabMenuAction[]>();
  readonly closeIcon = input<FabMenuProps['closeIcon']>();
  readonly closeLabel = input<string>();
  readonly actionsLabel = input<string>();
  readonly variant = input<FabMenuProps['variant']>('primary');
  readonly size = input<FabMenuProps['size']>('small');
  readonly extended = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly open = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  });
  readonly defaultOpen = input(false, { transform: booleanAttribute });
  /** Classes or state-aware element classes applied through the shared style contract. */
  readonly classes = input<string | ClassNameComponent<FabMenuInterface>>();

  /** Emits an accepted open-state request and supports `[(open)]`. */
  readonly openChange = output<boolean>();
  /** Emits the selected action and its source index before closing. */
  readonly actionSelect = output<FabMenuActionSelectEvent>();

  private readonly openState = createControllableState({
    value: this.open,
    defaultValue: this.defaultOpen,
    onChange: (open) => this.openChange.emit(open),
    componentName: 'FabMenu',
    stateName: 'open',
  });
  protected readonly isOpen = this.openState.value;
  protected readonly hasAccessibleLabel = computed(
    () => this.label().trim() !== '',
  );
  protected readonly resolvedTriggerLabel = computed(() =>
    this.isOpen()
      ? (this.closeLabel() ?? `Close ${this.label()}`)
      : this.label(),
  );
  protected readonly resolvedTriggerIcon = computed(
    () =>
      (this.isOpen() && this.closeIcon()) ||
      (this.isOpen() ? DEFAULT_FAB_MENU_CLOSE_ICON : this.icon()),
  );
  protected readonly resolvedActionsLabel = computed(
    () => this.actionsLabel() ?? `${this.label()} actions`,
  );
  protected readonly triggerVariant = computed(
    () =>
      (this.isOpen() ? this.variant() : `${this.variant()}Container`) as
        | 'primary'
        | 'secondary'
        | 'tertiary'
        | 'primaryContainer'
        | 'secondaryContainer'
        | 'tertiaryContainer',
  );
  protected readonly closedTriggerVariant = computed(
    () =>
      `${this.variant()}Container` as
        'primaryContainer' | 'secondaryContainer' | 'tertiaryContainer',
  );
  protected readonly panelId = computed(() => `fab-menu-${this.instanceId}`);
  protected readonly defaultCloseIcon = DEFAULT_FAB_MENU_CLOSE_ICON;
  protected readonly styles = createStyle(fabMenuStyle, () => ({
    label: this.label(),
    icon: this.icon(),
    actions: this.actions(),
    closeIcon: this.closeIcon(),
    closeLabel: this.closeLabel(),
    actionsLabel: this.actionsLabel(),
    variant: this.variant(),
    size: this.size(),
    extended: this.extended(),
    disabled: this.disabled(),
    open: this.open(),
    defaultOpen: this.defaultOpen(),
    isOpen: this.isOpen(),
    className: this.classes(),
  }));

  private static nextId = 0;
  private readonly instanceId = FabMenu.nextId++;
  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly triggerHost =
    viewChild<ElementRef<HTMLElement>>('triggerHost');
  private readonly closedTriggerHost =
    viewChild<ElementRef<HTMLElement>>('closedTriggerHost');
  private readonly openTriggerHost =
    viewChild<ElementRef<HTMLElement>>('openTriggerHost');
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
  private controller?: FabMenuController;

  constructor() {
    afterRenderEffect((onCleanup) => {
      const root = this.root()?.nativeElement;
      const trigger =
        this.triggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const closedTrigger =
        this.closedTriggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const openTrigger =
        this.openTriggerHost()?.nativeElement.querySelector<HTMLElement>(
          'button, a',
        );
      const panel = this.panel()?.nativeElement;
      if (!root || !trigger || !closedTrigger || !openTrigger || !panel) return;

      const controller = createFabMenuController({
        root,
        trigger,
        closedTrigger,
        openTrigger,
        panel,
        onDismiss: () => this.openState.set(false),
      });
      this.controller = controller;
      onCleanup(() => {
        controller.destroy();
        if (this.controller === controller) {
          this.controller = undefined;
        }
      });
    });

    afterRenderEffect(() => {
      this.controller?.setOpen(this.isOpen());
    });
  }

  // The action is repainted onto a container surface, so the state layer must
  // contrast with that, not with the filled variant's own primary background.
  protected readonly actionStateColor = computed(
    () => `on-${this.variant()}-container`,
  );

  ngOnInit(): void {
    this.openState.initialize();
  }

  protected readonly actionClassName: ClassNameComponent<ButtonInterface> =
    () => ({
      button: this.styles()['action'],
    });

  protected toggle(): void {
    if (!this.disabled() && this.hasAccessibleLabel()) {
      this.openState.set(!this.isOpen());
    }
  }

  protected selectAction(action: FabMenuAction, index: number): void {
    if (this.disabled() || action.disabled) return;
    this.actionSelect.emit({ action, index });
    this.controller?.restoreFocusOnClose();
    this.openState.set(false);
  }
}

// packages/ui-svelte/src/lib/fab-menu/FabMenu.svelte
<script module lang="ts">
  let nextFabMenuId = 0;
</script>

<script lang="ts">
  import {
    DEFAULT_FAB_MENU_CLOSE_ICON,
    fabMenuStyle,
    mergeClassNames,
    type ButtonInterface,
    type ClassNameComponent,
    type FabMenuInterface,
    type FabMenuAction,
  } from '@udixio/core';
  import { createFabMenuController, type FabMenuController } from '@udixio/core/dom';
  import Button from '../button/Button.svelte';
  import Fab from '../fab/Fab.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteFabMenuProps } from './fab-menu.types';

  let {
    label,
    icon,
    actions,
    closeIcon = DEFAULT_FAB_MENU_CLOSE_ICON,
    closeLabel = `Close ${label}`,
    actionsLabel = `${label} actions`,
    variant = 'primary',
    size = 'small',
    extended = false,
    disabled = false,
    open = $bindable(),
    defaultOpen = false,
    onOpenChange,
    onActionSelect,
    class: hostClass = '',
    classes,
    ...rest
  }: SvelteFabMenuProps = $props();

  let root: HTMLDivElement | undefined = $state();
  let triggerHost: HTMLSpanElement | undefined = $state();
  let closedTriggerHost: HTMLSpanElement | undefined = $state();
  let openTriggerHost: HTMLSpanElement | undefined = $state();
  let panel: HTMLDivElement | undefined = $state();
  let controller: FabMenuController | undefined;
  const panelId = `fab-menu-${nextFabMenuId++}`;

  const openState = createControllableState({
    value: () => open,
    defaultValue: () => defaultOpen,
    onChange: (next) => onOpenChange?.(next),
    assign: (next) => (open = next),
    componentName: 'FabMenu',
    stateName: 'open',
  });
  const isOpen = $derived(openState.current);
  const hasAccessibleLabel = $derived(label.trim() !== '');
  const resolvedTriggerLabel = $derived(isOpen ? closeLabel : label);
  const resolvedTriggerIcon = $derived(isOpen ? closeIcon : icon);
  const triggerVariant = $derived(
    (isOpen ? variant : `${variant}Container`) as 'primary' | 'secondary' | 'tertiary' | 'primaryContainer' | 'secondaryContainer' | 'tertiaryContainer',
  );
  const closedTriggerVariant = $derived(`${variant}Container` as 'primaryContainer' | 'secondaryContainer' | 'tertiaryContainer');
  const actionStateColor = $derived(`on-${variant}-container`);
  const styles = createStyle(fabMenuStyle, () => ({
    label,
    icon,
    actions,
    closeIcon,
    closeLabel,
    actionsLabel,
    variant,
    size,
    extended,
    disabled,
    open,
    defaultOpen,
    isOpen,
    className: mergeClassNames<FabMenuInterface>('fabMenu', classes, hostClass),
  }));
  const actionClasses: ClassNameComponent<ButtonInterface> = () => ({ button: styles.current['action'] });

  const toggle = () => {
    if (!disabled && hasAccessibleLabel) openState.set(!isOpen);
  };

  const selectAction = (action: FabMenuAction, index: number) => {
    if (disabled || action.disabled) return;
    onActionSelect?.(action, index);
    controller?.restoreFocusOnClose();
    openState.set(false);
  };

  $effect(() => {
    if (!root || !triggerHost || !closedTriggerHost || !openTriggerHost || !panel) return;
    const trigger = triggerHost.querySelector<HTMLElement>('button, a');
    const closedTrigger = closedTriggerHost.querySelector<HTMLElement>('button, a');
    const openTrigger = openTriggerHost.querySelector<HTMLElement>('button, a');
    if (!trigger || !closedTrigger || !openTrigger) return;
    const created = createFabMenuController({
      root,
      trigger,
      closedTrigger,
      openTrigger,
      panel,
      onDismiss: () => openState.set(false),
    });
    controller = created;
    return () => {
      created.destroy();
      if (controller === created) controller = undefined;
    };
  });

  $effect(() => {
    controller?.setOpen(isOpen);
  });

  $effect(() => () => controller?.destroy());
</script>

{#if hasAccessibleLabel}
  <div
    {...rest}
    bind:this={root}
    class={styles.current['fabMenu']}
    data-open={isOpen}
  >
    <span bind:this={closedTriggerHost} class={styles.current['triggerSizer']} aria-hidden="true" inert>
      <Fab label={label} {icon} variant={closedTriggerVariant} {size} {extended} disabled tabindex={-1} />
      <span bind:this={openTriggerHost} class={styles.current['triggerPositioner']}>
        <Fab label={closeLabel} icon={closeIcon} variant={variant} size="small" disabled tabindex={-1} />
      </span>
    </span>

    <span bind:this={triggerHost} class={styles.current['triggerPositioner']}>
      <Fab
        label={resolvedTriggerLabel}
        icon={resolvedTriggerIcon}
        variant={triggerVariant}
        size={isOpen ? 'small' : size}
        extended={extended && !isOpen}
        {disabled}
        class={styles.current['fab']}
        aria-expanded={isOpen}
        aria-controls={panelId}
        onclick={toggle}
      />
    </span>

    <div
      bind:this={panel}
      id={panelId}
      class={styles.current['actions']}
      role="group"
      aria-label={actionsLabel}
      aria-hidden={!isOpen || undefined}
      inert={!isOpen}
    >
      {#each actions as action, index (action.id)}
        <span class={styles.current['actionContainer']} data-fab-menu-action>
          <Button
            label={action.label}
            icon={action.icon}
            href={action.href}
            disabled={disabled || !!action.disabled}
            variant="filled"
            shape="rounded"
            classes={actionClasses}
            stateColor={actionStateColor}
            onclick={() => selectAction(action, index)}
          />
        </span>
      {/each}
    </div>
  </div>
{:else}
  <!-- A FAB menu without an accessible trigger has no usable surface. -->
{/if}
