// packages/ui-react/src/lib/components/MenuItem.tsx
import React, { forwardRef, type ReactNode } from 'react';
import {
  classNames,
  getMenuItemRole,
  getMenuItemSelectionTransition,
  menuItemStyle,
  type MenuItemInterface,
  type MenuItemProps,
  type ReactProps,
} from '@udixio/core';
import { iCheck } from '@udixio/icons-rounded-400/check';
import { StateLayer } from './StateLayer';
import { Icon } from '../icon';
import { createUseStyle } from '../utils/create-use-style';
import { useControllableState } from '../utils/use-controllable-state';
import { useMenuContext } from './menu-context';

export type { MenuItemSelectionType, MenuItemVariant } from '@udixio/core';

export type ReactMenuItemProps = Omit<
  ReactProps<MenuItemInterface>,
  | 'aria-checked'
  | 'aria-disabled'
  | 'aria-selected'
  | 'disabled'
  | 'leadingIcon'
  | 'role'
  | 'trailingIcon'
> & {
  /** Custom visible label content; falls back to `label`. */
  children?: ReactNode;
  /** Optional navigation target; disabled links omit the native href. */
  href?: string;
  /** Optional icon displayed before the label. Commands share this leading column when any command uses an icon; selection items keep their own indicator. */
  leadingIcon?: MenuItemProps['leadingIcon'];
  /** Optional decorative icon displayed after the label; use MenuSubmenu for a chevron that opens another menu. */
  trailingIcon?: MenuItemProps['trailingIcon'];
  /** Prevents activation, selection changes, and keyboard focus. */
  disabled?: MenuItemProps['disabled'];
};

export const useMenuItemStyle = createUseStyle(menuItemStyle);

/**
 * An action or selectable choice within a Menu.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx
 * - Use `selectionType`, `selected`, and `onSelectedChange` for controlled selection.
 * - Use `defaultSelected` when the item owns its initial selection state.
 * @a11y
 * - Resolves to `menuitem`, `menuitemradio`, `menuitemcheckbox`, or `option` from the parent Menu purpose.
 * - Disabled links are removed from navigation and expose `aria-disabled`.
 * - Use `MenuSubmenu` when the row should open another action menu.
 */
export const MenuItem = forwardRef<
  HTMLButtonElement | HTMLAnchorElement,
  ReactMenuItemProps
>(
  (
    {
      label,
      children,
      value,
      leadingIcon,
      trailingIcon,
      disabled = false,
      variant,
      href,
      selectionType: selectionTypeProp,
      selected,
      defaultSelected = false,
      onSelectedChange,
      className,
      onClick,
      ...restProps
    },
    forwardedRef,
  ) => {
    const context = useMenuContext();
    const selectionType =
      selectionTypeProp ??
      (context.purpose === 'selection' ? 'single' : 'none');
    const resolvedVariant = variant ?? context.variant;
    const [isSelected, setSelected] = useControllableState({
      value: selected,
      defaultValue: defaultSelected,
      onChange: onSelectedChange,
      componentName: 'MenuItem',
      stateName: 'selected',
    });
    const role = getMenuItemRole({
      purpose: context.purpose,
      selectionType,
    });
    const usesActionIconSlot =
      context.purpose === 'actions' && selectionType === 'none';
    const resolvedLeadingIcon =
      isSelected && selectionType !== 'none' ? iCheck : leadingIcon;
    const styles = useMenuItemStyle({
      label,
      value,
      leadingIcon,
      trailingIcon,
      disabled,
      variant: resolvedVariant,
      selectionType,
      selected,
      defaultSelected,
      onSelectedChange,
      isSelected,
      purpose: context.purpose,
      className,
    });

    const activate = (
      event: React.MouseEvent<HTMLButtonElement | HTMLAnchorElement>,
    ) => {
      if (disabled) {
        event.preventDefault();
        return;
      }
      const transition = getMenuItemSelectionTransition({
        disabled,
        selectionType,
        selected: isSelected,
      });
      if (transition.nextSelected !== undefined) {
        setSelected(transition.nextSelected);
      }
      (
        onClick as
          | React.MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>
          | undefined
      )?.(event);
    };

    const sharedProps = {
      ...restProps,
      ref: forwardedRef,
      className: styles.menuItem,
      role,
      'aria-disabled': disabled || undefined,
      'aria-selected':
        role === 'option' ? (isSelected ? 'true' : 'false') : undefined,
      'aria-checked':
        role === 'menuitemcheckbox' || role === 'menuitemradio'
          ? isSelected
          : undefined,
      'data-menu-disabled': disabled ? 'true' : undefined,
      'data-menu-leading-icon':
        usesActionIconSlot && leadingIcon ? 'true' : undefined,
      tabIndex: disabled ? -1 : 0,
      onClick: activate,
    };
    const content = (
      <>
        {!disabled && (
          <StateLayer
            className={styles.stateLayer}
            colorName={
              resolvedVariant === 'vibrant' || isSelected
                ? 'on-tertiary-container'
                : 'on-secondary-container'
            }
            stateClassName="state-ripple-group-[menu-item]"
          />
        )}
        {usesActionIconSlot ? (
          <span
            aria-hidden="true"
            data-menu-leading-icon-slot
            style={resolvedLeadingIcon ? undefined : { display: 'none' }}
            className={classNames(
              styles.itemIcon,
              styles.leadingIcon,
              'z-10 relative',
            )}
          >
            {resolvedLeadingIcon && <Icon icon={resolvedLeadingIcon} />}
          </span>
        ) : resolvedLeadingIcon ? (
          <span
            aria-hidden="true"
            className={classNames(
              styles.itemIcon,
              styles.leadingIcon,
              'z-10 relative',
            )}
          >
            <Icon icon={resolvedLeadingIcon} />
          </span>
        ) : null}
        <span className={classNames(styles.itemLabel, 'z-10 relative')}>
          {children ?? label}
        </span>
        {trailingIcon && (
          <span
            aria-hidden="true"
            className={classNames(
              styles.itemIcon,
              styles.trailingIcon,
              'z-10 relative',
            )}
          >
            <Icon icon={trailingIcon} />
          </span>
        )}
      </>
    );

    return href ? (
      <a
        {...(sharedProps as React.AnchorHTMLAttributes<HTMLAnchorElement>)}
        href={disabled ? undefined : href}
      >
        {content}
      </a>
    ) : (
      <button
        {...(sharedProps as React.ButtonHTMLAttributes<HTMLButtonElement>)}
        type="button"
        disabled={disabled}
        value={value}
      >
        {content}
      </button>
    );
  },
);

MenuItem.displayName = 'MenuItem';

// packages/ui-angular/src/lib/menu/menu-item.ts
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
  type OnInit,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  getMenuItemRole,
  getMenuItemSelectionTransition,
  menuItemStyle,
  type ClassNameComponent,
  type ElementClasses,
  mergeClassNames,
  type MenuItemInterface,
  type MenuItemProps,
} from '@udixio/core';
import { iCheck } from '@udixio/icons-rounded-400/check';
import { Icon } from '../icon/icon';
import { StateLayer } from '../state-layer/state-layer';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { MENU_CONTEXT } from './menu-context';

const optionalBooleanAttribute = (value: unknown): boolean | undefined =>
  value === undefined ? undefined : booleanAttribute(value);

/**
 * An action or selectable choice within a Menu.
 * @status beta
 * @category Selection
 * @parent menu
 * @devx Use `selectionType`, `selected`, and `selectedChange` for controlled selection, or initialize with `defaultSelected`.
 * @a11y Resolves to `menuitem`, `menuitemradio`, `menuitemcheckbox`, or `option`; disabled links are inert and removed from navigation.
 * @limitations
 * - Angular uses the required `label` input instead of projected item content; use `udx-menu-submenu` for nested actions.
 * - `[class.x]` and `[ngClass]` bind to the `display: contents` host and have no visible effect; use `class`, `[class]`, or `classes`.
 */
@Component({
  selector: 'udx-menu-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @if (href()) {
      <a
        [class]="styles()['menuItem']"
        [attr.href]="disabled() ? null : href()"
        [attr.role]="role()"
        [attr.aria-disabled]="disabled() || null"
        [attr.aria-selected]="role() === 'option' ? isSelected() : null"
        [attr.aria-checked]="isCheckedRole() ? isSelected() : null"
        [attr.data-menu-disabled]="disabled() || null"
        [attr.data-menu-leading-icon]="hasActionLeadingIcon() ? 'true' : null"
        [attr.tabindex]="disabled() ? -1 : 0"
        (click)="activate($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </a>
    } @else {
      <button
        type="button"
        [class]="styles()['menuItem']"
        [disabled]="disabled()"
        [value]="value() ?? ''"
        [attr.role]="role()"
        [attr.aria-selected]="role() === 'option' ? isSelected() : null"
        [attr.aria-checked]="isCheckedRole() ? isSelected() : null"
        [attr.data-menu-disabled]="disabled() || null"
        [attr.data-menu-leading-icon]="hasActionLeadingIcon() ? 'true' : null"
        (click)="activate($event)"
      >
        <ng-container [ngTemplateOutlet]="content" />
      </button>
    }

    <ng-template #content>
      @if (!disabled()) {
        <udx-state-layer
          [class]="styles()['stateLayer']"
          [colorName]="stateColor()"
          stateClassName="state-ripple-group-[menu-item]"
        />
      }
      @if (usesActionIconSlot()) {
        <span
          aria-hidden="true"
          data-menu-leading-icon-slot
          [style.display]="resolvedLeadingIcon() ? null : 'none'"
          [class]="
            styles()['itemIcon'] +
            ' ' +
            styles()['leadingIcon'] +
            ' z-10 relative'
          "
        >
          @if (resolvedLeadingIcon()) {
            <udx-icon [icon]="resolvedLeadingIcon()!" />
          }
        </span>
      } @else if (resolvedLeadingIcon()) {
        <span
          aria-hidden="true"
          [class]="
            styles()['itemIcon'] +
            ' ' +
            styles()['leadingIcon'] +
            ' z-10 relative'
          "
        >
          <udx-icon [icon]="resolvedLeadingIcon()!" />
        </span>
      }
      <span [class]="styles()['itemLabel'] + ' z-10 relative'">
        {{ label() }}
      </span>
      @if (trailingIcon()) {
        <span
          aria-hidden="true"
          [class]="
            styles()['itemIcon'] +
            ' ' +
            styles()['trailingIcon'] +
            ' z-10 relative'
          "
        >
          <udx-icon [icon]="trailingIcon()!" />
        </span>
      }
    </ng-template>
  `,
  imports: [Icon, StateLayer, NgTemplateOutlet],
})
export class MenuItem implements OnInit {
  readonly label = input.required<string>();
  readonly value = input<MenuItemProps['value']>();
  /** Optional icon displayed before the label. Commands share this leading column when any command uses an icon; selection items keep their own indicator. */
  readonly leadingIcon = input<MenuItemProps['leadingIcon']>();
  /** Optional decorative icon displayed after the label; use `udx-menu-submenu` for an interactive chevron. */
  readonly trailingIcon = input<MenuItemProps['trailingIcon']>();
  /** Prevents activation, selection changes, and keyboard focus. */
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly variant = input<MenuItemProps['variant']>();
  readonly selectionType = input<MenuItemProps['selectionType']>();
  readonly selected = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  });
  readonly defaultSelected = input(false, { transform: booleanAttribute });
  /** Optional navigation target; disabled links omit the native href. */
  readonly href = input<string>();
  /** Classes applied to the root element. Angular's native `class` attribute and `[class]` binding land here, merged with the component's own classes. */
  readonly hostClass = input<string>('', { alias: 'class' });

  /** Static or state-aware classes for the component's internal elements, keyed by element name. */
  readonly classes = input<
    ElementClasses<MenuItemInterface> | ClassNameComponent<MenuItemInterface>
  >();

  /** Emits each accepted selected-state request and supports `[(selected)]`. */
  readonly selectedChange = output<boolean>();

  private readonly context = inject(MENU_CONTEXT, { optional: true });
  private readonly selection = createControllableState({
    value: this.selected,
    defaultValue: this.defaultSelected,
    onChange: (selected) => this.selectedChange.emit(selected),
    componentName: 'MenuItem',
    stateName: 'selected',
  });
  protected readonly isSelected = this.selection.value;
  protected readonly purpose = computed(
    () => this.context?.purpose() ?? 'actions',
  );
  protected readonly resolvedSelectionType = computed(
    () =>
      this.selectionType() ??
      (this.purpose() === 'selection' ? 'single' : 'none'),
  );
  protected readonly resolvedVariant = computed(
    () => this.variant() ?? this.context?.variant() ?? 'standard',
  );
  protected readonly role = computed(() =>
    getMenuItemRole({
      purpose: this.purpose(),
      selectionType: this.resolvedSelectionType(),
    }),
  );
  protected readonly usesActionIconSlot = computed(
    () =>
      this.purpose() === 'actions' && this.resolvedSelectionType() === 'none',
  );
  protected readonly hasActionLeadingIcon = computed(
    () => this.usesActionIconSlot() && Boolean(this.leadingIcon()),
  );
  protected readonly isCheckedRole = computed(
    () => this.role() === 'menuitemcheckbox' || this.role() === 'menuitemradio',
  );
  protected readonly resolvedLeadingIcon = computed(() =>
    this.isSelected() && this.resolvedSelectionType() !== 'none'
      ? iCheck
      : this.leadingIcon(),
  );
  protected readonly stateColor = computed(() =>
    this.resolvedVariant() === 'vibrant' || this.isSelected()
      ? 'on-tertiary-container'
      : 'on-secondary-container',
  );
  protected readonly styles = createStyle(menuItemStyle, () => ({
    label: this.label(),
    value: this.value(),
    leadingIcon: this.leadingIcon(),
    trailingIcon: this.trailingIcon(),
    disabled: this.disabled(),
    variant: this.resolvedVariant(),
    selectionType: this.resolvedSelectionType(),
    selected: this.selected(),
    defaultSelected: this.defaultSelected(),
    onSelectedChange: undefined,
    isSelected: this.isSelected(),
    purpose: this.purpose(),
    className: mergeClassNames<MenuItemInterface>(
      'menuItem',
      this.classes(),
      this.hostClass(),
    ),
  }));

  ngOnInit(): void {
    this.selection.initialize();
  }

  protected activate(event: Event): void {
    if (this.disabled()) {
      event.preventDefault();
      return;
    }
    const transition = getMenuItemSelectionTransition({
      disabled: false,
      selectionType: this.resolvedSelectionType(),
      selected: this.isSelected(),
    });
    if (transition.nextSelected !== undefined) {
      this.selection.set(transition.nextSelected);
    }
  }
}
