// packages/ui-svelte/src/lib/carousel/Carousel.svelte
<script lang="ts">
  import {
    carouselStyle,
    customScrollStyle,
    mergeClassNames,
    type CarouselInterface,
    type CarouselMetrics,
  } from '@udixio/core';
  import { createCarouselController, createCustomScrollController, type CarouselController, type CustomScrollController } from '@udixio/core/dom';
  import { untrack } from 'svelte';
  import { setCarouselContext } from './carousel-context.svelte';
  import type { CarouselItemRegistration } from './carousel-item-registration.svelte';
  import { createControllableState } from '../utils/create-controllable-state.svelte';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteCarouselProps } from './carousel.types';

  const clamp01 = (value: number) => Math.min(1, Math.max(0, value));

  let {
    children,
    variant = 'hero',
    gap = 8,
    scrollSensitivity = 1.25,
    outputRange = [42, 300],
    index = $bindable(),
    defaultIndex = 0,
    onIndexChange,
    onMetricsChange,
    accessibleLabel,
    class: hostClass = '',
    style: hostStyle,
    classes,
    onkeydown,
    ...rest
  }: SvelteCarouselProps = $props();

  let items = $state<CarouselItemRegistration[]>([]);
  let root: HTMLDivElement | undefined = $state();
  let scrollContainer: HTMLDivElement | undefined = $state();
  let scrollContent: HTMLDivElement | undefined = $state();
  let track: HTMLDivElement | undefined = $state();
  let viewportWidth = $state(0);
  let scrollVisible = $state(0);
  let isDragging = $state(false);
  let focusedIndex = $state(0);
  let carouselController: CarouselController | undefined;
  let customScrollController: CustomScrollController | undefined;
  let lastReportedIndex: number | undefined;
  let lastMetrics: CarouselMetrics | undefined;

  const indexState = createControllableState({
    value: () => index,
    defaultValue: () => defaultIndex,
    onChange: (next) => onIndexChange?.(next),
    assign: (next) => (index = next),
    componentName: 'Carousel',
    stateName: 'index',
  });
  const selectedIndex = $derived(indexState.current);
  const scrollSize = $derived(((Math.min(outputRange[1], viewportWidth || outputRange[1]) + gap) * items.length) / scrollSensitivity || 400);
  const spacerWidth = $derived(Math.max(0, scrollSize - viewportWidth));
  const styles = createStyle(carouselStyle, () => ({
    variant,
    gap,
    scrollSensitivity,
    outputRange,
    index,
    defaultIndex,
    onIndexChange,
    onMetricsChange,
    selectedIndex,
    className: mergeClassNames<CarouselInterface>('carousel', classes, hostClass),
  }));
  const scrollStyles = createStyle(customScrollStyle, () => ({
    orientation: 'horizontal' as const,
    draggable: true,
    isDragging,
    scrollSize,
    onScroll: undefined,
    scroll: undefined,
    setScroll: undefined,
    throttleDuration: 75,
    className: undefined,
  }));

  setCarouselContext({
    outputRange: () => outputRange,
    selectedIndex: () => indexState.current,
    indexOf: (item) => {
      const value = items.indexOf(item);
      return value === -1 ? undefined : value;
    },
    registerItem: (item) => {
      items = [...untrack(() => items), item];
      return () => { items = untrack(() => items).filter((candidate) => candidate !== item); };
    },
  });

  const emitMetrics = () => {
    if (!root || items.length === 0) return;
    const total = items.length;
    const viewport = root.clientWidth || 0;
    const visibleApprox = (viewport + gap) / (outputRange[1] + gap);
    const visibleFull = Math.max(1, Math.floor(visibleApprox));
    const stepHalf = Math.max(1, Math.round(visibleFull * (2 / 3)));
    const safeIndex = Math.min(Math.max(0, selectedIndex), Math.max(0, total - 1));
    const metrics: CarouselMetrics = {
      total,
      selectedIndex: safeIndex,
      visibleApprox,
      visibleFull,
      stepHalf,
      canPrev: safeIndex > 0,
      canNext: safeIndex < total - 1,
      scrollProgress: carouselController?.getProgress() ?? 0,
      viewportWidth: viewport,
      itemMaxWidth: outputRange[1],
      gap,
    };
    const changed = !lastMetrics || (Object.keys(metrics) as (keyof CarouselMetrics)[]).some((key) => metrics[key] !== lastMetrics?.[key]);
    if (changed) {
      lastMetrics = metrics;
      onMetricsChange?.(metrics);
    }
  };

  const centerOnIndex = (next: number) => {
    const safe = Math.min(Math.max(0, next), Math.max(0, items.length - 1));
    focusedIndex = safe;
    customScrollController?.scrollTo({ progress: clamp01(safe / Math.max(1, items.length - 1)), orientation: 'horizontal' });
  };

  const handleKeydown = (event: KeyboardEvent) => {
    if (!items.length) return;
    if (event.key === 'ArrowLeft') { event.preventDefault(); centerOnIndex(focusedIndex - 1); }
    else if (event.key === 'ArrowRight') { event.preventDefault(); centerOnIndex(focusedIndex + 1); }
    else if (event.key === 'Home') { event.preventDefault(); centerOnIndex(0); }
    else if (event.key === 'End') { event.preventDefault(); centerOnIndex(items.length - 1); }
    onkeydown?.(event);
  };

  $effect(() => {
    if (!root || !scrollContainer || !scrollContent || !track) return;
    const host = root;
    const container = scrollContainer;
    const content = scrollContent;
    const carouselTrack = track;
    // Controller creation must be independent of child registration. The
    // controller accessors intentionally read the latest signals later; if
    // setup tracked `items` through the initial synchronous layout pass, every
    // item mount would destroy and recreate the controllers.
    return untrack(() => {
      const custom = createCustomScrollController({
        container,
        content,
        orientation: () => 'horizontal',
        scrollSize: () => scrollSize,
        draggable: () => true,
        onScroll: (metrics) => {
          scrollVisible = metrics.scrollVisible;
          carouselController?.setProgress(metrics.scrollProgress);
        },
        onDraggingChange: (value) => { isDragging = value; },
        onDimensionsChange: (dimensions) => { viewportWidth = dimensions.width; },
      });
      const carousel = createCarouselController({
        track: carouselTrack,
        items: () => items.map((item) => item.element ?? null),
        viewport: () => scrollVisible || host.clientWidth || 0,
        gap: () => gap,
        minItemWidth: () => outputRange[0],
        maxItemWidth: () => outputRange[1],
        onSelectedIndexChange: (next) => { lastReportedIndex = next; indexState.set(next); focusedIndex = next; emitMetrics(); },
      });
      customScrollController = custom;
      carouselController = carousel;
      custom.notifyInitial();
      carousel.setProgress(items.length > 1 ? clamp01(selectedIndex / Math.max(1, items.length - 1)) : 0, { animate: false });
      return () => {
        custom.destroy();
        carousel.destroy();
        if (customScrollController === custom) customScrollController = undefined;
        if (carouselController === carousel) carouselController = undefined;
      };
    });
  });

  $effect(() => {
    items;
    gap;
    outputRange;
    carouselController?.update();
    emitMetrics();
  });

  $effect(() => {
    const external = index;
    if (external !== undefined && external !== lastReportedIndex && items.length) centerOnIndex(external);
  });
</script>

<div
  {...rest}
  bind:this={root}
  class={styles.current['carousel']}
  style={hostStyle}
  role="region"
  aria-label={accessibleLabel}
  aria-roledescription="carousel"
  onkeydown={handleKeydown}
>
  <div bind:this={scrollContainer} class={scrollStyles.current['customScroll']}>
    <div bind:this={scrollContent} class={scrollStyles.current['track']} style={`width: ${viewportWidth}px`}>
      <div bind:this={track} class={styles.current['track']} style={`gap: ${gap}px; will-change: transform`}>
        {@render children?.()}
      </div>
    </div>
    {#if spacerWidth > 0}<div class="flex-none" style={`width: ${spacerWidth}px`}></div>{/if}
  </div>
</div>

// packages/ui-angular/src/lib/carousel/carousel.ts
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  contentChildren,
  input,
  output,
  signal,
  viewChild,
  type OnInit,
} from '@angular/core';
import {
  carouselStyle,
  customScrollStyle,
  type CarouselInterface,
  type CarouselMetrics,
  type CarouselProps,
  type ClassNameComponent,
} from '@udixio/core';
import {
  createCarouselController,
  createCustomScrollController,
  type CarouselController,
  type CustomScrollController,
} from '@udixio/core/dom';
import { createControllableState } from '../utils/create-controllable-state';
import { createStyle } from '../utils/create-style';
import { CarouselItem } from './carousel-item';

const clamp01 = (value: number) => Math.min(1, Math.max(0, value));

/**
 * Carousels show a collection of items that can be scrolled on and off the screen.
 *
 * @status beta
 * @category Layout
 * @devx Project `lib-carousel-item` children; use `index`/`indexChange` for controlled positioning, or `defaultIndex` to seed the initial position of an uncontrolled carousel.
 * @a11y The root is a `region` with `aria-roledescription="carousel"` (set `accessibleLabel` for a name); each slide is a `group` with `aria-roledescription="slide"` and an `"n / total"` label. Roving `tabindex` keeps a single slide in the tab order; Arrow/Home/End move the selection.
 * @limitations Responsive behavior on mobile is not supported. Only the `hero` variant is implemented; `center-aligned`, `multi-browse`, `un-contained`, and `full-screen` are reserved in the type for future Material 3 layout support and currently render as `hero`.
 */
@Component({
  selector: 'lib-carousel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      #root
      [class]="styles()['carousel']"
      role="region"
      [attr.aria-label]="accessibleLabel() || null"
      aria-roledescription="carousel"
      (keydown)="handleKeyDown($event)"
    >
      <div #scrollContainer [class]="scrollStyles()['customScroll']">
        <div
          #scrollContent
          [class]="scrollStyles()['track']"
          [style.width.px]="viewportWidth() || null"
        >
          <div
            #track
            [class]="styles()['track']"
            [style.gap.px]="gap()"
            style="will-change: transform"
          >
            <ng-content />
          </div>
        </div>

        @if (spacerWidth() > 0) {
          <div class="flex-none" [style.width.px]="spacerWidth()"></div>
        }
      </div>
    </div>
  `,
})
export class Carousel implements OnInit {
  readonly variant = input<CarouselProps['variant']>('hero');
  readonly gap = input(8);
  readonly scrollSensitivity = input(1.25);
  readonly outputRange = input<[number, number]>([42, 300]);
  readonly index = input<number>();
  readonly defaultIndex = input(0);
  readonly accessibleLabel = input<string>();
  readonly className = input<string | ClassNameComponent<CarouselInterface>>();

  /** Emits an accepted centered-index transition. */
  readonly indexChange = output<number>();
  /** Receives live metrics to better control the carousel externally. */
  readonly metricsChange = output<CarouselMetrics>();

  private readonly root = viewChild<ElementRef<HTMLElement>>('root');
  private readonly scrollContainer =
    viewChild<ElementRef<HTMLElement>>('scrollContainer');
  private readonly scrollContent =
    viewChild<ElementRef<HTMLElement>>('scrollContent');
  private readonly track = viewChild<ElementRef<HTMLElement>>('track');
  private readonly items = contentChildren(CarouselItem, {
    read: ElementRef<HTMLElement>,
  });

  private readonly indexState = createControllableState({
    value: this.index,
    defaultValue: this.defaultIndex,
    onChange: (value) => this.indexChange.emit(value),
    componentName: 'Carousel',
    stateName: 'index',
  });
  protected readonly selectedIndex = this.indexState.value;

  /** Last index the user explicitly targeted; the keyboard-nav baseline. */
  private readonly focusedIndex = signal(0);
  protected readonly viewportWidth = signal(0);
  private readonly isDragging = signal(false);

  private carouselController?: CarouselController;
  private customScrollController?: CustomScrollController;
  private scrollVisible = 0;
  private lastMetrics: CarouselMetrics | null = null;
  private didMount = false;

  protected readonly styles = createStyle(carouselStyle, () => ({
    variant: this.variant(),
    gap: this.gap(),
    scrollSensitivity: this.scrollSensitivity(),
    outputRange: this.outputRange(),
    index: this.index(),
    defaultIndex: this.defaultIndex(),
    onIndexChange: () => undefined,
    onMetricsChange: () => undefined,
    selectedIndex: this.selectedIndex(),
    className: this.className(),
  }));

  protected readonly scrollStyles = createStyle(customScrollStyle, () => ({
    orientation: 'horizontal' as const,
    draggable: true,
    isDragging: this.isDragging(),
    scrollSize: this.computeScrollSize(),
    onScroll: () => undefined,
    scroll: undefined,
    setScroll: () => undefined,
    throttleDuration: 75,
    className: undefined,
  }));

  protected readonly spacerWidth = computed(() =>
    Math.max(0, this.computeScrollSize() - this.viewportWidth()),
  );

  constructor() {
    // Create both shared controllers once the DOM exists, and seed the
    // spring at the resolved initial index instead of an implicit progress
    // of 0 (a nonzero controlled/default index must render correctly from
    // the very first frame, not be corrected a tick later).
    afterRenderEffect((onCleanup) => {
      const root = this.root()?.nativeElement;
      const container = this.scrollContainer()?.nativeElement;
      const content = this.scrollContent()?.nativeElement;
      const track = this.track()?.nativeElement;
      if (!root || !container || !content || !track) return;

      let carouselController: CarouselController | undefined;

      const customScrollController = createCustomScrollController({
        container,
        content,
        orientation: () => 'horizontal',
        scrollSize: () => this.computeScrollSize(),
        draggable: () => true,
        onScroll: (metrics) => {
          this.scrollVisible = metrics.scrollVisible;
          if (metrics.scrollTotal > 0) {
            carouselController?.setProgress(metrics.scrollProgress ?? 0);
          }
        },
        onDraggingChange: (dragging) => this.isDragging.set(dragging),
        onDimensionsChange: (dimensions) =>
          this.viewportWidth.set(dimensions.width),
      });

      carouselController = createCarouselController({
        track,
        items: () => this.items().map((ref) => ref.nativeElement),
        viewport: () => this.scrollVisible || root.clientWidth || 0,
        gap: () => this.gap(),
        minItemWidth: () => this.outputRange()[0],
        maxItemWidth: () => this.outputRange()[1],
        onSelectedIndexChange: (i) => this.indexState.set(i),
      });

      this.customScrollController = customScrollController;
      this.carouselController = carouselController;

      // Read the desired initial position BEFORE notifyInitial(), which can
      // synchronously round-trip through onScroll -> setProgress(0) and
      // would otherwise clobber a nonzero resolved index. Re-assert it last
      // so this call always wins regardless of that side effect.
      const count = this.items().length;
      const initialProgress =
        count > 1
          ? clamp01(this.selectedIndex() / Math.max(1, count - 1))
          : 0;
      customScrollController.notifyInitial();
      carouselController.setProgress(initialProgress, { animate: false });

      onCleanup(() => {
        customScrollController.destroy();
        carouselController?.destroy();
        this.customScrollController = undefined;
        this.carouselController = undefined;
      });
    });

    // Re-apply the layout when item count, gap, or size range change.
    afterRenderEffect(() => {
      this.items();
      this.gap();
      this.outputRange();
      this.carouselController?.update();
    });

    // Stamp slide semantics (role/roledescription/label) and wire focus once
    // per item-list change; only the count is a dependency here, so this
    // never re-runs mid-scroll.
    afterRenderEffect((onCleanup) => {
      const elements = this.items().map((ref) => ref.nativeElement);
      const total = elements.length;
      const unlisten = elements.map((element, i) => {
        element.setAttribute('role', 'group');
        element.setAttribute('aria-roledescription', 'slide');
        element.setAttribute('aria-label', `${i + 1} / ${total}`);
        const onFocus = () => this.focusedIndex.set(i);
        element.addEventListener('focus', onFocus);
        return () => element.removeEventListener('focus', onFocus);
      });
      onCleanup(() => unlisten.forEach((off) => off()));
    });

    // Roving tabindex: only the selected slide is in the tab order.
    afterRenderEffect(() => {
      const elements = this.items().map((ref) => ref.nativeElement);
      const selected = this.selectedIndex();
      elements.forEach((element, i) => {
        element.tabIndex = i === selected ? 0 : -1;
      });
    });

    // Re-center only when the controlled `index` input changes after mount
    // (the initial position is already seeded above). Reading the resolved
    // `selectedIndex` here instead of the raw input would fight free
    // scrolling, since scroll updates it continuously.
    afterRenderEffect(() => {
      const idx = this.index();
      const count = this.items().length;
      if (count === 0) return;
      if (!this.didMount) {
        this.didMount = true;
        return;
      }
      if (typeof idx === 'number') {
        this.centerOnIndex(idx);
      }
    });

    afterRenderEffect(() => {
      const total = this.items().length;
      const root = this.root()?.nativeElement;
      if (total <= 0 || !root) return;

      const viewportWidth = root.clientWidth || 0;
      const gap = this.gap();
      const itemMaxWidth = this.outputRange()[1];
      const scrollProgress = this.carouselController?.getProgress() ?? 0;
      const visibleApprox = (viewportWidth + gap) / (itemMaxWidth + gap);
      const visibleFull = Math.max(1, Math.floor(visibleApprox));
      const stepHalf = Math.max(1, Math.round(visibleFull * (2 / 3)));
      const selectedIndexSafe = Math.min(
        Math.max(0, this.selectedIndex()),
        Math.max(0, total - 1),
      );

      const metrics: CarouselMetrics = {
        total,
        selectedIndex: selectedIndexSafe,
        visibleApprox,
        visibleFull,
        stepHalf,
        canPrev: selectedIndexSafe > 0,
        canNext: selectedIndexSafe < total - 1,
        scrollProgress,
        viewportWidth,
        itemMaxWidth,
        gap,
      };

      const last = this.lastMetrics;
      const changed =
        !last ||
        (Object.keys(metrics) as (keyof CarouselMetrics)[]).some(
          (key) => metrics[key] !== last[key],
        );
      if (changed) {
        this.lastMetrics = metrics;
        this.metricsChange.emit(metrics);
      }
    });
  }

  ngOnInit(): void {
    this.indexState.initialize();
  }

  private computeScrollSize(): number {
    let maxWidth = this.outputRange()[1];
    const visible = this.viewportWidth();
    if (visible > 0 && maxWidth > visible) {
      maxWidth = visible;
    }
    const result =
      ((maxWidth + this.gap()) * this.items().length) /
      this.scrollSensitivity();
    return result || 400;
  }

  private centerOnIndex(idx: number): void {
    const count = this.items().length;
    if (count === 0) return;
    this.focusedIndex.set(idx);
    this.customScrollController?.scrollTo({
      progress: clamp01(idx / Math.max(1, count - 1)),
      orientation: 'horizontal',
    });
  }

  protected handleKeyDown(event: KeyboardEvent): void {
    const count = this.items().length;
    if (count === 0) return;
    const idx = this.focusedIndex();
    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault();
        this.centerOnIndex(Math.max(0, idx - 1));
        break;
      case 'ArrowRight':
        event.preventDefault();
        this.centerOnIndex(Math.min(count - 1, idx + 1));
        break;
      case 'Home':
        event.preventDefault();
        this.centerOnIndex(0);
        break;
      case 'End':
        event.preventDefault();
        this.centerOnIndex(count - 1);
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        this.centerOnIndex(idx);
        break;
    }
  }
}
